{% snapshot HIST_TRIPS_CLIENTS %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='TRIPS',
        unique_key='_AIRBYTE_RAW_ID',
        strategy='check',
        check_cols=[
            'AGE', 'LGA', 'SEX', 'TOWN', 'ZONE', 'HOIST', 'PHONE',
            'STATE', 'SYSID', 'TITLE', 'DVANUM', 'MAPREF', 'PAIDBY',
            'STREET', 'COMMENT', 'PROFILE', 'SPECIAL', 'SUPPORT',
            'SURNAME', 'DLNUMBER', 'EXITDATE', 'EXITFLAG', 'POSTCODE',
            'PREFNAME', 'PRIORITY', 'UNIQUEID', 'ENTRYDATE', 'GIVENNAME',
            'NEWSLCODE', 'CLIENTNAME', 'FUNDSOURCE', 'LASTASSESS',
            'PENSIONNUM', 'UPDATEFLAG', 'WHEELCHAIR', 'ACCOUNTCODE',
            'CLIENTCLASS', 'DATEOFBIRTH', 'SENDACCOUNT', 'SILENTPHONE',
            '"CLIENT EMAIL"', 'HOMELANGUAGE', 'SPECIALNEEDS',
            'COUNTRYOFBIRTH', 'REFERRALSOURCE', 'ACCOMMODATIONTYPE',
            '"CLIENT WORK PHONE"', '"INDIGENOUS STATUS"',
            '"LINKED CARER NAME"', 'LIVINGARRANGMENTS',
            '"CLIENT MOBILE PHONE"',
            '"LAST VERIFIED TRIP DATE"',
            '"LINKED CARER ACCOUNT CODE"',
            '"CONSENT TO PROVIDE DETAILS"',
            '"CONSENT FOR FUTURE CONTACTS"',
            '"INTERESTED IN SHARING STORY"',
            '_AB_SOURCE_FILE_URL',
            '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META,
    _AIRBYTE_GENERATION_ID,
    AGE, LGA, SEX, TOWN, ZONE, HOIST, PHONE, STATE, SYSID, TITLE,
    DVANUM, MAPREF, PAIDBY, STREET, COMMENT, PROFILE, SPECIAL, SUPPORT,
    SURNAME, DLNUMBER, EXITDATE, EXITFLAG, POSTCODE, PREFNAME, PRIORITY,
    UNIQUEID, ENTRYDATE, GIVENNAME, NEWSLCODE, CLIENTNAME, FUNDSOURCE,
    LASTASSESS, PENSIONNUM, UPDATEFLAG, WHEELCHAIR, ACCOUNTCODE,
    CLIENTCLASS, DATEOFBIRTH, SENDACCOUNT, SILENTPHONE,
    "CLIENT EMAIL", HOMELANGUAGE, SPECIALNEEDS, COUNTRYOFBIRTH,
    REFERRALSOURCE, ACCOMMODATIONTYPE, "CLIENT WORK PHONE",
    "INDIGENOUS STATUS", "LINKED CARER NAME", LIVINGARRANGMENTS,
    "CLIENT MOBILE PHONE", _AB_SOURCE_FILE_URL,
    "LAST VERIFIED TRIP DATE", "LINKED CARER ACCOUNT CODE",
    "CONSENT TO PROVIDE DETAILS", "CONSENT FOR FUTURE CONTACTS",
    "INTERESTED IN SHARING STORY", _AB_SOURCE_FILE_LAST_MODIFIED,
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_trips', 'TRIPS_CLIENTS') }}

{% endsnapshot %}