SELECT 'E_TOOLS'        AS SRC_SYS, 
       'CUSTOMER_LIST'  AS TABLE_NAME, 
       CARE_REC_ID, 
       FIRST_NAME, 
       LAST_NAME, 
       DATE_OF_BIRTH

FROM {{ source('raw_e_tools', 'CUSTOMER_LIST') }}

WHERE CARE_REC_ID IS NULL
   OR FIRST_NAME IS NULL
   OR LAST_NAME IS NULL
   OR DATE_OF_BIRTH IS NULL
