SELECT 'ECHIDNA'            AS SRC_SYS, 
       'ECHIDNA_CLIENTS'    AS TABLE_NAME, 
       CLIENT_FIRST_NAME, 
       CLIENT_SURNAME, 
       DATE_OF_BIRTH, 
       ADDRESS, 
       SUBURB, 
       POSTCODE

FROM {{ source('raw_echidna', 'ECHIDNA_CLIENTS') }}

WHERE CLIENT_FIRST_NAME IS NULL
OR CLIENT_SURNAME IS NULL
OR DATE_OF_BIRTH IS NULL
OR ADDRESS IS NULL
OR SUBURB IS NULL
OR POSTCODE IS NULL
