SELECT
    'TRAKCARE'                    AS SRC_SYS,
    'PA_PERSON/PA_PATMAS/CT_ZIP'  AS TABLE_NAME,
    PAT.PAPMI_NO,
    PAT.PAPMI_NAME2,
    PAT.PAPMI_NAME,
    PER.PAPER_NAME2,
    PER.PAPER_NAME,
    PAT.PAPMI_DOB,
    PER.PAPER_DOB,
    PER.PAPER_STNAME,
    ZIP.CTZIP_CITYDESC,
    ZIP.CTZIP_DESC,
    ZIP.CTZIP_CODE

FROM {{ source('raw_trakcare', 'PA_PERSON') }} PER

LEFT JOIN {{ source('raw_trakcare', 'PA_PATMAS') }} PAT
    ON PAT.PAPMI_PAPER_DR = PER.PAPER_ROWID

LEFT JOIN {{ source('raw_trakcare', 'CT_ZIP') }} ZIP
    ON CAST(PER.PAPER_ZIP_DR AS NUMBER(18,0)) = CAST(ZIP.CTZIP_ROWID AS NUMBER(18,0))

WHERE PAT.PAPMI_NO IS NOT NULL -- 107276
AND (   PAT.PAPMI_NAME2 IS NULL
     OR PAT.PAPMI_NAME IS NULL   
     OR PER.PAPER_NAME2 IS NULL    
     OR PER.PAPER_NAME IS NULL
     OR PAT.PAPMI_DOB IS NULL
     OR PER.PAPER_DOB IS NULL
     OR PER.PAPER_STNAME IS NULL
     OR ZIP.CTZIP_CITYDESC IS NULL 
     OR ZIP.CTZIP_DESC IS NULL 
     OR ZIP.CTZIP_CODE IS NULL
    )