SELECT 'TRIPS'          AS SRC_SYS, 
       'TRIPS_CLIENTS'  AS TABLE_NAME, 
       UNIQUEID, 
       GIVENNAME, 
       SURNAME, 
       DATEOFBIRTH, 
       STREET, 
       TOWN, 
       POSTCODE

FROM {{ source('raw_trips', 'TRIPS_CLIENTS') }}

WHERE UNIQUEID IS NULL 
   OR UNIQUEID LIKE '%+%'
   OR COALESCE(GIVENNAME,PREFNAME) IS NULL
   OR SURNAME IS NULL 
   OR SURNAME LIKE '%AAA%'
   OR DATEOFBIRTH IS NULL 
   OR DATEOFBIRTH LIKE '%+%'
   OR STREET IS NULL 
   OR STREET = ','
   OR TOWN IS NULL
   OR POSTCODE IS NULL 
   OR POSTCODE = 0