SELECT
    ID                                                                    AS VADC_OUT_ID,

    -- Links to other tables
    QUESPAADMDR                                                           AS ADM_DR,
    QUESPAPATMASDR                                                        AS PATIENT_DR,
    QUESSSUSERDEFWINDOWDR                                                 AS USER_DEF_WINDOW_DR,
    QUESUSERDR                                                            AS USER_DR,
    NULLIF(TRIM(QUESOEORDEXECDR), 'NULL')                                 AS OE_ORD_EXEC_DR,
    NULLIF(TRIM(QUESMRCLINICALPATHWAYSDR), 'NULL')                        AS MR_CLINICAL_PATHWAYS_DR,
    QUESSTATUSDR                                                          AS STATUS_DR,
    QUESTEXTRESULTDR                                                      AS TEXT_RESULT_DR,
    NULLIF(TRIM(QUESCONSULTDR), 'NULL')                                   AS CONSULT_DR,
    QUESOPERROOMDR                                                        AS OPER_ROOM_DR,
    QUESFHRESIDENTDR                                                      AS FH_RESIDENT_DR,
    NULLIF(TRIM(QUESPATHWAYITEMDR), 'NULL')                               AS PATHWAY_ITEM_DR,
    QUESPAWAITINGLISTDR                                                   AS WAITING_LIST_DR,
    QUESCOPIEDEPDR                                                        AS COPIED_EP_DR,
    QUESCOPIEDUSERDR                                                      AS COPIED_USER_DR,
    QUESREASONFORCORRECTIONDR                                             AS REASON_FOR_CORRECTION_DR,
    QUESERRORREASONDR                                                     AS ERROR_REASON_DR,
    NULLIF(TRIM(QUESNRCAREPLANISSUESDR), 'NULL')                          AS NR_CARE_PLAN_ISSUES_DR,
    NULLIF(TRIM(QUESRBAPPOINTMENTDR), 'NULL')                             AS RB_APPOINTMENT_DR,
    NULLIF(TRIM(QUESANADR), 'NULL')                                       AS ANA_DR,
    NULLIF(TRIM(QUESANAOPERATIONDR), 'NULL')                              AS ANA_OPERATION_DR,
    QUESCOPIEDSOURCEDR                                                    AS COPIED_SOURCE_DR,
    NULLIF(TRIM(QUESTRANSACTIONDR), 'NULL')                               AS TRANSACTION_DR,
    NULLIF(TRIM(QUESOBSENTRYDR), 'NULL')                                  AS OBS_ENTRY_DR,
    QUESPAPREGNANCYDR                                                     AS PREGNANCY_DR,
    NULLIF(TRIM(QUESPREPOSTEXAMOEORDITEMDR), 'NULL')                      AS PRE_POST_EXAM_OE_ORD_ITEM_DR,
    QUESORPREANAESTHETICCONSULTDR                                         AS OR_PRE_ANAESTHETIC_CONSULT_DR,
    NULLIF(TRIM(QUESRBAPPTOUTCOMEDR), 'NULL')                             AS RB_APPT_OUTCOME_DR,
    NULLIF(TRIM(QUESRBAPPTSLOTDR), 'NULL')                                AS RB_APPT_SLOT_DR,
    QUESSECONDUSERDR                                                      AS SECOND_USER_DR,
    NULLIF(TRIM(QUESPAADVERSEEVENTDR), 'NULL')                            AS ADVERSE_EVENT_DR,

    -- Date/time columns (typed)
    QUESDATE                                                              AS QUES_DATE,
    QUESTIME                                                              AS QUES_TIME,
    QVADCOUTDATE                                                          AS VADC_OUT_DATE,
    QUESCOPIEDDATE                                                        AS COPIED_DATE,
    QUESCOPIEDTIME                                                        AS COPIED_TIME,
    QUESCREATEDATE                                                        AS CREATED_DATE,
    QUESCREATETIME                                                        AS CREATED_TIME,
    QUESCREATEUSERDR                                                      AS CREATED_USER_DR,

    -- Score
    NULLIF(TRIM(QUESSCORE), 'NULL')                                       AS SCORE,

    -- VADC outcome fields
    NULLIF(TRIM(QVADCOUTK10), 'NULL')                                     AS VADC_OUT_K10,
    NULLIF(TRIM(QVADCOUTEMPL), 'NULL')                                    AS VADC_OUT_EMPL,
    NULLIF(TRIM(QVADCOUTACCOM), 'NULL')                                   AS VADC_OUT_ACCOM,
    NULLIF(TRIM(QVADCOUTAUDIT), 'NULL')                                   AS VADC_OUT_AUDIT,
    NULLIF(TRIM(QVADCOUTDUDIT), 'NULL')                                   AS VADC_OUT_DUDIT,
    NULLIF(TRIM(QVADCOUTSTUDY), 'NULL')                                   AS VADC_OUT_STUDY,
    NULLIF(TRIM(QVADCOUTARREST), 'NULL')                                  AS VADC_OUT_ARREST,
    NULLIF(TRIM(QVADCOUTINJDAYS), 'NULL')                                 AS VADC_OUT_INJ_DAYS,
    NULLIF(TRIM(QVADCOUTQTYLIFE), 'NULL')                                 AS VADC_OUT_QTY_LIFE,
    NULLIF(TRIM(QVADCOUTRISKOTH), 'NULL')                                 AS VADC_OUT_RISK_OTH,
    NULLIF(TRIM(QVADCOUTVIOLENT), 'NULL')                                 AS VADC_OUT_VIOLENT,
    NULLIF(TRIM(QVADCOUTARREST14), 'NULL')                                AS VADC_OUT_ARREST_14,
    NULLIF(TRIM(QVADCOUTK10OBSDR), 'NULL')                                AS VADC_OUT_K10_OBS_DR,
    NULLIF(TRIM(QVADCOUTPHYSHLTH), 'NULL')                                AS VADC_OUT_PHYS_HLTH,
    NULLIF(TRIM(QVADCOUTRISKSELF), 'NULL')                                AS VADC_OUT_RISK_SELF,
    NULLIF(TRIM(QVADCOUTEMPLOBSDR), 'NULL')                               AS VADC_OUT_EMPL_OBS_DR,
    NULLIF(TRIM(QVADCOUTPSYCHHLTH), 'NULL')                               AS VADC_OUT_PSYCH_HLTH,
    NULLIF(TRIM(QVADCOUTQTYLIFE14), 'NULL')                               AS VADC_OUT_QTY_LIFE_14,
    NULLIF(TRIM(QVADCOUTRISKOTH14), 'NULL')                               AS VADC_OUT_RISK_OTH_14,
    NULLIF(TRIM(QVADCOUTVIOLENT14), 'NULL')                               AS VADC_OUT_VIOLENT_14,
    NULLIF(TRIM(QVADCOUTVIOLENTV2), 'NULL')                               AS VADC_OUT_VIOLENT_V2,
    NULLIF(TRIM(QVADCOUTACCOMOBSDR), 'NULL')                              AS VADC_OUT_ACCOM_OBS_DR,
    NULLIF(TRIM(QVADCOUTAUDITOBSDR), 'NULL')                              AS VADC_OUT_AUDIT_OBS_DR,
    NULLIF(TRIM(QVADCOUTDUDITOBSDR), 'NULL')                              AS VADC_OUT_DUDIT_OBS_DR,
    NULLIF(TRIM(QVADCOUTPHYSHLTH14), 'NULL')                              AS VADC_OUT_PHYS_HLTH_14,
    NULLIF(TRIM(QVADCOUTRISKSELF14), 'NULL')                              AS VADC_OUT_RISK_SELF_14,
    NULLIF(TRIM(QVADCOUTSTUDYOBSDR), 'NULL')                              AS VADC_OUT_STUDY_OBS_DR,
    NULLIF(TRIM(QVADCOUTARRESTOBSDR), 'NULL')                             AS VADC_OUT_ARREST_OBS_DR,
    NULLIF(TRIM(QVADCOUTPSYCHHLTH14), 'NULL')                             AS VADC_OUT_PSYCH_HLTH_14,
    NULLIF(TRIM(QVADCOUTINJDAYSOBSDR), 'NULL')                            AS VADC_OUT_INJ_DAYS_OBS_DR,
    NULLIF(TRIM(QVADCOUTQTYLIFEOBSDR), 'NULL')                            AS VADC_OUT_QTY_LIFE_OBS_DR,
    NULLIF(TRIM(QVADCOUTRISKOTHOBSDR), 'NULL')                            AS VADC_OUT_RISK_OTH_OBS_DR,
    NULLIF(TRIM(QVADCOUTVIOLENTOBSDR), 'NULL')                            AS VADC_OUT_VIOLENT_OBS_DR,
    NULLIF(TRIM(QVADCOUTPHYSHLTHOBSDR), 'NULL')                           AS VADC_OUT_PHYS_HLTH_OBS_DR,
    NULLIF(TRIM(QVADCOUTRISKSELFOBSDR), 'NULL')                           AS VADC_OUT_RISK_SELF_OBS_DR,
    NULLIF(TRIM(QVADCOUTPSYCHHLTHOBSDR), 'NULL')                          AS VADC_OUT_PSYCH_HLTH_OBS_DR,
    NULLIF(TRIM(QVADCOUTVIOLENTV2OBSDR), 'NULL')                          AS VADC_OUT_VIOLENT_V2_OBS_DR,

    -- Audit trail
    NULLIF(TRIM(QUESCOPIEDCOMMENTS), 'NULL')                              AS COPIED_COMMENTS,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_QAUXXADOUT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')