SELECT
    CTPCP_ROWID                                                           AS ROW_ID,
    CTPCP_ROWID1                                                          AS ROW_ID_1,
    NULLIF(TRIM(CTPCP_CODE), 'NULL')                                      AS CODE,
    NULLIF(TRIM(CTPCP_DESC), 'NULL')                                      AS DESCRIPTION,
    NULLIF(TRIM(CTPCP_ID), 'NULL')                                        AS ID,
    NULLIF(TRIM(CTPCP_CATEGORY), 'NULL')                                  AS CATEGORY,
    NULLIF(TRIM(CTPCP_SMCNO), 'NULL')                                     AS SMC_NO,
    CTPCP_CARPRVTP_DR                                                     AS CAR_PRVTP_DR,
    NULLIF(TRIM(CTPCP_ADDRTYPE_DR), 'NULL')                               AS ADDR_TYPE_DR,
    NULLIF(TRIM(CTPCP_BLK), 'NULL')                                       AS BLK,
    NULLIF(TRIM(CTPCP_STNAME), 'NULL')                                    AS ST_NAME,
    NULLIF(TRIM(CTPCP_LEVEL), 'NULL')                                     AS LEVEL,
    NULLIF(TRIM(CTPCP_UNIT), 'NULL')                                      AS UNIT,
    NULLIF(TRIM(CTPCP_CITY_DR), 'NULL')                                   AS CITY_DR,
    NULLIF(TRIM(CTPCP_STATE_DR), 'NULL')                                  AS STATE_DR,
    NULLIF(TRIM(CTPCP_ZIP_DR), 'NULL')                                    AS ZIP_DR,
    NULLIF(TRIM(CTPCP_SPEC_DR), 'NULL')                                   AS SPEC_DR,
    NULLIF(TRIM(CTPCP_SUBSPEC_DR), 'NULL')                                AS SUB_SPEC_DR,
    NULLIF(TRIM(CTPCP_TELO), 'NULL')                                      AS TELO,
    NULLIF(TRIM(CTPCP_TELOEXT), 'NULL')                                   AS TELO_EXT,
    NULLIF(TRIM(CTPCP_TELH), 'NULL')                                      AS TEL_H,
    NULLIF(TRIM(CTPCP_PAGERNO), 'NULL')                                   AS PAGER_NO,
    NULLIF(TRIM(CTPCP_HOSP_DR), 'NULL')                                   AS HOSP_DR,
    NULLIF(TRIM(CTPCP_CON1CODE_DR), 'NULL')                               AS CON1_CODE_DR,
    NULLIF(TRIM(CTPCP_CON2CODE_DR), 'NULL')                               AS CON2_CODE_DR,
    CTPCP_ACTIVEFLAG                                                      AS ACTIVE_FLAG,
    NULLIF(TRIM(CTPCP_VERSIONORIGIN_DR), 'NULL')                          AS VERSION_ORIGIN_DR,
    CTPCP_VERSIONNUMBER                                                   AS VERSION_NO,
    CTPCP_VERSIONDATE                                                     AS VERSION_DATE,
    CTPCP_VERSIONTIME                                                     AS VERSION_TIME,
    NULLIF(TRIM(CTPCP_VERSIONDATETIME), 'NULL')                           AS VERSION_DATE_TIME,
    NULLIF(TRIM(CTPCP_AUTHORID), 'NULL')                                  AS AUTHOR_ID,
    NULLIF(TRIM(CTPCP_SPECIALISTYN), 'NULL')                              AS SPECIALIST_YN,
    NULLIF(TRIM(CTPCP_FIRSTDIGITINQUEUE), 'NULL')                         AS FIRST_DIGIT_IN_QUEUE,
    CTPCP_DATEACTIVEFROM                                                  AS DATE_ACTIVE_FROM,
    NULLIF(TRIM(CTPCP_DATEACTIVETO), 'NULL')                              AS DATE_ACTIVE_TO,
    NULLIF(TRIM(CTPCP_LINKDOCTOR_DR), 'NULL')                             AS LINK_DOCTOR_DR,
    NULLIF(TRIM(CTPCP_ALLOCATEDDOCTOR), 'NULL')                           AS ALLOCATED_DOCTOR,
    NULLIF(TRIM(CTPCP_SURGEON), 'NULL')                                   AS SURGEON,
    NULLIF(TRIM(CTPCP_ANAESTHETIST), 'NULL')                              AS ANAESTHETIST,
    NULLIF(TRIM(CTPCP_PRESCRIBERNUMBER), 'NULL')                          AS PRESCRIBER_NO,
    NULLIF(TRIM(CTPCP_CPGROUP_DR), 'NULL')                                AS CP_GROUP_DR,
    NULLIF(TRIM(CTPCP_RESPUNIT_DR), 'NULL')                               AS RESP_UNIT_DR,
    NULLIF(TRIM(CTPCP_CTLOC_DR), 'NULL')                                  AS CT_LOC_DR,
    NULLIF(TRIM(CTPCP_TITLE), 'NULL')                                     AS TITLE,
    TRY_TO_DATE(NULLIF(TRIM(CTPCP_DOB), 'NULL'))                          AS DOB,
    NULLIF(TRIM(CTPCP_MOBILEPHONE), 'NULL')                               AS MOBILE_PHONE,
    NULLIF(TRIM(CTPCP_FAX), 'NULL')                                       AS FAX,
    NULLIF(TRIM(CTPCP_MAILLIST), 'NULL')                                  AS MAIL_LIST,
    LOWER(NULLIF(TRIM(CTPCP_EMAIL), 'NULL'))                              AS EMAIL,
    NULLIF(TRIM(CTPCP_PREFCONMETHOD), 'NULL')                             AS PREF_CON_METHOD,
    NULLIF(TRIM(CTPCP_TEXTONE), 'NULL')                                   AS TEXT_ONE,
    NULLIF(TRIM(CTPCP_TEXTTWO), 'NULL')                                   AS TEXT_TWO,
    NULLIF(TRIM(CTPCP_CONTACTFIRSTON), 'NULL')                            AS CONTACT_FIRST_ON,
    NULLIF(TRIM(CTPCP_RADIOLOGIST), 'NULL')                               AS RADIOLOGIST,
    NULLIF(TRIM(CTPCP_ADMITTINGRIGHTS), 'NULL')                           AS ADMITTING_RIGHTS,
    NULLIF(TRIM(CTPCP_ACCEPTANCE), 'NULL')                                AS ACCEPTANCE,
    NULLIF(TRIM(CTPCP_PREVIOUS), 'NULL')                                  AS PREVIOUS,
    NULLIF(TRIM(CTPCP_MANTOUXTEST), 'NULL')                               AS MANTOUX_TEST,
    NULLIF(TRIM(CTPCP_CONTINUING), 'NULL')                                AS CONTINUING,
    NULLIF(TRIM(CTPCP_NEW), 'NULL')                                       AS NEW,
    NULLIF(TRIM(CTPCP_PREFMAILADDFLAD), 'NULL')                           AS PREF_MAIL_ADD_FLAG,
    TRY_TO_DATE(NULLIF(TRIM(CTPCP_UPDATEDATE), 'NULL'))                   AS UPDATE_DATE,
    NULLIF(TRIM(CTPCP_UPDATETIME), 'NULL')                                AS UPDATE_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(CTPCP_UPDATEUSER_DR), 'NULL'), 18, 6)       AS UPDATE_USER_DR,
    NULLIF(TRIM(CTPCP_BESTCONTACTTIME), 'NULL')                           AS BEST_CONTACT_TIME,
    NULLIF(TRIM(CTPCP_REFERRALDOCTOR_DR), 'NULL')                         AS REFERRAL_DOCTOR_DR,
    NULLIF(TRIM(CTPCP_FIRSTNAME), 'NULL')                                 AS FIRST_NAME,
    NULLIF(TRIM(CTPCP_OTHERNAME), 'NULL')                                 AS OTHER_NAME,
    NULLIF(TRIM(CTPCP_TITLE_DR), 'NULL')                                  AS TITLE_DR,
    NULLIF(TRIM(CTPCP_SURNAME), 'NULL')                                   AS LAST_NAME,
    NULLIF(TRIM(CTPCP_HICAPPROVED), 'NULL')                               AS HIC_APPROVED,
    NULLIF(TRIM(CTPCP_PRACTITIONERFLAG1), 'NULL')                         AS PRACTITIONER_FLAG_1,
    TRY_TO_NUMBER(NULLIF(TRIM(CTPCP_CREATEDUSER_DR), 'NULL'), 18, 6)      AS CREATED_USER_DR,
    TRY_TO_DATE(NULLIF(TRIM(CTPCP_CREATEDDATE), 'NULL'))                  AS CREATED_DATE,
    NULLIF(TRIM(CTPCP_CREATEDTIME), 'NULL')                               AS CREATED_TIME,
    NULLIF(TRIM(CTPCP_CREATEDHOSP_DR), 'NULL')                            AS CREATED_HOSP_DR,
    NULLIF(TRIM(CTPCP_UPDATEHOSP_DR), 'NULL')                             AS UPDATE_HOSP_DR,
    NULLIF(TRIM(CTPCP_TEXTTHREE), 'NULL')                                 AS TEXT_THREE,
    NULLIF(TRIM(CTPCP_TEXTTITLE), 'NULL')                                 AS TEXT_TITLE,
    NULLIF(TRIM(CTPCP_DOCTORSREPORTSTYPE), 'NULL')                        AS DOCTORS_REPORTS_TYPE,
    NULLIF(TRIM(CTPCP_QUICKPRINT), 'NULL')                                AS QUICK_PRINT,
    NULLIF(TRIM(CTPCP_COURIER_DR), 'NULL')                                AS COURIER_DR,
    NULLIF(TRIM(CTPCP_COURIERCOPIES), 'NULL')                             AS COURIER_COPIES,
    NULLIF(TRIM(CTPCP_DOCTORSREPORTSTO), 'NULL')                          AS DOCTORS_REPORTS_TO,
    NULLIF(TRIM(CTPCP_DOCTORSREPORTSDELIVERYSORT), 'NULL')                AS DOCTORS_REPORTS_DELIVERY_SORT,
    NULLIF(TRIM(CTPCP_SPECSTPALLIATIVECP), 'NULL')                        AS SPEC_ST_PALLIATIVE_CP,
    NULLIF(TRIM(CTPCP_CUMULATIVEPREFERENCE), 'NULL')                      AS CUMULATIVE_PREFERENCE,
    NULLIF(TRIM(CTPCP_CUMULATIVEORDER), 'NULL')                           AS CUMULATIVE_ORDER,
    NULLIF(TRIM(CTPCP_CUMULATIVEEPISODES), 'NULL')                        AS CUMULATIVE_EPISODES,
    NULLIF(TRIM(CTPCP_LANGUAGE_DR), 'NULL')                               AS LANGUAGE_DR,
    NULLIF(TRIM(CTPCP_WLOUTPATIENTRIGHTS), 'NULL')                        AS WL_OUTPATIENT_RIGHTS,
    NULLIF(TRIM(CTPCP_WLTRIAGERIGHTS), 'NULL')                            AS WL_TRIAGE_RIGHTS,
    NULLIF(TRIM(CTPCP_REGISSUER), 'NULL')                                 AS REG_ISSUER,
    NULLIF(TRIM(CTPCP_MANUALPRINT), 'NULL')                               AS MANUAL_PRINT,
    NULLIF(TRIM(CTPCP_OTCONSULTANT), 'NULL')                              AS OT_CONSULTANT,
    NULLIF(TRIM(CTPCP_EXTERNALINTERFACEQUEUE_DR), 'NULL')                 AS EXTERNAL_INTERFACE_QUEUE_DR,
    NULLIF(TRIM(CTPCP_REPORTMODE), 'NULL')                                AS REPORT_MODE,
    TRY_TO_DATE(NULLIF(TRIM(CTPCP_UPDATEDDATE), 'NULL'))                  AS UPDATED_DATE,
    NULLIF(TRIM(CTPCP_UPDATEDTIME), 'NULL')                               AS UPDATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(CTPCP_UPDATEDUSER_DR), 'NULL'), 18, 6)      AS UPDATED_USER_DR,
    NULLIF(TRIM(CTPCP_PATHOLOGYSELFDETERMINE), 'NULL')                    AS PATHOLOGY_SELF_DETERMINE,
    NULLIF(TRIM(CTPCP_SECONDARYPRESCRIBERNUMBER), 'NULL')                 AS SECONDARY_PRESCRIBER_NO,
    NULLIF(TRIM(CTPCP_PROVINCE_DR), 'NULL')                               AS PROVINCE_DR,
    NULLIF(TRIM(CTPCP_REGION_DR), 'NULL')                                 AS REGION_DR,
    NULLIF(TRIM(CTPCP_CONFIDENTIALFAX), 'NULL')                           AS CONFIDENTIAL_FAX,
    NULLIF(TRIM(CTPCP_CPGROUPAFFILIATIONS), 'NULL')                       AS CP_GROUP_AFFILIATIONS,
    NULLIF(TRIM(CTPCP_EXTERNALCAREPROV), 'NULL')                          AS EXTERNAL_CARE_PROV,
    NULLIF(TRIM(CTPCP_PBSPROVIDERTYPE), 'NULL')                           AS PBS_PROVIDER_TYPE,
    NULLIF(TRIM(CTPCP_YESNO1), 'NULL')                                    AS YES_NO_1,
    NULLIF(TRIM(CTPCP_YESNO2), 'NULL')                                    AS YES_NO_2,
    NULLIF(TRIM(CTPCP_YESNO3), 'NULL')                                    AS YES_NO_3,
    NULLIF(TRIM(CTPCP_YESNO4), 'NULL')                                    AS YES_NO_4,
    NULLIF(TRIM(CTPCP_SEX_DR), 'NULL')                                    AS SEX_DR,
    NULLIF(TRIM(CTPCP_PREFLANGUAGE_DR), 'NULL')                           AS PREF_LANGUAGE_DR,
    NULLIF(TRIM(CTPCP_OTHERLANGUAGE_DR), 'NULL')                          AS OTHER_LANGUAGE_DR,
    NULLIF(TRIM(CTPCP_NATION_DR), 'NULL')                                 AS NATION_DR,
    NULLIF(TRIM(CTPCP_TEXTFIELD), 'NULL')                                 AS TEXT_FIELD,
    NULLIF(TRIM(CTPCP_DEACTIVATIONREASON), 'NULL')                        AS DEACTIVATION_REASON,
    NULLIF(TRIM(CTPCP_CODETRANSLATED), 'NULL')                            AS CODE_TRANSLATED,
    NULLIF(TRIM(CTPCP_DESCTRANSLATED), 'NULL')                            AS DESC_TRANSLATED

FROM {{ ref('HIST_TRAKCARE_CT_CAREPROV') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')