SELECT
    NULLIF(TRIM(AS_ROWID), 'NULL')                                        AS ROW_ID,
    AS_RES_PARREF                                                         AS RES_PAR_REF,
    AS_CHILDSUB                                                           AS CHILD_SUB,
    AS_DATE                                                               AS SESSION_DATE,
    AS_SESSION                                                            AS SESSION,
    AS_SESSSTARTTIME                                                      AS SESSION_START_TIME,
    AS_SESSENDTIME                                                        AS SESSION_END_TIME,
    AS_NOAPPTSESSION                                                      AS NO_APPT_SESSION,
    AS_LOAD                                                               AS LOAD,
    AS_AVAILABILITY                                                       AS AVAILABILITY,
    AS_NUMPATIN                                                           AS NUM_PAT_IN,
    AS_NUMPATOUT                                                          AS NUM_PAT_OUT,
    NULLIF(TRIM(AS_REMARKS), 'NULL')                                      AS REMARKS,
    NULLIF(TRIM(AS_SLOT), 'NULL')                                         AS SLOT,
    NULLIF(TRIM(AS_QUEUENOCOUNT), 'NULL')                                 AS QUEUE_NO_COUNT,
    NULLIF(TRIM(AS_BOOKEDSLOTS), 'NULL')                                  AS BOOKED_SLOTS,
    NULLIF(TRIM(AS_RBEFFDATESESSION_DR), 'NULL')                          AS RB_EFF_DATE_SESSION_DR,
    NULLIF(TRIM(AS_IRREGULARFLAG), 'NULL')                                AS IRREGULAR_FLAG,
    NULLIF(TRIM(AS_SESSIONTYPE_DR), 'NULL')                               AS SESSION_TYPE_DR,
    NULLIF(TRIM(AS_ACTUALDATE), 'NULL')                                   AS ACTUAL_DATE,
    NULLIF(TRIM(AS_ACTUALSTARTTIME), 'NULL')                              AS ACTUAL_START_TIME,
    NULLIF(TRIM(AS_ACTUALENDTIME), 'NULL')                                AS ACTUAL_END_TIME,
    NULLIF(TRIM(AS_REASONFORDELAY_DR), 'NULL')                            AS REASON_FOR_DELAY_DR,
    NULLIF(TRIM(AS_REASONFOROVERTIME_DR), 'NULL')                         AS REASON_FOR_OVERTIME_DR,
    NULLIF(TRIM(AS_GENERATIONDATE), 'NULL')                               AS GENERATION_DATE,
    NULLIF(TRIM(AS_GENERATIONTIME), 'NULL')                               AS GENERATION_TIME,
    NULLIF(TRIM(AS_LASTUPDATEUSER_DR), 'NULL')                            AS LAST_UPDATE_USER_DR,
    NULLIF(TRIM(AS_LASTUPDATEDATE), 'NULL')                               AS LAST_UPDATE_DATE,
    NULLIF(TRIM(AS_LASTUPDATETIME), 'NULL')                               AS LAST_UPDATE_TIME,
    NULLIF(TRIM(AS_NOTAVAILABLESLOT), 'NULL')                             AS NOT_AVAILABLE_SLOT,
    NULLIF(TRIM(AS_OPDROOM_DR), 'NULL')                                   AS OPD_ROOM_DR,
    NULLIF(TRIM(AS_DAYCLINICOPTIONS), 'NULL')                             AS DAY_CLINIC_OPTIONS,
    NULLIF(TRIM(AS_WEBGENERATED), 'NULL')                                 AS WEB_GENERATED,
    NULLIF(TRIM(AS_APPTLOC_DR), 'NULL')                                   AS APPT_LOC_DR,
    NULLIF(TRIM(AS_EMERGENCYTHEATRE), 'NULL')                             AS EMERGENCY_THEATRE,
    NULLIF(TRIM(AS_OPERBOOKINGMETHOD), 'NULL')                            AS OPER_BOOKING_METHOD,
    NULLIF(TRIM(AS_NOMOREBOOKINGS), 'NULL')                               AS NO_MORE_BOOKINGS,
    NULLIF(TRIM(AS_ORIGSESSSTARTTIME), 'NULL')                            AS ORIG_SESS_START_TIME,
    NULLIF(TRIM(AS_ORIGSESSENDTIME), 'NULL')                              AS ORIG_SESS_END_TIME,
    NULLIF(TRIM(AS_APPTLOCALL), 'NULL')                                   AS APPT_LOC_ALL,
    NULLIF(TRIM(AS_AUTOREQ), 'NULL')                                      AS AUTO_REQ,
    NULLIF(TRIM(AS_OTSESSORIGINFLAG), 'NULL')                             AS OT_SESS_ORIGIN_FLAG,
    NULLIF(TRIM(AS_BRIEFNOTREQUIRED), 'NULL')                             AS BRIEF_NOT_REQUIRED,
    NULLIF(TRIM(AS_DONTREINSTATEFLAG), 'NULL')                            AS DONT_REINSTATE_FLAG,
    NULLIF(TRIM(AS_OTROOMSTATUS), 'NULL')                                 AS OT_ROOM_STATUS,
    NULLIF(TRIM(AS_REASONBRIEFNOTREQUIRED), 'NULL')                       AS REASON_BRIEF_NOT_REQUIRED

FROM {{ ref('HIST_TRAKCARE_RB_APPTSCHEDULE') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')