SELECT
    EV_ROWID                                                              AS ROW_ID,
    NULLIF(TRIM(EV_NUMBER), 'NULL')                                       AS NUMBER,
    NULLIF(TRIM(EV_STATUS), 'NULL')                                       AS STATUS,
    NULLIF(TRIM(EV_NAME), 'NULL')                                         AS NAME,
    NULLIF(TRIM(EV_TYPE_DR), 'NULL')                                      AS TYPE_DR,
    NULLIF(TRIM(EV_CLIENTTYPE), 'NULL')                                   AS CLIENT_TYPE,
    NULLIF(TRIM(EV_METHODOFCONDUCT_DR), 'NULL')                           AS METHOD_OF_CONDUCT_DR,
    NULLIF(TRIM(EV_ADMINISTRATOR_DR), 'NULL')                             AS ADMINISTRATOR_DR,
    EV_DURATION                                                           AS DURATION,
    NULLIF(TRIM(EV_VENUE), 'NULL')                                        AS VENUE,
    NULLIF(TRIM(EV_MAXNUMBEROFPARTICIPANTS), 'NULL')                      AS MAX_NO_OF_PARTICIPANTS,
    NULLIF(TRIM(EV_CHARGE), 'NULL')                                       AS CHARGE,
    NULLIF(TRIM(EV_PREPARATIONTIME), 'NULL')                              AS PREPARATION_TIME,
    NULLIF(TRIM(EV_PREDICTEDTRAVELTIME), 'NULL')                          AS PREDICTED_TRAVEL_TIME,
    NULLIF(TRIM(EV_PREDICTEDREVIEWTIME), 'NULL')                          AS PREDICTED_REVIEW_TIME,
    EV_RBRESOURCE_DR                                                      AS RB_RESOURCE_DR,
    NULLIF(TRIM(EV_VENUEADDRESS1), 'NULL')                                AS VENUE_ADDRESS_1,
    NULLIF(TRIM(EV_VENUEADDRESS2), 'NULL')                                AS VENUE_ADDRESS_2,
    NULLIF(TRIM(EV_VENUEPHONE), 'NULL')                                   AS VENUE_PHONE,
    NULLIF(TRIM(EV_VENUEFAX), 'NULL')                                     AS VENUE_FAX,
    NULLIF(TRIM(EV_CONSULTCATEGORY_DR), 'NULL')                           AS CONSULT_CATEGORY_DR,
    NULLIF(TRIM(EV_CLIENTSOURCE_DR), 'NULL')                              AS CLIENT_SOURCE_DR,
    NULLIF(TRIM(EV_CLIENTSOURCEDESC), 'NULL')                             AS CLIENT_SOURCE_DESC,
    NULLIF(TRIM(EV_ATTENDEEFEMALENO), 'NULL')                             AS ATTENDEE_FEMALE_NO,
    NULLIF(TRIM(EV_ATTENDEEMALENO), 'NULL')                               AS ATTENDEE_MALE_NO,
    NULLIF(TRIM(EV_EVENTSUBTYPE_DR), 'NULL')                              AS EVENT_SUB_TYPE_DR,
    NULLIF(TRIM(EV_CLIENTSOURCEORG_DR), 'NULL')                           AS CLIENT_SOURCE_ORG_DR,
    NULLIF(TRIM(EV_INSTYPE_DR), 'NULL')                                   AS INS_TYPE_DR,
    NULLIF(TRIM(EV_AUXINSTYPE_DR), 'NULL')                                AS AUX_INS_TYPE_DR,
    NULLIF(TRIM(EV_DATECREATED), 'NULL')                                  AS CREATED_DATE,
    NULLIF(TRIM(EV_LOCATION_DR), 'NULL')                                  AS LOCATION_DR,
    NULLIF(TRIM(EV_HOSPITAL_DR), 'NULL')                                  AS HOSPITAL_DR,
    NULLIF(TRIM(EV_ITEMCAT_DR), 'NULL')                                   AS ITEM_CAT_DR,
    NULLIF(TRIM(EV_CONTVENUE_DR), 'NULL')                                 AS CONT_VENUE_DR,
    NULLIF(TRIM(EV_DATEFROM), 'NULL')                                     AS DATE_FROM,
    NULLIF(TRIM(EV_DATETO), 'NULL')                                       AS DATE_TO,
    NULLIF(TRIM(EV_YESNO1), 'NULL')                                       AS YES_NO_1,
    NULLIF(TRIM(EV_YESNO2), 'NULL')                                       AS YES_NO_2,
    NULLIF(TRIM(EV_YESNO3), 'NULL')                                       AS YES_NO_3,
    NULLIF(TRIM(EV_YESNO4), 'NULL')                                       AS YES_NO_4,
    NULLIF(TRIM(EV_NFMICATEGDEPART_DR), 'NULL')                           AS NFMI_CATEG_DEPART_DR

FROM {{ ref('HIST_TRAKCARE_RB_EVENT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')