SELECT
    CTLOC_ROWID                                                           AS ROW_ID,
    NULLIF(TRIM(CTLOC_CODE), 'NULL')                                      AS CODE,
    NULLIF(TRIM(CTLOC_DESC), 'NULL')                                      AS DESCRIPTION,
    NULLIF(TRIM(CTLOC_TYPE), 'NULL')                                      AS TYPE,
    CTLOC_AGETO                                                           AS AGE_TO,
    LOWER(NULLIF(TRIM(CTLOC_EMAIL), 'NULL'))                              AS EMAIL,
    NULLIF(TRIM(CTLOC_FLOOR), 'NULL')                                     AS FLOOR,
    NULLIF(TRIM(CTLOC_INDEX), 'NULL')                                     AS INDEX,
    NULLIF(TRIM(CTLOC_OWNER), 'NULL')                                     AS OWNER,
    NULLIF(TRIM(CTLOC_FAX), 'NULL')                                       AS FAX,
    CTLOC_DEP_DR                                                          AS DEP_DR,
    CTLOC_OTC_DR                                                          AS OTC_DR,
    NULLIF(TRIM(CTLOC_PERIOD), 'NULL')                                    AS PERIOD,
    CTLOC_ZIP_DR                                                          AS ZIP_DR,
    NULLIF(TRIM(CTLOC_ADDRESS), 'NULL')                                   AS ADDRESS,
    CTLOC_AGEFROM                                                         AS AGE_FROM,
    CTLOC_CITY_DR                                                         AS CITY_DR,
    NULLIF(TRIM(CTLOC_DRGTYPE), 'NULL')                                   AS DRG_TYPE,
    CTLOC_ENDTIME                                                         AS END_TIME,
    NULLIF(TRIM(CTLOC_LAUNDRY), 'NULL')                                   AS LAUNDRY,
    NULLIF(TRIM(CTLOC_NFMI_DR), 'NULL')                                   AS NFMI_DR,
    NULLIF(TRIM(CTLOC_NOTUSED), 'NULL')                                   AS NOT_USED,
    NULLIF(TRIM(CTLOC_PAGERNO), 'NULL')                                   AS PAGER_NO,
    CTLOC_GLCCC_DR                                                        AS GL_CCC_DR,
    NULLIF(TRIM(CTLOC_SNAPFLAG), 'NULL')                                  AS SNAP_FLAG,
    NULLIF(TRIM(CTLOC_TIMEZONE), 'NULL')                                  AS TIMEZONE,
    NULLIF(TRIM(CTLOC_WARDFLAG), 'NULL')                                  AS WARD_FLAG,
    NULLIF(TRIM(CTLOC_EBOOKERID), 'NULL')                                 AS EBOOKER_ID,
    NULLIF(TRIM(CTLOC_POENABLED), 'NULL')                                 AS PO_ENABLED,
    CTLOC_REGION_DR                                                       AS REGION_DR,
    CTLOC_STARTTIME                                                       AS START_TIME,
    NULLIF(TRIM(CTLOC_TELEPHONE), 'NULL')                                 AS TELEPHONE,
    CTLOC_VISITHRTO                                                       AS VISIT_HR_TO,
    NULLIF(TRIM(CTLOC_ACTIVEFLAG), 'NULL')                                AS ACTIVE_FLAG,
    CTLOC_CASHIER_DR                                                      AS CASHIER_DR,
    CTLOC_DISPLOC_DR                                                      AS DISP_LOC_DR,
    NULLIF(TRIM(CTLOC_EBOOKINGID), 'NULL')                                AS EBOOKING_ID,
    CTLOC_JBGROUP_DR                                                      AS JB_GROUP_DR,
    NULLIF(TRIM(CTLOC_NATIONCODE), 'NULL')                                AS NATION_CODE,
    NULLIF(TRIM(CTLOC_OWNQUEFLAG), 'NULL')                                AS OWN_QUE_FLAG,
    NULLIF(TRIM(CTLOC_QUICKPRINT), 'NULL')                                AS QUICK_PRINT,
    NULLIF(TRIM(CTLOC_RECQUEFLAG), 'NULL')                                AS REC_QUE_FLAG,
    NULLIF(TRIM(CTLOC_REPORTMODE), 'NULL')                                AS REPORT_MODE,
    CTLOC_ADMQUEST_DR                                                     AS ADM_QUEST_DR,
    NULLIF(TRIM(CTLOC_CONTACTNAME), 'NULL')                               AS CONTACT_NAME,
    CTLOC_CREATEDDATE                                                     AS CREATED_DATE,
    CTLOC_CREATEDTIME                                                     AS CREATED_TIME,
    CTLOC_DISQUEST_DR                                                     AS DIS_QUEST_DR,
    CTLOC_EXTGROUP_DR                                                     AS EXT_GROUP_DR,
    CTLOC_HOSPITAL_DR                                                     AS HOSPITAL_DR,
    CTLOC_INTQUEST_DR                                                     AS INT_QUEST_DR,
    CTLOC_LANGUAGE_DR                                                     AS LANGUAGE_DR,
    NULLIF(TRIM(CTLOC_MANUALPRINT), 'NULL')                               AS MANUAL_PRINT,
    CTLOC_PROVINCE_DR                                                     AS PROVINCE_DR,
    CTLOC_RESPUNIT_DR                                                     AS RESP_UNIT_DR,
    CTLOC_UPDATEDDATE                                                     AS UPDATED_DATE,
    CTLOC_UPDATEDTIME                                                     AS UPDATED_TIME,
    CTLOC_VISITHRFROM                                                     AS VISIT_HR_FROM,
    CTLOC_DATEACTIVETO                                                    AS DATE_ACTIVE_TO,
    CTLOC_DEFADMTIMLOC                                                    AS DEF_ADM_TIM_LOC,
    NULLIF(TRIM(CTLOC_DEFREQBYTYPE), 'NULL')                              AS DEF_REQ_BY_TYPE,
    NULLIF(TRIM(CTLOC_HEALTHCENTRE), 'NULL')                              AS HEALTH_CENTRE,
    NULLIF(TRIM(CTLOC_NATAHEADINGS), 'NULL')                              AS NATA_HEADINGS,
    CTLOC_RESTPERIODTO                                                    AS REST_PERIOD_TO,
    NULLIF(TRIM(CTLOC_STOCKENABLED), 'NULL')                              AS STOCK_ENABLED,
    NULLIF(TRIM(CTLOC_TELEPHONEEXT), 'NULL')                              AS TELEPHONE_EXT,
    NULLIF(TRIM(CTLOC_CODETABLETAGS), 'NULL')                             AS CODE_TABLE_TAGS,
    NULLIF(TRIM(CTLOC_COMMUNITYUNIT), 'NULL')                             AS COMMUNITY_UNIT,
    CTLOC_DOCCOURIER_DR                                                   AS DOC_COURIER_DR,
    NULLIF(TRIM(CTLOC_FLOWSHEETNAME), 'NULL')                             AS FLOW_SHEET_NAME,
    NULLIF(TRIM(CTLOC_HL7ORDERSLINK), 'NULL')                             AS HL7_ORDERS_LINK,
    NULLIF(TRIM(CTLOC_INPATIENTUNIT), 'NULL')                             AS INPATIENT_UNIT,
    NULLIF(TRIM(CTLOC_INCLDISORDERS), 'NULL')                             AS INCL_DISORDERS,
    CTLOC_LOCCOURIER_DR                                                   AS LOC_COURIER_DR,
    CTLOC_NATCODEDATETO                                                   AS NAT_CODE_DATE_TO,
    NULLIF(TRIM(CTLOC_PREFCONMETHOD), 'NULL')                             AS PREF_CON_METHOD,
    CTLOC_STARTTIMEFB24                                                   AS START_TIME_FB24,
    CTLOC_WARDSINGLESEX                                                   AS WARD_SINGLE_SEX,
    NULLIF(TRIM(CTLOC_CODETRANSLATED), 'NULL')                            AS CODE_TRANSLATED,
    CTLOC_COUNTERTYPE_DR                                                  AS COUNTER_TYPE_DR,
    CTLOC_CREATEDUSER_DR                                                  AS CREATED_USER_DR,
    CTLOC_DATEACTIVEFROM                                                  AS DATE_ACTIVE_FROM,
    NULLIF(TRIM(CTLOC_DESCTRANSLATED), 'NULL')                            AS DESC_TRANSLATED,
    NULLIF(TRIM(CTLOC_EBOOKERENABLED), 'NULL')                            AS EBOOKER_ENABLED,
    NULLIF(TRIM(CTLOC_FLOORPLANQUERY), 'NULL')                            AS FLOOR_PLAN_QUERY,
    NULLIF(TRIM(CTLOC_LABAUTORECEIVE), 'NULL')                            AS LAB_AUTO_RECEIVE,
    CTLOC_MAXDAYSONLEAVE                                                  AS MAX_DAYS_ON_LEAVE,
    NULLIF(TRIM(CTLOC_ORDERSTORECLOC), 'NULL')                            AS ORDER_STORE_CLOC,
    NULLIF(TRIM(CTLOC_OUTPATIENTUNIT), 'NULL')                            AS OUTPATIENT_UNIT,
    CTLOC_PATIENTTYPE_DR                                                  AS PATIENT_TYPE_DR,
    CTLOC_RESTPERIODFROM                                                  AS REST_PERIOD_FROM,
    NULLIF(TRIM(CTLOC_RESULTDELIVERY), 'NULL')                            AS RESULT_DELIVERY,
    NULLIF(TRIM(CTLOC_UPDPHARMSTATUS), 'NULL')                            AS UPD_PHARM_STATUS,
    CTLOC_UPDATEDUSER_DR                                                  AS UPDATED_USER_DR,
    NULLIF(TRIM(CTLOC_CONFIDENTIALFAX), 'NULL')                           AS CONFIDENTIAL_FAX,
    NULLIF(TRIM(CTLOC_CUMULATIVEORDER), 'NULL')                           AS CUMULATIVE_ORDER,
    CTLOC_DAYSFOROPDOFFER                                                 AS DAYS_FOR_OP_OFFER,
    CTLOC_DEFDISCHTIMELOC                                                 AS DEF_DISCH_TIME_LOC,
    NULLIF(TRIM(CTLOC_DISCHARGELOUNGE), 'NULL')                           AS DISCHARGE_LOUNGE,
    CTLOC_EBOOKERSUSPDATE                                                 AS EBOOKER_SUSP_DATE,
    NULLIF(TRIM(CTLOC_EBOOKERSUSPREAS), 'NULL')                           AS EBOOKER_SUSP_REAS,
    NULLIF(TRIM(CTLOC_EBOOKINGENABLED), 'NULL')                           AS EBOOKING_ENABLED,
    NULLIF(TRIM(CTLOC_ENABLEDPHARMREV), 'NULL')                           AS ENABLED_PHARM_REV,
    CTLOC_EXTAVAILABLE_DR                                                 AS EXT_AVAILABLE_DR,
    CTLOC_NATCODEDATEFROM                                                 AS NAT_CODE_DATE_FROM,
    NULLIF(TRIM(CTLOC_BPDISPOSALALLOW), 'NULL')                           AS BP_DISPOSAL_ALLOW,
    CTLOC_DAYSAUTOGENERATE                                                AS DAYS_AUTO_GENERATE,
    CTLOC_DAYSTOKEEPRECORD                                                AS DAYS_TO_KEEP_RECORD,
    CTLOC_DEFAULTMRTYPE_DR                                                AS DEFAULT_MR_TYPE_DR,
    CTLOC_DOCCOURIERCOPIES                                                AS DOC_COURIER_COPIES,
    CTLOC_LABREPORTPAGE_DR                                                AS LAB_REPORT_PAGE_DR,
    CTLOC_LOCCOURIERCOPIES                                                AS LOC_COURIER_COPIES,
    NULLIF(TRIM(CTLOC_MENTALHEALTHUNIT), 'NULL')                          AS MENTAL_HEALTH_UNIT,
    NULLIF(TRIM(CTLOC_RESETPHARMSTATUS), 'NULL')                          AS RESET_PHARM_STATUS,
    NULLIF(TRIM(CTLOC_SENDHL7MESSAGEON), 'NULL')                          AS SEND_HL7_MESSAGE_ON,
    NULLIF(TRIM(CTLOC_SHORTLABSITECODE), 'NULL')                          AS SHORT_LAB_SITE_CODE,
    NULLIF(TRIM(CTLOC_STORAGEBINSTATUS), 'NULL')                          AS STORAGE_BIN_STATUS,
    CTLOC_DAYSCLINSUMMARYED                                               AS DAYS_CLIN_SUMMARY_ED,
    CTLOC_DAYSCLINSUMMARYIP                                               AS DAYS_CLIN_SUMMARY_IP,
    CTLOC_DAYSCLINSUMMARYOP                                               AS DAYS_CLIN_SUMMARY_OP,
    NULLIF(TRIM(CTLOC_EDSTREAMINGMETHOD), 'NULL')                         AS ED_STREAMING_METHOD,
    NULLIF(TRIM(CTLOC_ENABLEEDSTREAMING), 'NULL')                         AS ENABLE_ED_STREAMING,
    CTLOC_SIGNFACILDATEFROM                                               AS SIGN_FACIL_DATE_FROM,
    CTLOC_SIGNIFFACILDATETO                                               AS SIGNIF_FACIL_DATE_TO,
    CTLOC_SIGNIFFACILITY_DR                                               AS SIGNIF_FACILITY_DR,
    CTLOC_TIMESINCELASTAPPT                                               AS TIME_SINCE_LAST_APPT,
    CTLOC_CUMULATIVEEPISODES                                              AS CUMULATIVE_EPISODES,
    NULLIF(TRIM(CTLOC_DISCHSUMEDREQUIRED), 'NULL')                        AS DISCH_SUM_ED_REQUIRED,
    NULLIF(TRIM(CTLOC_DISCHSUMIPREQUIRED), 'NULL')                        AS DISCH_SUM_IP_REQUIRED,
    NULLIF(TRIM(CTLOC_DISCHSUMOPREQUIRED), 'NULL')                        AS DISCH_SUM_OP_REQUIRED,
    NULLIF(TRIM(CTLOC_DONOTSETBEDUNAVAIL), 'NULL')                        AS DO_NOT_SET_BED_UNAVAIL,
    NULLIF(TRIM(CTLOC_DOCTORSREPORTSTYPE), 'NULL')                        AS DOCTORS_REPORTS_TYPE,
    NULLIF(TRIM(CTLOC_EBOOKERIURPENABLED), 'NULL')                        AS EBOOKER_IURP_ENABLED,
    NULLIF(TRIM(CTLOC_EDDISCHSUMMARYTYPE), 'NULL')                        AS ED_DISCH_SUMMARY_TYPE,
    NULLIF(TRIM(CTLOC_EXTERNALINFOSYSTEM), 'NULL')                        AS EXTERNAL_INFO_SYSTEM,
    NULLIF(TRIM(CTLOC_EXTERNALVIEWERLINK), 'NULL')                        AS EXTERNAL_VIEWER_LINK,
    NULLIF(TRIM(CTLOC_HIGHDEPENDENCYUNIT), 'NULL')                        AS HIGH_DEPENDENCY_UNIT,
    NULLIF(TRIM(CTLOC_IPDISCHSUMMARYTYPE), 'NULL')                        AS IP_DISCH_SUMMARY_TYPE,
    NULLIF(TRIM(CTLOC_MRREQUESTMOVEVALID), 'NULL')                        AS MR_REQUEST_MOVE_VALID,
    NULLIF(TRIM(CTLOC_OPDISCHSUMMARYTYPE), 'NULL')                        AS OP_DISCH_SUMMARY_TYPE,
    NULLIF(TRIM(CTLOC_PATDIARYSPECCOLOUR), 'NULL')                        AS PAT_DIARY_SPEC_COLOUR,
    NULLIF(TRIM(CTLOC_PHARMREVSTATNOTREQ), 'NULL')                        AS PHARM_REV_STAT_NOT_REQ,
    NULLIF(TRIM(CTLOC_REHABILITATIVEFLAG), 'NULL')                        AS REHABILITATIVE_FLAG,
    NULLIF(TRIM(CTLOC_ALLOWLABBULKRECEIVE), 'NULL')                       AS ALLOW_LAB_BULK_RECEIVE,
    NULLIF(TRIM(CTLOC_DISCHSUMNOTREQUIRED), 'NULL')                       AS DISCH_SUM_NOT_REQUIRED,
    NULLIF(TRIM(CTLOC_EXECUTECONFIRMATION), 'NULL')                       AS EXECUTE_CONFIRMATION,
    NULLIF(TRIM(CTLOC_MANDATORYBEFOREPACK), 'NULL')                       AS MANDATORY_BEFORE_PACK,
    NULLIF(TRIM(CTLOC_MEDICALRECORDACTIVE), 'NULL')                       AS MEDICAL_RECORD_ACTIVE,
    CTLOC_PATIENTAGESEXMIX_DR                                             AS PATIENT_AGE_SEX_MIX_DR,
    CTLOC_PREFEREDOUTLIERWARD                                             AS PREFERRED_OUTLIER_WARD,
    CTLOC_BEDREASONNOTAVAIL_DR                                            AS BED_REASON_NOT_AVAIL_DR,
    CTLOC_BROADPATIENTGROUP_DR                                            AS BROAD_PATIENT_GROUP_DR,
    NULLIF(TRIM(CTLOC_CUMULATIVEPREFERENCE), 'NULL')                      AS CUMULATIVE_PREFERENCE,
    CTLOC_DEPARTMENTHEADUSERDR                                            AS DEPT_HEAD_USER_DR,
    NULLIF(TRIM(CTLOC_DIFFERENTSEXPATIENTS), 'NULL')                      AS DIFFERENT_SEX_PATIENTS,
    NULLIF(TRIM(CTLOC_ENVSUBJECTAPPLICABLE), 'NULL')                      AS ENV_SUBJECT_APPLICABLE,
    NULLIF(TRIM(CTLOC_EXCLHOSPAVERPRICEQTY), 'NULL')                      AS EXCL_HOSP_AVER_PRICE_QTY,
    NULLIF(TRIM(CTLOC_MANDATORYBEFOREADMIN), 'NULL')                      AS MANDATORY_BEFORE_ADMIN,
    NULLIF(TRIM(CTLOC_RADORDACCESSNOPREFIX), 'NULL')                      AS RAD_ORD_ACCESS_NO_PREFIX,
    CTLOC_THIRDPARTYCOURIER_DR                                            AS THIRD_PARTY_COURIER_DR,
    NULLIF(TRIM(CTLOC_VETSUBJECTAPPLICABLE), 'NULL')                      AS VET_SUBJECT_APPLICABLE,
    NULLIF(TRIM(CTLOC_WEEKLYAVAILINDICATOR), 'NULL')                      AS WEEKLY_AVAIL_INDICATOR,
    NULLIF(TRIM(CTLOC_TELEHEALTHAPPOINTMENT), 'NULL')                     AS TELEHEALTH_APPOINTMENT,
    CTLOC_WEEKSSUSPENSIONREVIEW                                           AS WEEKS_SUSPENSION_REVIEW,
    CTLOC_DAYSOFFEROUTCOMECHANGE                                          AS DAYS_OFFER_OUTCOME_CHANGE,
    NULLIF(TRIM(CTLOC_MULTDATERANGESVISITHRS), 'NULL')                    AS MULT_DATE_RANGES_VISIT_HRS,
    NULLIF(TRIM(CTLOC_OPENOVERNIGHTINDICATOR), 'NULL')                    AS OPEN_OVERNIGHT_INDICATOR,
    CTLOC_DAYSFOROPLETTERRESPONSE                                         AS DAYS_FOR_OP_LETTER_RESPONSE,
    NULLIF(TRIM(CTLOC_PRINTLABELSURGMRREQUEST), 'NULL')                   AS PRINT_LABEL_SURG_MR_REQUEST,
    CTLOC_THIRDPARTYCOURIERCOPIES                                         AS THIRD_PARTY_COURIER_COPIES,
    NULLIF(TRIM(CTLOC_CHARGEACCOMPATIENTONLEAVE), 'NULL')                 AS CHARGE_ACCOM_PATIENT_ON_LEAVE,
    CTLOC_EXTERNALINTERFACEQUEUE_DR                                       AS EXTERNAL_INTERFACE_QUEUE_DR,
    NULLIF(TRIM(CTLOC_LABDEFAULTRECEIVEDATETIME), 'NULL')                 AS LAB_DEFAULT_RECEIVE_DATE_TIME,
    NULLIF(TRIM(CTLOC_PBSPHARMACYAPPROVALNUMBER), 'NULL')                 AS PBS_PHARMACY_APPROVAL_NO,
    CTLOC_REFERRINGDOCTORCOURIER_DR                                       AS REFERRING_DOCTOR_COURIER_DR,
    NULLIF(TRIM(CTLOC_AUTOSENDAWAYTOLABEPLABSITE), 'NULL')                AS AUTO_SEND_AWAY_TO_LAB_EP_LAB_SITE,
    CTLOC_CHILDHEALTHORGANISATION_DR                                      AS CHILD_HEALTH_ORGANISATION_DR,
    CTLOC_DEFAULTCOLLECTIONCENTRE_DR                                      AS DEFAULT_COLLECTION_CENTRE_DR,
    CTLOC_DEFAULTRAPIDREQUESTFORM_DR                                      AS DEFAULT_RAPID_REQUEST_FORM_DR,
    NULLIF(TRIM(CTLOC_DONOTDISPLAYROOMDESCFORBED), 'NULL')                AS DO_NOT_DISPLAY_ROOM_DESC_FOR_BED,
    NULLIF(TRIM(CTLOC_DOCTORSREPORTSDELIVERYSORT), 'NULL')                AS DOCTORS_REPORTS_DELIVERY_SORT,
    CTLOC_INTENDCLINCAREINTENSITY_DR                                      AS INTEND_CLIN_CARE_INTENSITY_DR,
    CTLOC_OFFERSBEFOREIP_OPWAITRESET                                      AS OFFERS_BEFORE_IP_OP_WAIT_RESET,
    NULLIF(TRIM(CTLOC_ENABLEDISCHARGEALLHYPERLINK), 'NULL')               AS ENABLE_DISCHARGE_ALL_HYPERLINK,
    CTLOC_REFERRINGDOCTORCOURIERCOPIES                                    AS REFERRING_DOCTOR_COURIER_COPIES,
    NULLIF(TRIM(CTLOC_COLLECTIONCENTRELICENSENUMBER), 'NULL')             AS COLLECTION_CENTRE_LICENCE_NO,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_CT_LOC') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')