SELECT
    NULLIF(TRIM(APPT_ROWID), 'NULL')                                      AS ROW_ID,
    APPT_PAPMI_DR                                                         AS PATIENT_DR,
    APPT_ADM_DR                                                           AS ADM_DR,
    APPT_LOC_DR                                                           AS LOC_DR,
    APPT_AT_DR                                                            AS AT_DR,
    APPT_ASSI_DR                                                          AS ASSI_DR,
    APPT_HRG_DR                                                           AS HRG_DR,
    APPT_RBOP_DR                                                          AS RBOP_DR,
    APPT_METHOD_DR                                                        AS METHOD_DR,
    APPT_OUTCOME_DR                                                       AS OUTCOME_DR,
    APPT_OPDROOM_DR                                                       AS OPD_ROOM_DR,
    APPT_RBEVENT_DR                                                       AS RB_EVENT_DR,
    APPT_RBCSERV_DR                                                       AS RBC_SERV_DR,
    APPT_RTTHOSP_DR                                                       AS RTT_HOSP_DR,
    APPT_RTTSPEC_DR                                                       AS RTT_SPEC_DR,
    APPT_WAITLIST_DR                                                      AS WAIT_LIST_DR,
    APPT_LANGUAGE_DR                                                      AS LANGUAGE_DR,
    APPT_BOOKEDBY_DR                                                      AS BOOKED_BY_DR,
    APPT_EQUIPMENT_DR                                                     AS EQUIPMENT_DR,
    APPT_TRANSPORT_DR                                                     AS TRANSPORT_DR,
    APPT_TRANSUSER_DR                                                     AS TRANS_USER_DR,
    APPT_INTERPRETER_DR                                                   AS INTERPRETER_DR,
    APPT_REVIEWPERIOD_DR                                                  AS REVIEW_PERIOD_DR,
    APPT_RBATTENDANCE_DR                                                  AS RB_ATTENDANCE_DR,
    APPT_PPMSSEARCH_DR                                                    AS PPMS_SEARCH_DR,
    APPT_SERVICESET_DR                                                    AS SERVICE_SET_DR,
    APPT_ADMINCATEGORY_DR                                                 AS ADMIN_CATEGORY_DR,
    APPT_AUTHORISEUSER_DR                                                 AS AUTHORISE_USER_DR,
    APPT_BILLINGMETHOD_DR                                                 AS BILLING_METHOD_DR,
    APPT_BOOKINGSYSTEM_DR                                                 AS BOOKING_SYSTEM_DR,
    APPT_CAREPROVGROUP_DR                                                 AS CARE_PROV_GROUP_DR,
    APPT_CAREPROVTYPE_DR                                                  AS CARE_PROV_TYPE_DR,
    APPT_CONSULTCATEG_DR                                                  AS CONSULT_CATEG_DR,
    APPT_CONTDELIVMODE_DR                                                 AS CONT_DELIV_MODE_DR,
    APPT_CONTSESSIONTYPE_DR                                               AS CONT_SESSION_TYPE_DR,
    APPT_CONTDELIVSETTING_DR                                              AS CONT_DELIV_SETTING_DR,
    APPT_CONTCLIENTPRESSTAT_DR                                            AS CONT_CLIENT_PRES_STAT_DR,
    APPT_INSURASSOCIATION_DR                                              AS INSUR_ASSOCIATION_DR,
    APPT_PAYORCONTACTTYPE_DR                                              AS PAYOR_CONTACT_TYPE_DR,
    APPT_PREASSAPPRBOP_DR                                                 AS PRE_ASS_APPR_BOP_DR,
    APPT_REASONFORCANCEL_DR                                               AS REASON_FOR_CANCEL_DR,
    APPT_REASONNOTSHOW                                                    AS REASON_NOT_SHOW,
    APPT_REASONOVERBOOK_DR                                                AS REASON_OVERBOOK_DR,
    APPT_RTTREFERPRIOR_DR                                                 AS RTT_REFER_PRIOR_DR,
    APPT_RTTCONS_DR                                                       AS RTT_CONS_DR,
    APPT_SOURCEOFATTEND_DR                                                AS SOURCE_OF_ATTEND_DR,
    APPT_TREATMENTPLAN_DR                                                 AS TREATMENT_PLAN_DR,
    APPT_WAITLISTSTATUS_DR                                                AS WAIT_LIST_STATUS_DR,
    APPT_LASTUPDATEHOSPITAL_DR                                            AS LAST_UPDATE_HOSPITAL_DR,
    APPT_LASTSTATUSCHANGEUSER_DR                                          AS LAST_STATUS_CHANGE_USER_DR,
    APPT_LASTSTATUSCHANGEHOSPITAL_DR                                      AS LAST_STATUS_CHANGE_HOSPITAL_DR,
    APPT_CONFIRMATIONRESPONSE_DR                                          AS CONFIRMATION_RESPONSE_DR,
    APPT_FOLLOWUPAPPTHOSPITAL_DR                                          AS FOLLOW_UP_APPT_HOSPITAL_DR,
    APPT_REASONBOOKPASTTTG_DR                                             AS REASON_BOOK_PAST_TTG_DR,
    APPT_REASONFORTRANSFER_DR                                             AS REASON_FOR_TRANSFER_DR,

    -- Date/time columns (typed in RAW)
    APPT_ETA                                                              AS ETA,
    APPT_ENDDATE                                                          AS END_DATE,
    APPT_ENDTIME                                                          AS END_TIME,
    APPT_SEENDATE                                                         AS SEEN_DATE,
    APPT_SEENTIME                                                         AS SEEN_TIME,
    APPT_TIMECOMP                                                         AS COMPLETION_TIME,
    APPT_DATECOMP                                                         AS COMPLETION_DATE,
    APPT_TRANSDATE                                                        AS TRANS_DATE,
    APPT_TRANSTIME                                                        AS TRANS_TIME,
    APPT_BOOKEDDATE                                                       AS BOOKED_DATE,
    APPT_BOOKEDTIME                                                       AS BOOKED_TIME,
    APPT_CANCELDATE                                                       AS CANCEL_DATE,
    APPT_CANCELTIME                                                       AS CANCEL_TIME,
    APPT_DATESEARCH                                                       AS DATE_SEARCH,
    APPT_ARRIVALDATE                                                      AS ARRIVAL_DATE,
    APPT_ARRIVALTIME                                                      AS ARRIVAL_TIME,
    APPT_ARRIVALTIMECP1                                                   AS ARRIVAL_TIME_CP1,
    APPT_ARRIVALTIMECP2                                                   AS ARRIVAL_TIME_CP2,
    APPT_DEPARTURETIMECP1                                                 AS DEPARTURE_TIME_CP1,
    APPT_DEPARTURETIMECP2                                                 AS DEPARTURE_TIME_CP2,
    APPT_TRANSFERDATE                                                     AS TRANSFER_DATE,
    APPT_TRANSFERTIME                                                     AS TRANSFER_TIME,
    APPT_CONFIRMEDDATE                                                    AS CONFIRMED_DATE,
    APPT_DEPARTUREDATE                                                    AS DEPARTURE_DATE,
    APPT_DEPARTURETIME                                                    AS DEPARTURE_TIME,
    APPT_NEXTAPPTDATE                                                     AS NEXT_APPT_DATE,
    APPT_FOLLOWUPAPPTDATE                                                 AS FOLLOW_UP_APPT_DATE,
    APPT_INWITHDOCTORDATE                                                 AS IN_WITH_DOCTOR_DATE,
    APPT_INWITHDOCTORTIME                                                 AS IN_WITH_DOCTOR_TIME,
    APPT_INWITHNURSEDATE                                                  AS IN_WITH_NURSE_DATE,
    APPT_INWITHNURSETIME                                                  AS IN_WITH_NURSE_TIME,
    APPT_SEENBYNURSEDATE                                                  AS SEEN_BY_NURSE_DATE,
    APPT_SEENBYNURSETIME                                                  AS SEEN_BY_NURSE_TIME,
    APPT_LASTUPDATEDATE                                                   AS LAST_UPDATE_DATE,
    APPT_LASTSTATUSCHANGEDATE                                             AS LAST_STATUS_CHANGE_DATE,
    APPT_LASTSTATUSCHANGETIME                                             AS LAST_STATUS_CHANGE_TIME,
    APPT_COMMREPORTEDDATE                                                 AS COMM_REPORTED_DATE,

    -- Numeric/float columns
    APPT_ESCORT                                                           AS ESCORT,
    APPT_CHILDSUB                                                         AS CHILD_SUB,
    APPT_DURATION                                                         AS DURATION,
    APPT_TRANSCOUNT                                                       AS TRANS_COUNT,

    -- Boolean
    APPT_ASSOCIATED_FLAG                                                  AS ASSOCIATED_FLAG,

    -- VARCHAR columns
    NULLIF(TRIM(APPT_EBEI), 'NULL')                                       AS EBEI,
    NULLIF(TRIM(APPT_RBTR), 'NULL')                                       AS RBTR,
    NULLIF(TRIM(APPT_RSVP), 'NULL')                                       AS RSVP,
    NULLIF(TRIM(APPT_UBRN), 'NULL')                                       AS UBRN,
    NULLIF(TRIM(APPT_USRN), 'NULL')                                       AS USRN,
    NULLIF(TRIM(APPT_VIEW), 'NULL')                                       AS VIEW,
    NULLIF(TRIM(APPT_STATUS), 'NULL')                                     AS STATUS,
    NULLIF(TRIM(APPT_URGENT), 'NULL')                                     AS URGENT,
    NULLIF(TRIM(APPT_YESNO1), 'NULL')                                     AS YES_NO_1,
    NULLIF(TRIM(APPT_APPT_DR), 'NULL')                                    AS APPT_DR,
    NULLIF(TRIM(APPT_ADMTYPE), 'NULL')                                    AS ADM_TYPE,
    NULLIF(TRIM(APPT_NOTUSED), 'NULL')                                    AS NOT_USED,
    NULLIF(TRIM(APPT_QUEUENO), 'NULL')                                    AS QUEUE_NO,
    NULLIF(TRIM(APPT_REMARKS), 'NULL')                                    AS REMARKS,
    NULLIF(TRIM(APPT_ARCIM_DR), 'NULL')                                   AS ARCIM_DR,
    NULLIF(TRIM(APPT_ACTIVITY), 'NULL')                                   AS ACTIVITY,
    NULLIF(TRIM(APPT_MRPULLED), 'NULL')                                   AS MR_PULLED,
    NULLIF(TRIM(APPT_OEORI_DR), 'NULL')                                   AS OE_ORI_DR,
    NULLIF(TRIM(APPT_PANOK_DR), 'NULL')                                   AS PAN_OK_DR,
    NULLIF(TRIM(APPT_VERIFIED), 'NULL')                                   AS VERIFIED,
    NULLIF(TRIM(APPT_AS_PARREF), 'NULL')                                  AS AS_PAR_REF,
    NULLIF(TRIM(APPT_GROUPDESC), 'NULL')                                  AS GROUP_DESC,
    NULLIF(TRIM(APPT_PAYEDFLAG), 'NULL')                                  AS PAYED_FLAG,
    NULLIF(TRIM(APPT_INFECTIOUS), 'NULL')                                 AS INFECTIOUS,
    NULLIF(TRIM(APPT_MOVEMEDREC), 'NULL')                                 AS MOVE_MED_REC,
    NULLIF(TRIM(APPT_PROBLEM_DR), 'NULL')                                 AS PROBLEM_DR,
    NULLIF(TRIM(APPT_SMSCONSENT), 'NULL')                                 AS SMS_CONSENT,
    NULLIF(TRIM(APPT_TECHNICIAN), 'NULL')                                 AS TECHNICIAN,
    NULLIF(TRIM(APPT_CONFIRMEDBY), 'NULL')                                AS CONFIRMED_BY,
    NULLIF(TRIM(APPT_CUSTOMFLAG1), 'NULL')                                AS CUSTOM_FLAG_1,
    NULLIF(TRIM(APPT_CUSTOMFLAG2), 'NULL')                                AS CUSTOM_FLAG_2,
    NULLIF(TRIM(APPT_CUSTOMFLAG3), 'NULL')                                AS CUSTOM_FLAG_3,
    NULLIF(TRIM(APPT_CUSTOMTEXT1), 'NULL')                                AS CUSTOM_TEXT_1,
    NULLIF(TRIM(APPT_CUSTOMTEXT2), 'NULL')                                AS CUSTOM_TEXT_2,
    NULLIF(TRIM(APPT_CUSTOMTEXT3), 'NULL')                                AS CUSTOM_TEXT_3,
    NULLIF(TRIM(APPT_MEETINGLINK), 'NULL')                                AS MEETING_LINK,
    NULLIF(TRIM(APPT_PAYBYRESULT), 'NULL')                                AS PAY_BY_RESULT,
    NULLIF(TRIM(APPT_PAYMENTLINK), 'NULL')                                AS PAYMENT_LINK,
    NULLIF(TRIM(APPT_CAREPROVIDER), 'NULL')                               AS CARE_PROVIDER,
    NULLIF(TRIM(APPT_CONFIRMATION), 'NULL')                               AS CONFIRMATION,
    NULLIF(TRIM(APPT_APPOINTLETTER), 'NULL')                              AS APPT_LETTER,
    NULLIF(TRIM(APPT_BILLDOCTOR_DR), 'NULL')                              AS BILL_DOCTOR_DR,
    NULLIF(TRIM(APPT_FAMILYBOOKING), 'NULL')                              AS FAMILY_BOOKING,
    NULLIF(TRIM(APPT_INPATIENTFLAG), 'NULL')                              AS INPATIENT_FLAG,
    NULLIF(TRIM(APPT_PATIENTSTATUS), 'NULL')                              AS PATIENT_STATUS,
    NULLIF(TRIM(APPT_SEENDOCTOR_DR), 'NULL')                              AS SEEN_DOCTOR_DR,
    NULLIF(TRIM(APPT_SYSTEMSESSION), 'NULL')                              AS SYSTEM_SESSION,
    NULLIF(TRIM(APPT_EXECUTEDSTATUS), 'NULL')                             AS EXECUTED_STATUS,
    NULLIF(TRIM(APPT_REQUESTEDCP_DR), 'NULL')                             AS REQUESTED_CP_DR,
    NULLIF(TRIM(APPT_AUTOASSIGNEDFLG), 'NULL')                            AS AUTO_ASSIGNED_FLG,
    NULLIF(TRIM(APPT_CAREPROVIDER2_DR), 'NULL')                           AS CARE_PROVIDER_2_DR,
    NULLIF(TRIM(APPT_EVENTSUBMITCP_DR), 'NULL')                           AS EVENT_SUBMIT_CP_DR,
    NULLIF(TRIM(APPT_EXTERNALFILLERNO), 'NULL')                           AS EXTERNAL_FILLER_NO,
    NULLIF(TRIM(APPT_EXTERNALPLACERNO), 'NULL')                           AS EXTERNAL_PLACER_NO,
    NULLIF(TRIM(APPT_FIRSTAPPOINTFLAG), 'NULL')                           AS FIRST_APPT_FLAG,
    NULLIF(TRIM(APPT_MAINGROUPAPPT_DR), 'NULL')                           AS MAIN_GROUP_APPT_DR,
    NULLIF(TRIM(APPT_NURSINGNOTESFLAG), 'NULL')                           AS NURSING_NOTES_FLAG,
    NULLIF(TRIM(APPT_RBEVENTTIMES_DR), 'NULL')                            AS RB_EVENT_TIMES_DR,
    NULLIF(TRIM(APPT_DOCTORLETTERNOTES), 'NULL')                          AS DOCTOR_LETTER_NOTES,
    NULLIF(TRIM(APPT_FREETEXTREASONTTG), 'NULL')                          AS FREE_TEXT_REASON_TTG,
    NULLIF(TRIM(APPT_SYSTEMSESSIONHOLD), 'NULL')                          AS SYSTEM_SESSION_HOLD,
    NULLIF(TRIM(APPT_TRANSPORTCOMMENTS), 'NULL')                          AS TRANSPORT_COMMENTS,
    NULLIF(TRIM(APPT_TRANSPORTREQUIRED), 'NULL')                          AS TRANSPORT_REQUIRED,
    NULLIF(TRIM(APPT_MAINAPPOINTMENT_DR), 'NULL')                         AS MAIN_APPOINTMENT_DR,
    NULLIF(TRIM(APPT_PATIENTLETTERNOTES), 'NULL')                         AS PATIENT_LETTER_NOTES,
    NULLIF(TRIM(APPT_INTERPRETERREQUIRED), 'NULL')                        AS INTERPRETER_REQUIRED,
    NULLIF(TRIM(APPT_PATIENTNOTATTENDING), 'NULL')                        AS PATIENT_NOT_ATTENDING,
    NULLIF(TRIM(APPT_CANCELLEDONDISCHARGE), 'NULL')                       AS CANCELLED_ON_DISCHARGE,
    NULLIF(TRIM(APPT_EXTERNALPAPERPRESCNO), 'NULL')                       AS EXTERNAL_PAPER_PRESC_NO,
    NULLIF(TRIM(APPT_INTERPRETERCONFIRMED), 'NULL')                       AS INTERPRETER_CONFIRMED,
    NULLIF(TRIM(APPT_PAREFPATHWAYSTAGE_DR), 'NULL')                       AS PAR_EF_PATHWAY_STAGE_DR,
    NULLIF(TRIM(APPT_VIEWABLEBYEPCAREPROV), 'NULL')                       AS VIEWABLE_BY_EP_CARE_PROV,
    NULLIF(TRIM(APPT_DOCUPDATEDOTORDERBILL), 'NULL')                      AS DOC_UPDATED_OT_ORDER_BILL,
    NULLIF(TRIM(APPT_EXTERNALDOCFISCALCODE), 'NULL')                      AS EXTERNAL_DOC_FISCAL_CODE,
    NULLIF(TRIM(APPT_PERSONSCHEDULEITEM_DR), 'NULL')                      AS PERSON_SCHEDULE_ITEM_DR,
    NULLIF(TRIM(APPT_REASONFORCANCELLATION), 'NULL')                      AS REASON_FOR_CANCELLATION,
    NULLIF(TRIM(APPT_EXTERNALPRESCRIPTIONID), 'NULL')                     AS EXTERNAL_PRESCRIPTION_ID,
    NULLIF(TRIM(APPT_FIRSTAVAILABLESCHED_DR), 'NULL')                     AS FIRST_AVAILABLE_SCHED_DR,
    NULLIF(TRIM(APPT_REQUESTCAREPROVIDER2_DR), 'NULL')                    AS REQUEST_CARE_PROVIDER_2_DR,
    NULLIF(TRIM(APPT_PERSONRESPONSIBLECOMMENTS), 'NULL')                  AS PERSON_RESPONSIBLE_COMMENTS,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_RB_APPOINTMENT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')