SELECT
    COMMNEEDS_ROWID                               AS ROW_ID,
    COMMNEEDS_CODE                                AS CODE,
    TRIM(COMMNEEDS_DESC)                          AS DESC,
    COMMNEEDS_DATEFROM                            AS DATE_FROM,
    TRIM(COMMNEEDS_DATETO)                        AS DATE_TO,
    TRIM(COMMNEEDS_OWNER)                         AS OWNER,
    TRIM(COMMNEEDS_CODETABLETAGS)                 AS CODE_TABLE_TAGS,
    TRIM(COMMNEEDS_CREATEDDATE)                   AS CREATED_DATE,
    TRIM(COMMNEEDS_CREATEDTIME)                   AS CREATED_TIME,
    TRIM(COMMNEEDS_CREATEDUSER_DR)                AS CREATED_USER_DR,
    TRIM(COMMNEEDS_UPDATEDDATE)                   AS UPDATED_DATE,
    TRIM(COMMNEEDS_UPDATEDTIME)                   AS UPDATED_TIME,
    TRIM(COMMNEEDS_UPDATEDUSER_DR)                AS UPDATED_USER_DR,

    _AIRBYTE_EXTRACTED_AT                         AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_PAC_COMMUNICATIONNEEDS') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')