SELECT
    RES_ROWID                                                             AS ROW_ID,
    RES_CTLOC_DR                                                          AS CT_LOC_DR,
    NULLIF(TRIM(RES_CTPCP_DR), 'NULL')                                    AS CT_PCP_DR,
    NULLIF(TRIM(RES_EQ_DR), 'NULL')                                       AS EQ_DR,
    NULLIF(TRIM(RES_CODE), 'NULL')                                        AS CODE,
    NULLIF(TRIM(RES_DESC), 'NULL')                                        AS DESCRIPTION,
    NULLIF(TRIM(RES_LASTSCHEDSDATE), 'NULL')                              AS LAST_SCHED_S_DATE,
    NULLIF(TRIM(RES_LASTSCHEDEDATE), 'NULL')                              AS LAST_SCHED_E_DATE,
    RES_AVAILABILITY                                                      AS AVAILABILITY,
    NULLIF(TRIM(RES_CURRNUMPATIN), 'NULL')                                AS CURR_NUM_PAT_IN,
    NULLIF(TRIM(RES_CURRSESSSUMMARY), 'NULL')                             AS CURR_SESS_SUMMARY,
    NULLIF(TRIM(RES_CURRNUMPATOUT), 'NULL')                               AS CURR_NUM_PAT_OUT,
    NULLIF(TRIM(RES_CURRLOADLIMIT), 'NULL')                               AS CURR_LOAD_LIMIT,
    RES_QUEUELEN                                                          AS QUEUE_LEN,
    NULLIF(TRIM(RES_CURRSESSION_DR), 'NULL')                              AS CURR_SESSION_DR,
    NULLIF(TRIM(RES_CURRPENDAPPT), 'NULL')                                AS CURR_PEND_APPT,
    NULLIF(TRIM(RES_TYPE), 'NULL')                                        AS TYPE,
    NULLIF(TRIM(RES_SCHEDULEREQUIRED), 'NULL')                            AS SCHEDULE_REQUIRED,
    NULLIF(TRIM(RES_MRREQUEST), 'NULL')                                   AS MR_REQUEST,
    NULLIF(TRIM(RES_OPERBOOKINGMETHOD), 'NULL')                           AS OPER_BOOKING_METHOD,
    NULLIF(TRIM(RES_SCHEDULEFORTHISHOSPITAL), 'NULL')                     AS SCHEDULE_FOR_THIS_HOSPITAL,
    NULLIF(TRIM(RES_REFHOSP_DR), 'NULL')                                  AS REF_HOSP_DR,
    NULLIF(TRIM(RES_ROOM_DR), 'NULL')                                     AS ROOM_DR,
    NULLIF(TRIM(RES_ALLOCATEDSCHEDULE), 'NULL')                           AS ALLOCATED_SCHEDULE,
    NULLIF(TRIM(RES_DATEHOLD), 'NULL')                                    AS DATE_HOLD,
    NULLIF(TRIM(RES_SHOWINOPERWB), 'NULL')                                AS SHOW_IN_OPER_WB,
    NULLIF(TRIM(RES_DAYSOTCLOSED), 'NULL')                                AS DAYS_OT_CLOSED,
    NULLIF(TRIM(RES_OPERTHEATRETYPE_DR), 'NULL')                          AS OPER_THEATRE_TYPE_DR,
    NULLIF(TRIM(RES_ACTIVE), 'NULL')                                      AS ACTIVE,
    NULLIF(TRIM(RES_DATETO), 'NULL')                                      AS DATE_TO,
    NULLIF(TRIM(RES_ADMITTINGRIGHTS), 'NULL')                             AS ADMITTING_RIGHTS,
    NULLIF(TRIM(RES_IGNOREPUBHOL), 'NULL')                                AS IGNORE_PUB_HOL,
    RES_DATEACTIVEFROM                                                    AS DATE_ACTIVE_FROM,
    NULLIF(TRIM(RES_DATEACTIVETO), 'NULL')                                AS DATE_ACTIVE_TO,
    NULLIF(TRIM(RES_CPCLINICOPTIONS), 'NULL')                             AS CP_CLINIC_OPTIONS,
    NULLIF(TRIM(RES_CPLOCATIONNO), 'NULL')                                AS CP_LOCATION_NO,
    NULLIF(TRIM(RES_VENUE), 'NULL')                                       AS VENUE,
    NULLIF(TRIM(RES_EXTERNALVENUE), 'NULL')                               AS EXTERNAL_VENUE,
    NULLIF(TRIM(RES_EBOOKNOTES), 'NULL')                                  AS EBOOK_NOTES,
    NULLIF(TRIM(RES_STOCKLOC_DR), 'NULL')                                 AS STOCK_LOC_DR,
    NULLIF(TRIM(RES_WLOUTPATIENTRIGHTS), 'NULL')                          AS WL_OUTPATIENT_RIGHTS,
    NULLIF(TRIM(RES_WLTRIAGERIGHTS), 'NULL')                              AS WL_TRIAGE_RIGHTS,
    NULLIF(TRIM(RES_PRINCIPALCPNUMBER), 'NULL')                           AS PRINCIPAL_CP_NO,
    NULLIF(TRIM(RES_BILLINGAGENTID), 'NULL')                              AS BILLING_AGENT_ID,
    NULLIF(TRIM(RES_COURIERCOPIES), 'NULL')                               AS COURIER_COPIES,
    NULLIF(TRIM(RES_MAINLOCATION), 'NULL')                                AS MAIN_LOCATION,
    NULLIF(TRIM(RES_CODETRANSLATED), 'NULL')                              AS CODE_TRANSLATED,
    NULLIF(TRIM(RES_DESCTRANSLATED), 'NULL')                              AS DESC_TRANSLATED

FROM {{ ref('HIST_TRAKCARE_RB_RESOURCE') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')