SELECT
    ENQ_ROWID                                                             AS CONTACT_ID,
    ENQ_PAPER_DR                                                          AS PERSON_DR,
    ENQ_USER_DR                                                           AS USER_DR,
    ENQ_SEX_DR                                                            AS SEX_DR,
    ENQ_CITY_DR                                                           AS CITY_DR,
    ENQ_CITYAREA_DR                                                       AS CITY_AREA_DR,
    ENQ_INSTYPE_DR                                                        AS INS_TYPE_DR,
    ENQ_ITEMCAT_DR                                                        AS ITEM_CAT_DR,
    ENQ_RBEVENT_DR                                                        AS RB_EVENT_DR,
    ENQ_HOSPITAL_DR                                                       AS HOSPITAL_DR,
    ENQ_LOCATION_DR                                                       AS LOCATION_DR,
    ENQ_RESOURCE_DR                                                       AS RESOURCE_DR,
    ENQ_CONTVENUE_DR                                                      AS CONT_VENUE_DR,
    ENQ_NONGOVORG_DR                                                      AS NON_GOV_ORG_DR,
    ENQ_AUXINSTYPE_DR                                                     AS AUX_INS_TYPE_DR,
    ENQ_CONTMETHOD_DR                                                     AS CONT_METHOD_DR,
    ENQ_CONTOUTCOME_DR                                                    AS CONT_OUTCOME_DR,
    ENQ_REQUESTTYPE_DR                                                    AS REQUEST_TYPE_DR,
    ENQ_WAITINGLIST_DR                                                    AS WAITING_LIST_DR,
    ENQ_CONSULTCATEG_DR                                                   AS CONSULT_CATEG_DR,
    ENQ_CONTDELIVMODE_DR                                                  AS CONT_DELIV_MODE_DR,
    ENQ_CONTLOCALGOAL_DR                                                  AS CONT_LOCAL_GOAL_DR,
    ENQ_REQUESTSTATUS_DR                                                  AS REQUEST_STATUS_DR,
    ENQ_CONTWORKERTYPE_DR                                                 AS CONT_WORKER_TYPE_DR,
    ENQ_VARIANCEREASON_DR                                                 AS VARIANCE_REASON_DR,
    ENQ_CONTSERVICEREC2_DR                                                AS CONT_SERVICE_REC2_DR,
    ENQ_CONTSESSIONTYPE_DR                                                AS CONT_SESSION_TYPE_DR,
    ENQ_CONTDELIVSETTING_DR                                               AS CONT_DELIV_SETTING_DR,
    ENQ_SOURCEOFREFERRAL_DR                                               AS SOURCE_OF_REFERRAL_DR,
    ENQ_SERVICETYPEOUTLET_DR                                              AS SERVICE_TYPE_OUTLET_DR,
    ENQ_CONTCLIENTPRESSTAT_DR                                             AS CONT_CLIENT_PRES_STAT_DR,
    ENQ_CONTINTERPRETERTYPE_DR                                            AS CONT_INTERPRETER_TYPE_DR,

    -- Date/time columns (typed)
    ENQ_DATE                                                              AS CONTACT_DATE,
    ENQ_TIME                                                              AS CONTACT_TIME,
    ENQ_DATEUPDATE                                                        AS UPDATED_DATE,
    ENQ_TIMEUPDATE                                                        AS UPDATED_TIME,
    ENQ_ESTIMTIME                                                         AS ESTIM_TIME,

    -- Numeric columns
    ENQ_FEE                                                               AS FEE,
    ENQ_DURATION                                                          AS DURATION,
    ENQ_ESTIMMINS                                                         AS ESTIM_MINS,
    ENQ_TRAVELTIME                                                        AS TRAVEL_TIME,
    ENQ_INDIRECTTIME                                                      AS INDIRECT_TIME,
    ENQ_INTERPRETINGTIME                                                  AS INTERPRETING_TIME,
    ENQ_DISTANCETRAVELLED                                                 AS DISTANCE_TRAVELLED,

    -- VARCHAR columns
    NULLIF(TRIM(ENQ_TEXT1), 'NULL')                                       AS TEXT_1,
    NULLIF(TRIM(ENQ_TEXT2), 'NULL')                                       AS TEXT_2,
    NULLIF(TRIM(ENQ_TEXT3), 'NULL')                                       AS TEXT_3,
    NULLIF(TRIM(ENQ_TEXT4), 'NULL')                                       AS TEXT_4,
    NULLIF(TRIM(ENQ_YESNO1), 'NULL')                                      AS YES_NO_1,
    NULLIF(TRIM(ENQ_YESNO2), 'NULL')                                      AS YES_NO_2,
    NULLIF(TRIM(ENQ_YESNO3), 'NULL')                                      AS YES_NO_3,
    NULLIF(TRIM(ENQ_YESNO4), 'NULL')                                      AS YES_NO_4,
    NULLIF(TRIM(ENQ_CTCP_DR), 'NULL')                                     AS CT_CP_DR,
    NULLIF(TRIM(ENQ_REQDESC), 'NULL')                                     AS REQ_DESC,
    NULLIF(TRIM(ENQ_REQREASON), 'NULL')                                   AS REQ_REASON,
    NULLIF(TRIM(ENQ_CONTTIMEBHR), 'NULL')                                 AS CONT_TIME_BHR,
    NULLIF(TRIM(ENQ_CONTACTNAME), 'NULL')                                 AS CONTACT_NAME,
    NULLIF(TRIM(ENQ_CONTACTTYPE), 'NULL')                                 AS CONTACT_TYPE,
    NULLIF(TRIM(ENQ_PICTURES_DR), 'NULL')                                 AS PICTURES_DR,
    NULLIF(TRIM(ENQ_OEORDITEM_DR), 'NULL')                                AS OE_ORD_ITEM_DR,
    NULLIF(TRIM(ENQ_VOLUNTEERSER), 'NULL')                                AS VOLUNTEER_SER,
    NULLIF(TRIM(ENQ_ACTIONDETAILS), 'NULL')                               AS ACTION_DETAILS,
    NULLIF(TRIM(ENQ_CONTACTNUMBER), 'NULL')                               AS CONTACT_NO,
    NULLIF(TRIM(ENQ_INPATIENTFLAG), 'NULL')                               AS INPATIENT_FLAG,
    NULLIF(TRIM(ENQ_URGENTCONTACT), 'NULL')                               AS URGENT_CONTACT,
    NULLIF(TRIM(ENQ_GOVERNDEPART_DR), 'NULL')                             AS GOVERN_DEPART_DR,
    NULLIF(TRIM(ENQ_RBEVENTTIMES_DR), 'NULL')                             AS RB_EVENT_TIMES_DR,
    NULLIF(TRIM(ENQ_VARIANCEREASONTEXT), 'NULL')                          AS VARIANCE_REASON_TEXT,
    NULLIF(TRIM(ENQ_INTERPRETERREQUIRED), 'NULL')                         AS INTERPRETER_REQUIRED,
    NULLIF(TRIM(ENQ_CONTACTINTERVENTIONS), 'NULL')                        AS CONTACT_INTERVENTIONS,
    NULLIF(TRIM(ENQ_CAREPROVIDERGROUPS), 'NULL')                          AS CARE_PROVIDER_GROUPS,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_PA_ENQUIRYCONTACT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')