SELECT
    LOCATION_MAPPING_KEY,
    NULLIF(TRIM(NATC_ACTUALVALUE), 'NULL')        AS NATC_ACTUAL_VALUE,
    NULLIF(TRIM(CTLOC_DESC), 'NULL')              AS LOC_DESCRIPTION,
    NATC_MAPPEDVALUE                              AS NATC_MAPPED_VALUE,
    NATC_REPORTINGTYPE_DR                         AS REPORTING_TYPE_DR,
    NULLIF(TRIM(REPTYPE_DESC), 'NULL')            AS REPORTING_TYPE_DESC,
    NULLIF(TRIM(CAMPUS), 'NULL')                  AS CAMPUS,
    LEGACYORGANISATIONID                          AS LEGACY_ORGANISATION_ID

FROM {{ ref('HIST_MANUAL_LOCATION_MAPPING') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')