SELECT
    CAST(BIRTHDAY AS DATE)                  AS DOB,
    {{ format_name('LASTNAME') }}           AS LAST_NAME,
    {{ format_name('FIRSTNAME') }}          AS FIRST_NAME,
    TRIM(POSTALCODE)                        AS POSTCODE,
    TRY_TO_NUMBER(TRIM(DATABASEUSERID),18,6) AS BETTER_IMPACT_USER_ID,
    TRIM(VOLUNTEERSTATUS)                   AS STATUS,
    VOLUNTEERDATEJOINED                     AS JOINED_TS,
    DATEOFLASTVOLUNTEERSTATUSCHANGE         AS LAST_STATUS_CHANGE_TS,

    TRIM(CF_ABOUT_YOU_PLEASE_INDICATE_YOUR_GENDER) AS CF_GENDER,
    TRIM(CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_IF_MORE_THAN_ONE_SPECIAL_NEED_APPLIES_PLEASE_LIST_HERE) AS CF_SPECIAL_NEEDS_GROUPS,
    TRIM(CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_DOES_THE_RECIPIENT_IDENTIFY_AS_BEING_FROM_A_SPECIAL_NEEDS_GROUP_) AS IS_CF_IDENTIFIES_AS_SPECIAL_NEEDS,

    _AIRBYTE_EXTRACTED_AT                    AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_BETTER_IMPACT_VOLUNTEER_INFORMATION') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')