SELECT
    TRIM(NO_)                                     AS NO,
    TRIM(SERVICE)                                 AS SERVICE,
    {{ format_name('FIRST_NAME') }}               AS FIRST_NAME,
    {{ format_name('LAST_NAME') }}                AS LAST_NAME,
    TRIM(SUPPLEMENTS)                             AS SUPPLEMENTS,
    TRIM(PKG_MGMT_COST)                           AS PKG_MGMT_COST,
    TRIM(CARE_MGMT_COST)                          AS CARE_MGMT_COST,
    {{ format_date('DISCHARGE_DATE') }}           AS DISCHARGE_DATE,
    TRIM(CARE_RECIPIENT_ID)                       AS CARE_RECIPIENT_ID,
    TRIM(GOVERNMENT_SUBSIDY)                      AS GOVERNMENT_SUBSIDY,
    TRIM(TOTAL_AVAILABLE_FUNDS)                   AS TOTAL_AVAILABLE_FUNDS,
    TRIM(ALLOCATED_TO_CONTINGENCY)                AS ALLOCATED_TO_CONTINGENCY,
    TRIM(CONTINGENCY_BROUGHT_FORWARD)             AS CONTINGENCY_BROUGHT_FORWARD,
    TRIM(CONTINGENCY_CARRIED_FORWARD)             AS CONTINGENCY_CARRIED_FORWARD,
    TRIM(PROVIDER_SUBSIDISED_ITF_FEE)             AS PROVIDER_SUBSIDISED_ITF_FEE,
    TRIM(CONSUMER_AND_ADDITIONAL_CONTRIBUTION)    AS CONSUMER_AND_ADDITIONAL_CONTRIBUTION,
    TRIM(UNALLOCATED_UNSPENT_FUNDS_BROUGHT_FORWARD) AS UNALLOCATED_UNSPENT_FUNDS_BROUGHT_FORWARD,
    TRIM(UNALLOCATED_UNSPENT_FUNDS_CARRIED_FORWARD) AS UNALLOCATED_UNSPENT_FUNDS_CARRIED_FORWARD,
    TRIM(ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_CONTINGENCY) AS ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_CONTINGENCY,
    TRIM(ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_UNALLOCATED) AS ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_UNALLOCATED,

    _AIRBYTE_EXTRACTED_AT                          AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_E_TOOLS_PROVIDER_STATEMENT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')