SELECT
    TRY_TO_NUMBER(TRIM(NO_),18,6)                 AS NO,
    TRIM(SERVICE)                                 AS SERVICE,
    {{ format_name('FIRST_NAME') }}               AS FIRST_NAME,
    {{ format_name('LAST_NAME') }}                AS LAST_NAME,
    TRIM(SUPPLEMENTS)                             AS SUPPLEMENTS,
    TRY_TO_NUMBER(TRIM(PKG_MGMT_COST),18,6)        AS PKG_MGMT_COST,
    TRIM(CARE_MGMT_COST)                          AS CARE_MGMT_COST,
    {{ format_date('DISCHARGE_DATE') }}           AS DISCHARGE_DATE,
    TRY_TO_NUMBER(TRIM(CARE_RECIPIENT_ID),18,6)   AS CARE_RECIPIENT_ID,
    TRIM(GOVERNMENT_SUBSIDY)                      AS GOVERNMENT_SUBSIDY,
    TRY_TO_NUMBER(TRIM(TOTAL_AVAILABLE_FUNDS),18,6) AS TOTAL_AVAILABLE_FUNDS,
    TRIM(ALLOCATED_TO_CONTINGENCY)                AS ALLOCATED_TO_CONTINGENCY,
    TRIM(CONTINGENCY_BROUGHT_FORWARD)             AS CONTINGENCY_BROUGHT_FORWARD,
    TRIM(CONTINGENCY_CARRIED_FORWARD)             AS CONTINGENCY_CARRIED_FORWARD,
    TRIM(PROVIDER_SUBSIDISED_ITF_FEE)             AS PROVIDER_SUBSIDISED_ITF_FEE,
    TRIM(CONSUMER_AND_ADDITIONAL_CONTRIBUTION)    AS CONSUMER_AND_ADDITIONAL_CONTRIBUTION,
    TRY_TO_NUMBER(TRIM(UNALLOCATED_UNSPENT_FUNDS_BROUGHT_FORWARD),18,6) AS UNALLOCATED_UNSPENT_FUNDS_BROUGHT_FORWARD,
    TRY_TO_NUMBER(TRIM(UNALLOCATED_UNSPENT_FUNDS_CARRIED_FORWARD),18,6) AS UNALLOCATED_UNSPENT_FUNDS_CARRIED_FORWARD,
    TRIM(ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_CONTINGENCY) AS ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_CONTINGENCY,
    TRIM(ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_UNALLOCATED) AS ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_UNALLOCATED,

    _AIRBYTE_EXTRACTED_AT                          AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_E_TOOLS_PROVIDER_STATEMENT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')