SELECT
    TRIM(DR_)                                       AS DR_ID,
    {{ format_name('FIRSTNAME') }}                  AS FIRST_NAME,
    {{ format_name('LASTNAME') }}                   AS LAST_NAME,
    TRIM(SLK)                                       AS SLK,
    {{ format_date('DOB') }}                        AS DOB,
    UPPER(TRIM(SEX))                                AS GENDER,
    TRIM(CARDTYPE)                                  AS CARD_TYPE,
    TRIM(ABORIGINALITY)                             AS ABORIGINALITY,
    TRIM(REFUGEE)                                   AS REFUGEE,
    TRIM(ASYLUMSEEKER)                              AS ASYLUM_SEEKER_FLAG,
    {{ format_name('ADDRESS') }}                    AS ADDRESS,
    {{ format_name('SUBURB') }}                     AS CITY,
    TRIM(POSTCODE)                                  AS POSTCODE,
    {{ format_phone('HOMEPHONE') }}                 AS HOME_PHONE,
    {{ format_phone('MOBILEPHONE') }}               AS MOBILE_PHONE,
    TRIM(MEDICARENUMBER)                            AS MEDICARE_NO,
    TRIM(MEDICARESUFFIX)                            AS MEDICARE_IRN,
    TRIM(ACCOMMODATION)                              AS ACCOMMODATION,
    TRIM(ELIGIBLE_CHILD_OR_YOUNG_PERSON)            AS IS_ELIGIBLE_CHILD_OR_YOUNG_PERSON,
    TRIM(ELIGIBLE_PREGNANT_WOMAN)                   AS IS_ELIGIBLE_PREGNANT_WOMAN,
    TRIM(CHILD_OR_YOUNG_PERSON_IN_RESIDENTIAL_CARE) AS IS_CHILD_OR_YOUNG_PERSON_IN_RESIDENTIAL_CARE,
    TRIM(NO_PRIORITY)                                AS NO_PRIORITY,
    TRIM(YOUTH_JUSTICE_CLIENT_IN_CUSTODIAL_CARE)    AS IS_YOUTH_JUSTICE_IN_CUSTODIAL_CARE,
    TRIM(ABORIGINAL_TORRES_STRAIT_ISLANDER)         AS IS_ABORIGINAL_TORRES_STRAIT_ISLANDER,
    TRIM(ASYLUM_SEEKER)                              AS IS_ASYLUM_SEEKER,
    TRIM(REFUGEE_PRIORITY)                           AS IS_REFUGEE_PRIORITY,
    TRIM(MENTAL_HEALTH_CLIENT)                       AS IS_MENTAL_HEALTH,
    TRIM(INTELLECTUAL_DISABILITY_CLIENT)            AS IS_INTELLECTUAL_DISABILITY,
    TRIM(HOMELESS_PERSON)                            AS IS_HOMELESS_PERSON,
    TRIM(EMPTY_VALUE_PRIORITY)                       AS IS_EMPTY_VALUE_PRIORITY,
    TRIM(INTERPRETERREQ)                             AS IS_INTERPRETER_REQ,
    {{ format_name('COUNTRY') }}                    AS COUNTRY,
    {{ format_name('LANGUAGE') }}                   AS LANGUAGE,
    {{ format_name('SCHOOL') }}                     AS SCHOOL,
    TRIM(RISKSTATUS)                                AS RISK_STATUS,

    _AIRBYTE_EXTRACTED_AT                            AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TITANIUM_PATIENT_DETAIL_REPORT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')