SELECT
    TRIM(ACL) AS ACL, TRIM(ACR) AS ACR, TRIM(AHC) AS AHC, TRIM(AHH) AS AHH,
    TRIM(CCL) AS CCL, TRIM(CCR) AS CCR, TRIM(CDC) AS CDC, TRIM(CMG) AS CMG,
    TRIM(DAS) AS DAS, TRIM(EOL) AS EOL, TRIM(FLS) AS FLS, TRIM(GAR) AS GAR,
    TRIM(GCA) AS GCA, TRIM(GCM) AS GCM, TRIM(GMA) AS GMA, TRIM(GOG) AS GOG,
    TRIM(GSA) AS GSA, TRIM(GSM) AS GSM, TRIM(MNT) AS MNT, TRIM(MOD) AS MOD,
    TRIM(MRC) AS MRC, TRIM(MRH) AS MRH, TRIM(NCC) AS NCC, TRIM(NCH) AS NCH,
    TRIM(OFS) AS OFS, TRIM(PAG) AS PAG, TRIM(PAH) AS PAH, TRIM(PCR) AS PCR,
    TRIM(RSC) AS RSC, TRIM(SCL) AS SCL, TRIM(SCR) AS SCR, TRIM(SSP) AS SSP,
    TRIM(TRC) AS TRC, TRIM(TRN) AS TRN,
    TRIM(SYSID)                                    AS SYSID,
    {{ format_name('FULLNAME') }}                  AS FULL_NAME,
    TRIM(RECORDTYPE)                                AS RECORD_TYPE,
    {{ format_name('LETTERSOFNAME') }}              AS NAME_LETTERS,

    _AIRBYTE_EXTRACTED_AT                            AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRIPS_SERVICE_EVENT_EXPORT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')