SELECT
    INST_ROWID                                            AS ROW_ID,
    NULLIF(TRIM(INST_CODE), 'NULL')                       AS CODE,
    NULLIF(TRIM(INST_DESC), 'NULL')                       AS DESCRIPTION,
    NULLIF(TRIM(INST_CODE1), 'NULL')                      AS CODE_1,
    NULLIF(TRIM(INST_CODE2), 'NULL')                      AS CODE_2,
    NULLIF(TRIM(INST_CODE3), 'NULL')                      AS CODE_3,
    NULLIF(TRIM(INST_CODE4), 'NULL')                      AS CODE_4,
    NULLIF(TRIM(INST_OWNER), 'NULL')                      AS OWNER,
    INST_DATETO                                           AS DATE_TO,
    NULLIF(TRIM(INST_CARETYPE), 'NULL')                   AS CARE_TYPE,
    NULLIF(TRIM(INST_CATEGORY), 'NULL')                   AS CATEGORY,
    INST_DATEFROM                                         AS DATE_FROM,
    NULLIF(TRIM(INST_MULTIPART), 'NULL')                  AS MULTI_PART,
    INST_PAYMODE_DR                                       AS PAY_MODE_DR,
    INST_CREATEDDATE                                      AS CREATED_DATE,
    INST_CREATEDTIME                                      AS CREATED_TIME,
    INST_PRIORITY_DR                                      AS PRIORITY_DR,
    INST_UPDATEDDATE                                      AS UPDATED_DATE,
    INST_UPDATEDTIME                                      AS UPDATED_TIME,
    INST_ACCOUNTCLASS                                     AS ACCOUNT_CLASS,
    NULLIF(TRIM(INST_BILLINGLOGIC), 'NULL')               AS BILLING_LOGIC,
    NULLIF(TRIM(INST_INSBATCHONLY), 'NULL')               AS INS_BATCH_ONLY,
    NULLIF(TRIM(INST_CODETABLETAGS), 'NULL')              AS CODE_TABLE_TAGS,
    INST_PAYORGROUP_DR                                    AS PAYOR_GROUP_DR,
    NULLIF(TRIM(INST_CODETRANSLATED), 'NULL')             AS CODE_TRANSLATED,
    NULLIF(TRIM(INST_COMPANYADDRESS), 'NULL')             AS COMPANY_ADDRESS,
    INST_CREATEDUSER_DR                                   AS CREATED_USER_DR,
    NULLIF(TRIM(INST_DESCTRANSLATED), 'NULL')             AS DESC_TRANSLATED,
    INST_LINKINSTYPE_DR                                   AS LINK_INS_TYPE_DR,
    NULLIF(TRIM(INST_UNQUALIFIEDADM), 'NULL')             AS UNQUALIFIED_ADM,
    INST_UPDATEDUSER_DR                                   AS UPDATED_USER_DR,
    NULLIF(TRIM(INST_REPORTONSETCODE), 'NULL')            AS REPORT_ONSET_CODE,
    NULLIF(TRIM(INST_SPLITBILLSBYLOC), 'NULL')            AS SPLIT_BILLS_BY_LOC,
    NULLIF(TRIM(INST_DONOTDEFAULTCOPY), 'NULL')           AS DO_NOT_DEFAULT_COPY,
    NULLIF(TRIM(INST_ACCOMMODATIONTYPE), 'NULL')          AS ACCOMMODATION_TYPE,
    INST_DRGGROUPERVERSION_DR                             AS DRG_GROUPER_VERSION_DR,
    INST_DEFAULTAUXINSTYPE_DR                             AS DEFAULT_AUX_INS_TYPE_DR,
    NULLIF(TRIM(INST_PROGRAMFUNDINGSOURCE), 'NULL')       AS PROGRAM_FUNDING_SOURCE,
    NULLIF(TRIM(INST_REPORTPRIVATEROOMADDON), 'NULL')     AS REPORT_PRIVATE_ROOM_ADDON,
    _AIRBYTE_EXTRACTED_AT                                 AS AIRBYTE_EXTRACTED_TS
FROM {{ ref('HIST_TRAKCARE_ARC_INSURANCETYPE') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')