SELECT
    TRIM(AGE)                                     AS AGE,
    {{ format_name('LGA') }}                       AS LGA,
    UPPER(TRIM(SEX))                               AS GENDER,
    {{ format_name('TOWN') }}                      AS CITY,
    TRIM(ZONE)                                     AS ZONE,
    TRIM(HOIST)                                    AS HOIST,
    {{ format_phone('PHONE') }}                    AS PHONE,
    UPPER(TRIM(STATE))                             AS STATE,
    TRIM(SYSID)                                    AS SYSID,
    {{ format_name('TITLE') }}                     AS TITLE,
    TRIM(DVANUM)                                   AS DVA_NO,
    TRIM(MAPREF)                                   AS MAP_REF,
    {{ format_name('PAIDBY') }}                    AS PAID_BY,
    {{ format_name('STREET') }}                    AS STREET,
    TRIM(COMMENT)                                  AS COMMENT,
    TRIM(PROFILE)                                  AS PROFILE,
    TRIM(SPECIAL)                                  AS IS_SPECIAL,
    TRIM(SUPPORT)                                  AS SUPPORT,
    {{ format_name('SURNAME') }}                   AS LAST_NAME,
    TRIM(DLNUMBER)                                 AS DL_NO,
    {{ format_date('EXITDATE') }}                  AS EXIT_DATE,
    TRIM(EXITFLAG)                                 AS IS_EXIT,
    TRIM(POSTCODE)                                 AS POSTCODE,
    {{ format_name('PREFNAME') }}                  AS PREF_NAME,
    TRIM(PRIORITY)                                 AS PRIORITY,
    TRIM(UNIQUEID)                                 AS TRIPS_ID,
    {{ format_date('ENTRYDATE') }}                 AS ENTRY_DATE,
    {{ format_name('GIVENNAME') }}                 AS FIRST_NAME,
    TRIM(NEWSLCODE)                                AS NEWSL_CODE,
    {{ format_name('CLIENTNAME') }}                AS FULL_NAME_INCL_TITLE,
    TRIM(FUNDSOURCE)                                AS FUND_SOURCE,
    {{ format_date('LASTASSESS') }}                AS LAST_ASSESSMENT_DATE,
    TRIM(PENSIONNUM)                               AS PENSION_NO,
    TRIM(UPDATEFLAG)                                AS IS_UPDATE,
    TRIM(WHEELCHAIR)                                AS IS_WHEELCHAIR,
    TRIM(ACCOUNTCODE)                              AS ACCOUNT_CODE,
    TRIM(CLIENTCLASS)                               AS CLASS,
    {{ format_date('DATEOFBIRTH') }}               AS DOB,
    TRIM(SENDACCOUNT)                               AS IS_SEND_ACCOUNT,
    {{ format_phone('SILENTPHONE') }}              AS SILENT_PHONE,
    LOWER(TRIM(CLIENT_EMAIL))                       AS EMAIL,
    {{ format_name('HOMELANGUAGE') }}              AS HOME_LANGUAGE,
    TRIM(SPECIALNEEDS)                              AS SPECIAL_NEEDS,
    {{ format_name('COUNTRYOFBIRTH') }}             AS BIRTH_COUNTRY,
    TRIM(REFERRALSOURCE)                            AS REFERRAL_SOURCE,
    TRIM(ACCOMMODATIONTYPE)                         AS ACCOMMODATION_TYPE,
    {{ format_phone('CLIENT_WORK_PHONE') }}         AS WORK_PHONE,
    TRIM(INDIGENOUS_STATUS)                         AS INDIGENOUS_STATUS,
    {{ format_name('LINKED_CARER_NAME') }}          AS LINKED_CARER_NAME,
    TRIM(LIVINGARRANGMENTS)                         AS LIVING_ARRANGEMENTS,
    {{ format_phone('CLIENT_MOBILE_PHONE') }}       AS MOBILE_PHONE,
    {{ format_date('LAST_VERIFIED_TRIP_DATE') }}    AS LAST_VERIFIED_TRIP_DATE,
    TRIM(LINKED_CARER_ACCOUNT_CODE)                 AS LINKED_CARER_ACCOUNT_CODE,
    TRIM(CONSENT_TO_PROVIDE_DETAILS)                AS IS_CONSENT_TO_PROVIDE_DETAILS,
    TRIM(CONSENT_FOR_FUTURE_CONTACTS)               AS IS_CONSENT_FOR_FUTURE_CONTACTS,
    TRIM(INTERESTED_IN_SHARING_STORY)               AS IS_INTERESTED_IN_SHARING_STORY,

    _AIRBYTE_EXTRACTED_AT                            AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRIPS_CLIENTS') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')