SELECT
    TRIM("TO")                                    AS SERVICE_TO_TS,
    TRIM("FROM")                                   AS SERVICE_FROM_TS,
    {{ format_name('SITE') }}                      AS SITE,
    TRIM(TAGS)                                     AS TAGS,
    {{ format_name('STAFF') }}                     AS STAFF_FULL_NAME,
    {{ format_name('CLIENTS') }}                   AS CLIENTS,
    TRIM(PROGRAM)                                  AS PROGRAM,
    TRIM(SERVICE)                                  AS SERVICE,
    TRIM(ACTIVITY)                                 AS ACTIVITY,
    {{ format_name('LOCATION') }}                  AS LOCATION,
    TRIM(ACTIVITY_HOURS)                           AS ACTIVITY_HOURS,
    TRIM(ACTIVITY_ID)                              AS ACTIVITY_ID,
    TRIM(ACTIVITY_SIGNED_OFF)                      AS ACTIVITY_SIGNED_OFF,
    TRIM(REPLICATING_STAFF_NOTES)                  AS REPLICATING_STAFF_NOTES,
    TRIM(REPLICATING_CLIENT_NOTES)                 AS REPLICATING_CLIENT_NOTES,
    TRIM(STAFF_AVAILABILITY_ISSUES)                AS STAFF_AVAILABILITY_ISSUES,
    TRIM(NON_REPLICATING_STAFF_NOTES)              AS NON_REPLICATING_STAFF_NOTES,
    TRIM(STAFF_POSITIONS_TO_BE_FILLED)             AS STAFF_POSITIONS_TO_BE_FILLED,
    {{ format_date('ACTIVITY_SIGN_OFF_DATE_TIME') }} AS ACTIVITY_SIGN_OFF_DATE,
    {{ format_name('ACTIVITY_SIGN_OFF_COMPLETED_BY') }} AS ACTIVITY_SIGN_OFF_COMPLETED_BY,
    TRIM(ACTIVITY_TOTAL_NDIS_ALLOCATED_HOURS)      AS ACTIVITY_TOTAL_NDIS_ALLOCATED_HOURS,
    TRIM(ACTIVITY_COMPLETE_NOT_YET_SIGNED_OFF)     AS ACTIVITY_COMPLETE_NOT_YET_SIGNED_OFF,
    TRIM(INVOICES_CREATED_FOR_ONE_OR_MORE_CLIENTS) AS INVOICES_CREATED_FOR_ONE_OR_MORE_CLIENTS,
    TRIM(TIMESHEETS_CREATED_FOR_ONE_OR_MORE_STAFF) AS TIMESHEETS_CREATED_FOR_ONE_OR_MORE_STAFF,
    TRIM(ACTIVITY_COMPLETE_TIMESHEETS_NOT_YET_SIGNED_OFF) AS ACTIVITY_COMPLETE_TIMESHEETS_NOT_YET_SIGNED_OFF,

    _AIRBYTE_EXTRACTED_AT                           AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_SUPPORTABILITY_ACTIVITY_REPORT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')