SELECT
    EPISODE_ID,
    S_NO,
    TRIM(OUTLET)                                              AS OUTLET,
    TRIM(STATUS)                                              AS CLIENT_STATUS,
    TRIM(PARTICIPANT_ID)                                      AS PARTICIPANT_ID,
    CAST(CARE_RECIPIENT_ID AS TEXT) AS CARE_RECIPIENT_ID,
    {{ format_name('TITLE') }}                               AS TITLE,
    {{ format_name('FIRST_NAME') }}                          AS FIRST_NAME,
    {{ format_name('LAST_NAME') }}                           AS LAST_NAME,
    TRIM(BUDGET_CLASSIFICATION_AS_AT_REPORT_DATE)            AS BUDGET_CLASSIFICATION_REPORT_DATE,
    TRIM(INTERIM_OR_FULL_SERVICE_OFFER_AS_AT_REPORT_DATE)    AS INTERIM_OR_FULL_SERVICE_OFFER_REPORT_DATE,
    {{ format_name('SUBURB') }}                              AS SUBURB,
    {{ format_address('ADDRESS_LINE_1') }}                   AS ADDRESS_LINE_1,
    {{ format_address('ADDRESS_LINE_2') }}                   AS ADDRESS_LINE_2,
    UPPER(TRIM(STATE))                                       AS STATE,
    CAST(POSTCODE AS TEXT)                                   AS POSTCODE,
    LOWER(TRIM(EMAIL))                                       AS EMAIL,
    {{ format_name('CARE_MANAGER') }}                        AS CARE_MANAGER,
    {{ format_name('CARE_PARTNER') }}                        AS CARE_PARTNER,
    {{ format_phone('PHONE') }}                              AS PHONE,
    {{ format_phone('MOBILE') }}                             AS MOBILE_PHONE,
    {{ format_date('DATE_OF_BIRTH') }}                       AS DOB,
    TRIM(PAYOR_PROGRAMME_CLASSIFICATION_LEVEL)               AS PAYOR_PROGRAMME_CLASSIFICATION_LEVEL,
    {{ format_date('START_DATE') }}                          AS START_DATE,
    ONGOING_BUDGET,
    RESTORATIVE_CARE,
    END_OF_LIFE,
    ASSISTIVE_TECHNOLOGY,
    HOME_MODIFICATION,
    CLIENT_FUNDED,
    {{ format_date('DISCHARGED_DATE') }}                     AS DISCHARGE_DATE,
    TRIM(DISCHARGED_REASON)                                   AS DISCHARGE_REASON,
    TRIM(MAC_ID)                                              AS MAC_ID,
    IS_VULNERABLE,
    {{ format_date('REASSESSMENT_DATE') }}                   AS REASSESSMENT_DATE,
    TRIM(ASSESSMENT_TYPE)                                     AS ASSESSMENT_TYPE,
    {{ format_date('ASSESSMENT_DATE') }}                     AS ASSESSMENT_DATE,
    TRIM(CARE_PLAN_REVIEW_TYPE)                               AS CARE_PLAN_REVIEW_TYPE,
    {{ format_date('CARE_PLAN_REVIEW_DATE') }}               AS CARE_PLAN_REVIEW_DATE,
    TRIM(PREFERRED_METHOD_OF_CONTACT)                        AS PREF_CONTACT_METHOD,
    TRIM(ABORIGINAL_OR_TORRES_STRAIT_ISLANDER_ORIGIN)        AS ATSI_ORIGIN

FROM {{ ref('HIST_E_TOOLS_ESAH_CLIENTS') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')