SELECT
    NULLIF(TRIM(OEORI_ROWID), 'NULL')                                     AS ROW_ID,
    OEORI_OEORD_PARREF                                                    AS OE_ORD_PAR_REF,
    OEORI_CHILDSUB                                                        AS CHILD_SUB,
    NULLIF(TRIM(OEORI_ITMMAST_DR), 'NULL')                                AS ITM_MAST_DR,
    OEORI_CATEG_DR                                                        AS CATEG_DR,
    OEORI_ADMLOC_DR                                                       AS ADM_LOC_DR,
    OEORI_ORDDEPT_DR                                                      AS ORD_DEPT_DR,
    OEORI_UNIT_DR                                                         AS UNIT_DR,
    OEORI_USERADD                                                         AS USER_ADD,
    OEORI_USERUPDATE                                                      AS USER_UPDATE,
    OEORI_ACTION_DR                                                       AS ACTION_DR,
    OEORI_DURAT_DR                                                        AS DURAT_DR,
    OEORI_INSTR_DR                                                        AS INSTR_DR,
    OEORI_ROUTE_DR                                                        AS ROUTE_DR,
    OEORI_DOSAGE_DR                                                       AS DOSAGE_DR,
    OEORI_ENERGY_DR                                                       AS ENERGY_DR,
    OEORI_PHFREQ_DR                                                       AS PH_FREQ_DR,
    OEORI_RMFREQ_DR                                                       AS RM_FREQ_DR,
    OEORI_RECDEP_DR                                                       AS REC_DEP_DR,
    OEORI_REFCLN_DR                                                       AS REF_CLN_DR,
    OEORI_REFDOC_DR                                                       AS REF_DOC_DR,
    OEORI_VOLUME_DR                                                       AS VOLUME_DR,
    OEORI_BODYSITE_DR                                                     AS BODY_SITE_DR,
    OEORI_ITEMSTAT_DR                                                     AS ITEM_STAT_DR,
    OEORI_MEALTYPE_DR                                                     AS MEAL_TYPE_DR,
    OEORI_PRIORITY_DR                                                     AS PRIORITY_DR,
    OEORI_RICETYPE_DR                                                     AS RICE_TYPE_DR,
    OEORI_SUBCATEG_DR                                                     AS SUB_CATEG_DR,
    OEORI_USERREAD_DR                                                     AS USER_READ_DR,
    OEORI_WAITLIST_DR                                                     AS WAIT_LIST_DR,
    OEORI_CONSCATEG_DR                                                    AS CONS_CATEG_DR,
    OEORI_ORDERTYPE_DR                                                    AS ORDER_TYPE_DR,
    OEORI_PACCLINIC_DR                                                    AS PAC_CLINIC_DR,
    OEORI_SPECIALTY_DR                                                    AS SPECIALTY_DR,
    OEORI_USEREXECUTED                                                    AS USER_EXECUTED,
    OEORI_ADMINROUTE_DR                                                   AS ADMIN_ROUTE_DR,
    OEORI_ANNOTATION_DR                                                   AS ANNOTATION_DR,
    OEORI_CONSULTDEP_DR                                                   AS CONSULT_DEP_DR,
    OEORI_ENTEREDUOM_DR                                                   AS ENTERED_UOM_DR,
    OEORI_EXTBASEUOM_DR                                                   AS EXT_BASE_UOM_DR,
    OEORI_NEEDLETYPE_DR                                                   AS NEEDLE_TYPE_DR,
    OEORI_RBRESOURCE_DR                                                   AS RB_RESOURCE_DR,
    OEORI_REMOTEDUTY_DR                                                   AS REMOTE_DUTY_DR,
    OEORI_RETURNUSER_DR                                                   AS RETURN_USER_DR,
    OEORI_USERADDHOSPDR                                                   AS USER_ADD_HOSP_DR,
    OEORI_USERUNREAD_DR                                                   AS USER_UNREAD_DR,
    OEORI_ALERTREASON_DR                                                  AS ALERT_REASON_DR,
    OEORI_CLINICGROUP_DR                                                  AS CLINIC_GROUP_DR,
    OEORI_IMPLANTTYPE_DR                                                  AS IMPLANT_TYPE_DR,
    OEORI_NEEDLEGAUGE_DR                                                  AS NEEDLE_GAUGE_DR,
    OEORI_CONTRASTTYPE_DR                                                 AS CONTRAST_TYPE_DR,
    OEORI_FLOWRATEUNIT_DR                                                 AS FLOW_RATE_UNIT_DR,
    OEORI_OPERCATEGORY_DR                                                 AS OPER_CATEGORY_DR,
    OEORI_REASONREFUND_DR                                                 AS REASON_REFUND_DR,
    OEORI_USERREVIEWED_DR                                                 AS USER_REVIEWED_DR,
    OEORI_ALLERGYREASON_DR                                                AS ALLERGY_REASON_DR,
    OEORI_COLLECTIONDEP_DR                                                AS COLLECTION_DEP_DR,
    OEORI_INSBILLCONDIT_DR                                                AS INS_BILL_CONDIT_DR,
    OEORI_PENDINGSTATUS_DR                                                AS PENDING_STATUS_DR,
    OEORI_CANCELREASON_DR                                                 AS CANCEL_REASON_DR,
    OEORI_BROKERAGEVENDOR_DR                                              AS BROKERAGE_VENDOR_DR,
    OEORI_PACKOVERREASON_DR                                               AS PACK_OVER_REASON_DR,
    OEORI_PREEXAMUSERHOSPDR                                               AS PRE_EXAM_USER_HOSP_DR,
    OEORI_USERDEPARTMENT_DR                                               AS USER_DEPARTMENT_DR,
    OEORI_VARIANCEREASON_DR                                               AS VARIANCE_REASON_DR,
    OEORI_POSTEXAMUSERHOSPDR                                              AS POST_EXAM_USER_HOSP_DR,
    OEORI_REASONINCRETURN_DR                                              AS REASON_INC_RETURN_DR,
    OEORI_SKINTESTOUTCOME_DR                                              AS SKIN_TEST_OUTCOME_DR,
    OEORI_INDICTRANSFUSION_DR                                             AS INDICT_TRANSFUSION_DR,
    OEORI_RESULTUPDATEUSER_DR                                             AS RESULT_UPDATE_USER_DR,
    OEORI_EXAMABANDONREASON_DR                                            AS EXAM_ABANDON_REASON_DR,
    OEORI_EXTERNALREFDOCTOR_DR                                            AS EXTERNAL_REF_DOCTOR_DR,
    OEORI_MANUFACTURERORDER_DR                                            AS MANUFACTURER_ORDER_DR,
    OEORI_RADIATIONDOESUNIT_DR                                            AS RADIATION_DOES_UNIT_DR,
    OEORI_REASONREJECTPRESC_DR                                            AS REASON_REJECT_PRESC_DR,
    OEORI_SECONDORDERINGUSER_DR                                           AS SECOND_ORDERING_USER_DR,
    OEORI_RESULTUPDATEHOSPITAL_DR                                         AS RESULT_UPDATE_HOSPITAL_DR,
    OEORI_TYPE_SIZEOFFILMSUSED_DR                                         AS TYPE_SIZE_OF_FILMS_USED_DR,
    OEORI_NOCONSENTOVERRIDEREAS_DR                                        AS NO_CONSENT_OVERRIDE_REAS_DR,
    OEORI_FILMREASONFORREJECTION_DR                                       AS FILM_REASON_FOR_REJECTION_DR,
    OEORI_TYPESIZEOFFILMSREJECTED_DR                                      AS TYPE_SIZE_OF_FILMS_REJECTED_DR,

    -- Date/time columns (typed)
    OEORI_DATE                                                            AS ORDER_DATE,
    OEORI_LDMP                                                            AS LDMP,
    OEORI_XDATE                                                           AS X_DATE,
    OEORI_XTIME                                                           AS X_TIME,
    OEORI_STTDAT                                                          AS START_DATE,
    OEORI_STTTIM                                                          AS START_TIME,
    OEORI_ENDDATE                                                         AS END_DATE,
    OEORI_ENDTIME                                                         AS END_TIME,
    OEORI_FINDATE                                                         AS FIN_DATE,
    OEORI_LMPDATE                                                         AS LMP_DATE,
    OEORI_TIMEORD                                                         AS TIME_ORD,
    OEORI_DATEREAD                                                        AS DATE_READ,
    OEORI_TIMEREAD                                                        AS TIME_READ,
    OEORI_DATEUNREAD                                                      AS DATE_UNREAD,
    OEORI_EXPIRYDATE                                                      AS EXPIRY_DATE,
    OEORI_RETURNDATE                                                      AS RETURN_DATE,
    OEORI_RETURNTIME                                                      AS RETURN_TIME,
    OEORI_TIMEUNREAD                                                      AS TIME_UNREAD,
    OEORI_UPDATEDATE                                                      AS UPDATE_DATE,
    OEORI_UPDATETIME                                                      AS UPDATE_TIME,
    OEORI_DATEAUTHREQ                                                     AS DATE_AUTH_REQ,
    OEORI_THEATREDATE                                                     AS THEATRE_DATE,
    OEORI_TIMEAUTHREQ                                                     AS TIME_AUTH_REQ,
    OEORI_APPROVALDATE                                                    AS APPROVAL_DATE,
    OEORI_APPROVALTIME                                                    AS APPROVAL_TIME,
    OEORI_DATEEXECUTED                                                    AS DATE_EXECUTED,
    OEORI_DATEREVIEWED                                                    AS DATE_REVIEWED,
    OEORI_DISCOUNTDATE                                                    AS DISCOUNT_DATE,
    OEORI_DISCOUNTTIME                                                    AS DISCOUNT_TIME,
    OEORI_EPISREADYDATE                                                   AS EPIS_READY_DATE,
    OEORI_EPISREADYTIME                                                   AS EPIS_READY_TIME,
    OEORI_EXAMSTARTTIME                                                   AS EXAM_START_TIME,
    OEORI_HL7RESULTDATE                                                   AS HL7_RESULT_DATE,
    OEORI_HL7RESULTTIME                                                   AS HL7_RESULT_TIME,
    OEORI_INJECTIONTIME                                                   AS INJECTION_TIME,
    OEORI_LABRESULTDATE                                                   AS LAB_RESULT_DATE,
    OEORI_LABRESULTTIME                                                   AS LAB_RESULT_TIME,
    OEORI_AUTHORISEDDATE                                                  AS AUTHORISED_DATE,
    OEORI_AUTHORISEDTIME                                                  AS AUTHORISED_TIME,
    OEORI_EPISARRIVEDATE                                                  AS EPIS_ARRIVE_DATE,
    OEORI_EPISARRIVETIME                                                  AS EPIS_ARRIVE_TIME,
    OEORI_EPISDEPARTDATE                                                  AS EPIS_DEPART_DATE,
    OEORI_EPISDEPARTTIME                                                  AS EPIS_DEPART_TIME,
    OEORI_LABRECEIVEDATE                                                  AS LAB_RECEIVE_DATE,
    OEORI_LABRECEIVETIME                                                  AS LAB_RECEIVE_TIME,
    OEORI_CONTRASTEXPIRYDATE                                              AS CONTRAST_EXPIRY_DATE,
    OEORI_CURRSAMPLEEXPIRY                                                AS CURR_SAMPLE_EXPIRY,
    OEORI_DATEPOAUTHORISED                                                AS DATE_PO_AUTHORISED,
    OEORI_EXPECTEDCOLLDATE                                                AS EXPECTED_COLL_DATE,
    OEORI_EXPECTEDCOLLTIME                                                AS EXPECTED_COLL_TIME,
    OEORI_PROSRECEIVEDDATE                                                AS PROS_RECEIVED_DATE,
    OEORI_PROSRECEIVEDTIME                                                AS PROS_RECEIVED_TIME,
    OEORI_REASSESSMENTDATE                                                AS REASSESSMENT_DATE,
    OEORI_REASSESSMENTTIME                                                AS REASSESSMENT_TIME,
    OEORI_RESULTUPDATEDATE                                                AS RESULT_UPDATE_DATE,
    OEORI_RESULTUPDATETIME                                                AS RESULT_UPDATE_TIME,
    OEORI_TIMEPOAUTHORISED                                                AS TIME_PO_AUTHORISED,
    OEORI_POSTEXAMSTARTTIME                                               AS POST_EXAM_START_TIME,
    OEORI_RESULTAVAILABLEDATE                                             AS RESULT_AVAILABLE_DATE,
    OEORI_SUPPLIERCONTACTEDDATE                                           AS SUPPLIER_CONTACTED_DATE,
    OEORI_SUPPLIERCONTACTEDTIME                                           AS SUPPLIER_CONTACTED_TIME,
    OEORI_PRESCREPEXPIRYDATE                                              AS PRESC_REP_EXPIRY_DATE,

    -- Numeric/float columns
    OEORI_FAT                                                             AS FAT,
    OEORI_COST                                                            AS COST,
    OEORI_TIME                                                            AS TIME,
    OEORI_PRICE                                                           AS PRICE,
    OEORI_FLOWQTY                                                         AS FLOW_QTY,
    OEORI_PROTEIN                                                         AS PROTEIN,
    OEORI_PHQTYORD                                                        AS PH_QTY_ORD,
    OEORI_REFUNDQTY                                                       AS REFUND_QTY,
    OEORI_UNITCOST                                                        AS UNIT_COST,
    OEORI_DAYOFCYCLE                                                      AS DAY_OF_CYCLE,
    OEORI_EXPOSUREKV                                                      AS EXPOSURE_KV,
    OEORI_MAXREPEATS                                                      AS MAX_REPEATS,
    OEORI_QTYPACKUOM                                                      AS QTY_PACK_UOM,
    OEORI_FREQDELAY                                                       AS FREQ_DELAY,
    OEORI_INTERVAL_DR                                                     AS INTERVAL_DR,
    OEORI_ISOTOPEDOSE                                                     AS ISOTOPE_DOSE,
    OEORI_LABELCOPIES                                                     AS LABEL_COPIES,
    OEORI_CARBOHYDRATE                                                    AS CARBOHYDRATE,
    OEORI_EXPOSURE_MAS                                                    AS EXPOSURE_MAS,
    OEORI_NOORDERSLINK                                                    AS NO_ORDERS_LINK,
    OEORI_CONTRASTVOLUME                                                  AS CONTRAST_VOLUME,
    OEORI_PRNMAXDOSE24HRS                                                 AS PRN_MAX_DOSE_24HRS,
    OEORI_PREPARATIONTIME                                                 AS PREPARATION_TIME,
    OEORI_EXTQTYTOBEPACKED                                                AS EXT_QTY_TO_BE_PACKED,
    OEORI_RETENTIONDAYS                                                   AS RETENTION_DAYS,
    OEORI_SCREENINGTIME                                                   AS SCREENING_TIME,
    OEORI_SPEEDFLOWRATE                                                   AS SPEED_FLOW_RATE,
    OEORI_WEEKSPREGNANT                                                   AS WEEKS_PREGNANT,
    OEORI_PRESCREPNUMBERDAYS                                              AS PRESC_REP_NUMBER_DAYS,
    OEORI_PRNTOTNUMBERDOSESALL                                            AS PRN_TOT_NUMBER_DOSES_ALL,
    OEORI_TOTALEXTQTYINBASEUOM                                            AS TOTAL_EXT_QTY_IN_BASE_UOM,

    -- Boolean columns
    OEORI_CONSENTRECEIVED                                                 AS CONSENT_RECEIVED,
    OEORI_ATTACHTOTEXTRESULT                                              AS ATTACH_TO_TEXT_RESULT,

    -- VARCHAR columns
    NULLIF(TRIM(OEORI_PRN), 'NULL')                                       AS PRN,
    NULLIF(TRIM(OEORI_QTY), 'NULL')                                       AS QTY,
    NULLIF(TRIM(OEORI_LAB1), 'NULL')                                      AS LAB_1,
    NULLIF(TRIM(OEORI_LAB2), 'NULL')                                      AS LAB_2,
    NULLIF(TRIM(OEORI_SIZE), 'NULL')                                      AS SIZE,
    NULLIF(TRIM(OEORI_UNIT), 'NULL')                                      AS UNIT,
    NULLIF(TRIM(OEORI_VIEW), 'NULL')                                      AS VIEW,
    NULLIF(TRIM(OEORI_PANIC), 'NULL')                                     AS PANIC,
    NULLIF(TRIM(OEORI_SEQNO), 'NULL')                                     AS SEQ_NO,
    NULLIF(TRIM(OEORI_TEXT1), 'NULL')                                     AS TEXT_1,
    NULLIF(TRIM(OEORI_TEXT2), 'NULL')                                     AS TEXT_2,
    NULLIF(TRIM(OEORI_TEXT3), 'NULL')                                     AS TEXT_3,
    NULLIF(TRIM(OEORI_TEXT4), 'NULL')                                     AS TEXT_4,
    NULLIF(TRIM(OEORI_BBTAG1), 'NULL')                                    AS BB_TAG_1,
    NULLIF(TRIM(OEORI_BBTAG2), 'NULL')                                    AS BB_TAG_2,
    NULLIF(TRIM(OEORI_BBTAG3), 'NULL')                                    AS BB_TAG_3,
    NULLIF(TRIM(OEORI_BBTAG4), 'NULL')                                    AS BB_TAG_4,
    NULLIF(TRIM(OEORI_BBTAG5), 'NULL')                                    AS BB_TAG_5,
    NULLIF(TRIM(OEORI_BILLED), 'NULL')                                    AS BILLED,
    NULLIF(TRIM(OEORI_IVTYPE), 'NULL')                                    AS IV_TYPE,
    NULLIF(TRIM(OEORI_LINKNO), 'NULL')                                    AS LINK_NO,
    NULLIF(TRIM(OEORI_NOTIFY), 'NULL')                                    AS NOTIFY,
    NULLIF(TRIM(OEORI_YESNO1), 'NULL')                                    AS YES_NO_1,
    NULLIF(TRIM(OEORI_YESNO2), 'NULL')                                    AS YES_NO_2,
    NULLIF(TRIM(OEORI_YESNO3), 'NULL')                                    AS YES_NO_3,
    NULLIF(TRIM(OEORI_YESNO4), 'NULL')                                    AS YES_NO_4,
    NULLIF(TRIM(OEORI_APPT_DR), 'NULL')                                   AS APPT_DR,
    NULLIF(TRIM(OEORI_DEPTYPE), 'NULL')                                   AS DEP_TYPE,
    NULLIF(TRIM(OEORI_DOSEQTY), 'NULL')                                   AS DOSE_QTY,
    NULLIF(TRIM(OEORI_ISADHOC), 'NULL')                                   AS IS_AD_HOC,
    NULLIF(TRIM(OEORI_PRESCNO), 'NULL')                                   AS PRESC_NO,
    NULLIF(TRIM(OEORI_REMARKS), 'NULL')                                   AS REMARKS,
    NULLIF(TRIM(OEORI_ARCOS_DR), 'NULL')                                  AS ARCOS_DR,
    NULLIF(TRIM(OEORI_ABNORMAL), 'NULL')                                  AS ABNORMAL,
    NULLIF(TRIM(OEORI_ACTIVITY), 'NULL')                                  AS ACTIVITY,
    NULLIF(TRIM(OEORI_BBSTATUS), 'NULL')                                  AS BB_STATUS,
    NULLIF(TRIM(OEORI_BILLDESC), 'NULL')                                  AS BILL_DESC,
    NULLIF(TRIM(OEORI_COMMENT1), 'NULL')                                  AS COMMENT_1,
    NULLIF(TRIM(OEORI_COMMENT2), 'NULL')                                  AS COMMENT_2,
    NULLIF(TRIM(OEORI_COMMENT3), 'NULL')                                  AS COMMENT_3,
    NULLIF(TRIM(OEORI_DRGORDER), 'NULL')                                  AS DRG_ORDER,
    NULLIF(TRIM(OEORI_DATETIME), 'NULL')                                  AS DATETIME,
    NULLIF(TRIM(OEORI_DIETFLAG), 'NULL')                                  AS DIET_FLAG,
    NULLIF(TRIM(OEORI_FILLERNO), 'NULL')                                  AS FILLER_NO,
    NULLIF(TRIM(OEORI_INFOTYPE), 'NULL')                                  AS INFO_TYPE,
    NULLIF(TRIM(OEORI_LABSEQNO), 'NULL')                                  AS LAB_SEQ_NO,
    NULLIF(TRIM(OEORI_OEORI_DR), 'NULL')                                  AS OEORI_DR,
    NULLIF(TRIM(OEORI_PLACERNO), 'NULL')                                  AS PLACER_NO,
    NULLIF(TRIM(OEORI_PREGNANT), 'NULL')                                  AS PREGNANT,
    NULLIF(TRIM(OEORI_SERIESNO), 'NULL')                                  AS SERIES_NO,
    NULLIF(TRIM(OEORI_UNIT_HRS), 'NULL')                                  AS UNIT_HRS,
    NULLIF(TRIM(OEORI_XCTCP_DR), 'NULL')                                  AS XC_TCP_DR,
    NULLIF(TRIM(OEORI_ANAEST_DR), 'NULL')                                 AS ANAEST_DR,
    NULLIF(TRIM(OEORI_BBEXTCODE), 'NULL')                                 AS BB_EXT_CODE,
    NULLIF(TRIM(OEORI_DELAYMEAL), 'NULL')                                 AS DELAY_MEAL,
    NULLIF(TRIM(OEORI_DOCTOR_DR), 'NULL')                                 AS DOCTOR_DR,
    NULLIF(TRIM(OEORI_ITEMGROUP), 'NULL')                                 AS ITEM_GROUP,
    NULLIF(TRIM(OEORI_LABACTION), 'NULL')                                 AS LAB_ACTION,
    NULLIF(TRIM(OEORI_LABVOLUME), 'NULL')                                 AS LAB_VOLUME,
    NULLIF(TRIM(OEORI_LABELTEXT), 'NULL')                                 AS LABEL_TEXT,
    NULLIF(TRIM(OEORI_ORDENT_DR), 'NULL')                                 AS ORD_ENT_DR,
    NULLIF(TRIM(OEORI_PERSONNEL), 'NULL')                                 AS PERSONNEL,
    NULLIF(TRIM(OEORI_PRESCTYPE), 'NULL')                                 AS PRESC_TYPE,
    NULLIF(TRIM(OEORI_RESULTREF), 'NULL')                                 AS RESULT_REF,
    NULLIF(TRIM(OEORI_ANAOPER_DR), 'NULL')                                AS ANA_OPER_DR,
    NULLIF(TRIM(OEORI_APPROVALNO), 'NULL')                                AS APPROVAL_NO,
    NULLIF(TRIM(OEORI_APPROVEDBY), 'NULL')                                AS APPROVED_BY,
    NULLIF(TRIM(OEORI_CONSULT_DR), 'NULL')                                AS CONSULT_DR,
    NULLIF(TRIM(OEORI_DRCROSS_DR), 'NULL')                                AS DR_CROSS_DR,
    NULLIF(TRIM(OEORI_HICCLAIMNO), 'NULL')                                AS HIC_CLAIM_NO,
    NULLIF(TRIM(OEORI_LTSITECODE), 'NULL')                                AS LT_SITE_CODE,
    NULLIF(TRIM(OEORI_LTSPECCODE), 'NULL')                                AS LT_SPEC_CODE,
    NULLIF(TRIM(OEORI_PHONEORDER), 'NULL')                                AS PHONE_ORDER,
    NULLIF(TRIM(OEORI_PRESCSEQNO), 'NULL')                                AS PRESC_SEQ_NO,
    NULLIF(TRIM(OEORI_REFUNDTYPE), 'NULL')                                AS REFUND_TYPE,
    NULLIF(TRIM(OEORI_REPEATDESC), 'NULL')                                AS REPEAT_DESC,
    NULLIF(TRIM(OEORI_RESULTFLAG), 'NULL')                                AS RESULT_FLAG,
    NULLIF(TRIM(OEORI_WHOGOWHERE), 'NULL')                                AS WHO_GO_WHERE,
    NULLIF(TRIM(OEORI_APPROVALIND), 'NULL')                               AS APPROVAL_IND,
    NULLIF(TRIM(OEORI_CALCQTYFLAG), 'NULL')                               AS CALC_QTY_FLAG,
    NULLIF(TRIM(OEORI_COLLECTEDBY), 'NULL')                               AS COLLECTED_BY,
    NULLIF(TRIM(OEORI_DERIVEDFROM), 'NULL')                               AS DERIVED_FROM,
    NULLIF(TRIM(OEORI_DISCOUNTAMT), 'NULL')                               AS DISCOUNT_AMT,
    NULLIF(TRIM(OEORI_INFOSUBTYPE), 'NULL')                               AS INFO_SUBTYPE,
    NULLIF(TRIM(OEORI_ISBROKERAGE), 'NULL')                               AS IS_BROKERAGE,
    NULLIF(TRIM(OEORI_LINKTOORDER), 'NULL')                               AS LINK_TO_ORDER,
    NULLIF(TRIM(OEORI_PHSPECINSTR), 'NULL')                               AS PH_SPEC_INSTR,
    NULLIF(TRIM(OEORI_PREEXAMUSER), 'NULL')                               AS PRE_EXAM_USER,
    NULLIF(TRIM(OEORI_PROSBATCHNO), 'NULL')                               AS PROS_BATCH_NO,
    NULLIF(TRIM(OEORI_READYTOBILL), 'NULL')                               AS READY_TO_BILL,
    NULLIF(TRIM(OEORI_RESULTEXIST), 'NULL')                               AS RESULT_EXIST,
    NULLIF(TRIM(OEORI_RESULTGROUP), 'NULL')                               AS RESULT_GROUP,
    NULLIF(TRIM(OEORI_SIGNIFICANT), 'NULL')                               AS SIGNIFICANT,
    NULLIF(TRIM(OEORI_ARPBLITEM_DR), 'NULL')                              AS ARPBL_ITEM_DR,
    NULLIF(TRIM(OEORI_ASSISTANT_DR), 'NULL')                              AS ASSISTANT_DR,
    NULLIF(TRIM(OEORI_AUTHCOMMENTS), 'NULL')                              AS AUTH_COMMENTS,
    NULLIF(TRIM(OEORI_CONSULTDR_DR), 'NULL')                              AS CONSULT_DR_DR,
    NULLIF(TRIM(OEORI_COVERMAININS), 'NULL')                              AS COVER_MAIN_INS,
    NULLIF(TRIM(OEORI_DSREPORTFLAG), 'NULL')                              AS DS_REPORT_FLAG,
    NULLIF(TRIM(OEORI_DEMANDNUMBER), 'NULL')                              AS DEMAND_NUMBER,
    NULLIF(TRIM(OEORI_DEPPROCNOTES), 'NULL')                              AS DEP_PROC_NOTES,
    NULLIF(TRIM(OEORI_DISCOUNTPERC), 'NULL')                              AS DISCOUNT_PERC,
    NULLIF(TRIM(OEORI_DONOTDISPLAY), 'NULL')                              AS DO_NOT_DISPLAY,
    NULLIF(TRIM(OEORI_LABEPISODENO), 'NULL')                              AS LAB_EPISODE_NO,
    NULLIF(TRIM(OEORI_MAINOEENT_DR), 'NULL')                              AS MAIN_OE_ENT_DR,
    NULLIF(TRIM(OEORI_PORTEQUIPREQ), 'NULL')                              AS PORT_EQUIP_REQ,
    NULLIF(TRIM(OEORI_POSTEXAMUSER), 'NULL')                              AS POST_EXAM_USER,
    NULLIF(TRIM(OEORI_PROSSERIALNO), 'NULL')                              AS PROS_SERIAL_NO,
    NULLIF(TRIM(OEORI_PROSSUPPLIER), 'NULL')                              AS PROS_SUPPLIER,
    NULLIF(TRIM(OEORI_RVICHARGE_DR), 'NULL')                              AS RVI_CHARGE_DR,
    NULLIF(TRIM(OEORI_STOCKBATCHES), 'NULL')                              AS STOCK_BATCHES,
    NULLIF(TRIM(OEORI_URGENTREPORT), 'NULL')                              AS URGENT_REPORT,
    NULLIF(TRIM(OEORI_VARIABLEDOSE), 'NULL')                              AS VARIABLE_DOSE,
    NULLIF(TRIM(OEORI_COMPXMATCHREQ), 'NULL')                             AS COMP_X_MATCH_REQ,
    NULLIF(TRIM(OEORI_LABTESTSETROW), 'NULL')                             AS LAB_TEST_SET_ROW,
    NULLIF(TRIM(OEORI_NOORDEREDBAGS), 'NULL')                             AS NO_ORDERED_BAGS,
    NULLIF(TRIM(OEORI_NUMBERPERWEEK), 'NULL')                             AS NUMBER_PER_WEEK,
    NULLIF(TRIM(OEORI_OEORDITEM2_DR), 'NULL')                             AS OE_ORD_ITEM_2_DR,
    NULLIF(TRIM(OEORI_PRNINDICATION), 'NULL')                             AS PRN_INDICATION,
    NULLIF(TRIM(OEORI_PASTERIZEFOOD), 'NULL')                             AS PASTERIZE_FOOD,
    NULLIF(TRIM(OEORI_QUESTIONNAIRE), 'NULL')                             AS QUESTIONNAIRE,
    NULLIF(TRIM(OEORI_RADAUTHDOC_DR), 'NULL')                             AS RAD_AUTH_DOC_DR,
    NULLIF(TRIM(OEORI_RETURNTOSTOCK), 'NULL')                             AS RETURN_TO_STOCK,
    NULLIF(TRIM(OEORI_SENTINEXTRACT), 'NULL')                             AS SENT_IN_EXTRACT,
    NULLIF(TRIM(OEORI_TEXT1REVIEWED), 'NULL')                             AS TEXT_1_REVIEWED,
    NULLIF(TRIM(OEORI_TEXT2REVIEWED), 'NULL')                             AS TEXT_2_REVIEWED,
    NULLIF(TRIM(OEORI_USERAUTHORISE), 'NULL')                             AS USER_AUTHORISE,
    NULLIF(TRIM(OEORI_ANAESTAGENT_DR), 'NULL')                            AS ANAEST_AGENT_DR,
    NULLIF(TRIM(OEORI_APPLYTIMEFRAME), 'NULL')                            AS APPLY_TIMEFRAME,
    NULLIF(TRIM(OEORI_DISCOUNTREASON), 'NULL')                            AS DISCOUNT_REASON,
    NULLIF(TRIM(OEORI_PHARMACYSTATUS), 'NULL')                            AS PHARMACY_STATUS,
    NULLIF(TRIM(OEORI_PREGNANCYCHECK), 'NULL')                            AS PREGNANCY_CHECK,
    NULLIF(TRIM(OEORI_RECLOCVERIFIED), 'NULL')                            AS REC_LOC_VERIFIED,
    NULLIF(TRIM(OEORI_REMOTEDUTYTYPE), 'NULL')                            AS REMOTE_DUTY_TYPE,
    NULLIF(TRIM(OEORI_RESULTCOMMENTS), 'NULL')                            AS RESULT_COMMENTS,
    NULLIF(TRIM(OEORI_SPEEDFLOWVALUE), 'NULL')                            AS SPEED_FLOW_VALUE,
    NULLIF(TRIM(OEORI_UNITSCOLLECTED), 'NULL')                            AS UNITS_COLLECTED,
    NULLIF(TRIM(OEORI_ACCESSIONNUMBER), 'NULL')                           AS ACCESSION_NUMBER,
    NULLIF(TRIM(OEORI_ADMINSURANCE_DR), 'NULL')                           AS ADM_INSURANCE_DR,
    NULLIF(TRIM(OEORI_CLINPATHWAYS_DR), 'NULL')                           AS CLIN_PATHWAYS_DR,
    NULLIF(TRIM(OEORI_CONTACTCAREPROV), 'NULL')                           AS CONTACT_CARE_PROV,
    NULLIF(TRIM(OEORI_DAYBOOKSPECIMEN), 'NULL')                           AS DAYBOOK_SPECIMEN,
    NULLIF(TRIM(OEORI_DISPENSINGTIMES), 'NULL')                           AS DISPENSING_TIMES,
    NULLIF(TRIM(OEORI_HL7RESULTSTATUS), 'NULL')                           AS HL7_RESULT_STATUS,
    NULLIF(TRIM(OEORI_LABEPISODESETUP), 'NULL')                           AS LAB_EPISODE_SETUP,
    NULLIF(TRIM(OEORI_NOTIFYCLINICIAN), 'NULL')                           AS NOTIFY_CLINICIAN,
    NULLIF(TRIM(OEORI_PERSONINJECT_DR), 'NULL')                           AS PERSON_INJECT_DR,
    NULLIF(TRIM(OEORI_RADIOLOGYSTATUS), 'NULL')                           AS RADIOLOGY_STATUS,
    NULLIF(TRIM(OEORI_RESULTAVAILABLE), 'NULL')                           AS RESULT_AVAILABLE,
    NULLIF(TRIM(OEORI_TESTSETCOMMENTS), 'NULL')                           AS TEST_SET_COMMENTS,
    NULLIF(TRIM(OEORI_THEATREREQUIRED), 'NULL')                           AS THEATRE_REQUIRED,
    NULLIF(TRIM(OEORI_CURRREPEATNUMBER), 'NULL')                          AS CURR_REPEAT_NUMBER,
    NULLIF(TRIM(OEORI_ORIGINALORDER_DR), 'NULL')                          AS ORIGINAL_ORDER_DR,
    NULLIF(TRIM(OEORI_PATIENTIDCHECKED), 'NULL')                          AS PATIENT_ID_CHECKED,
    NULLIF(TRIM(OEORI_PRIMARYORDERITEM), 'NULL')                          AS PRIMARY_ORDER_ITEM,
    NULLIF(TRIM(OEORI_STERILIZEUTELSIS), 'NULL')                          AS STERILIZE_UTELSIS,
    NULLIF(TRIM(OEORI_DISCOUNTDOCTOR_DR), 'NULL')                         AS DISCOUNT_DOCTOR_DR,
    NULLIF(TRIM(OEORI_DOCTOREXECUTED_DR), 'NULL')                         AS DOCTOR_EXECUTED_DR,
    NULLIF(TRIM(OEORI_ELIGIBILITYSTATUS), 'NULL')                         AS ELIGIBILITY_STATUS,
    NULLIF(TRIM(OEORI_HOTREPORTREQUIRED), 'NULL')                         AS HOT_REPORT_REQUIRED,
    NULLIF(TRIM(OEORI_INSCARDNOOVERRIDE), 'NULL')                         AS INS_CARD_NO_OVERRIDE,
    NULLIF(TRIM(OEORI_ADMINISTERSKINTEST), 'NULL')                        AS ADMINISTER_SKIN_TEST,
    NULLIF(TRIM(OEORI_AUTOLOGOUSBLOODREQ), 'NULL')                        AS AUTOLOGOUS_BLOOD_REQ,
    NULLIF(TRIM(OEORI_BROKERAGEGENERATED), 'NULL')                        AS BROKERAGE_GENERATED,
    NULLIF(TRIM(OEORI_DAYBOOKACCESSIONNO), 'NULL')                        AS DAYBOOK_ACCESSION_NO,
    NULLIF(TRIM(OEORI_MAXNUMBEROFREPEATS), 'NULL')                        AS MAX_NUMBER_OF_REPEATS,
    NULLIF(TRIM(OEORI_OPB_IPB_CONVERSION), 'NULL')                        AS OPB_IPB_CONVERSION,
    NULLIF(TRIM(OEORI_PATCONSENTOBTAINED), 'NULL')                        AS PAT_CONSENT_OBTAINED,
    NULLIF(TRIM(OEORI_REASORDCMVNEGBLOOD), 'NULL')                        AS REAS_ORD_CMV_NEG_BLOOD,
    NULLIF(TRIM(OEORI_REASONNOTCOLLECTED), 'NULL')                        AS REASON_NOT_COLLECTED,
    NULLIF(TRIM(OEORI_RESULTDSREPORTFLAG), 'NULL')                        AS RESULT_DS_REPORT_FLAG,
    NULLIF(TRIM(OEORI_CONTRASTBATCHNUMBER), 'NULL')                       AS CONTRAST_BATCH_NUMBER,
    NULLIF(TRIM(OEORI_LTCLINICALCONDITION), 'NULL')                       AS LT_CLINICAL_CONDITION,
    NULLIF(TRIM(OEORI_SENSITIVITIESSIGNOFF), 'NULL')                      AS SENSITIVITIES_SIGN_OFF,
    NULLIF(TRIM(OEORI_AUTHORISECLINICIAN_DR), 'NULL')                     AS AUTHORISE_CLINICIAN_DR,
    NULLIF(TRIM(OEORI_CLINICALLYSIGNIFICANT), 'NULL')                     AS CLINICALLY_SIGNIFICANT,
    NULLIF(TRIM(OEORI_BROKERAGEVENDORRATE_DR), 'NULL')                    AS BROKERAGE_VENDOR_RATE_DR,
    NULLIF(TRIM(OEORI_CONTORDERAFTERDISCHARGE), 'NULL')                   AS CONT_ORDER_AFTER_DISCHARGE,
    NULLIF(TRIM(OEORI_EXTERNALPRIMARYSPECSITE), 'NULL')                   AS EXTERNAL_PRIMARY_SPEC_SITE,
    NULLIF(TRIM(OEORI_INCOMPLETECOLLECTION), 'NULL')                      AS INCOMPLETE_COLLECTION,
    NULLIF(TRIM(OEORI_PAREFPATHWAYSTAGE_DR), 'NULL')                      AS PAR_EF_PATHWAY_STAGE_DR,
    NULLIF(TRIM(OEORI_EXTERNALSECONDARYSPECSITE), 'NULL')                 AS EXTERNAL_SECONDARY_SPEC_SITE,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_OE_ORDITEM') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')