SELECT
    PAADM_ROWID                                                           AS ADM_ID,
    PAADM_PAPMI_DR                                                        AS PATIENT_DR,
    NULLIF(TRIM(PAADM_TYPE), 'NULL')                                      AS TYPE,
    NULLIF(TRIM(PAADM_ADMNO), 'NULL')                                     AS ADM_NO,
    NULLIF(TRIM(PAADM_ADMREF), 'NULL')                                    AS ADM_REF,
    NULLIF(TRIM(PAADM_CCLASS), 'NULL')                                    AS CARE_CLASS,
    PAADM_EXPLOS                                                          AS EXP_LOS,
    PAADM_HCA_DR                                                          AS HCA_DR,
    PAADM_HCP_DR                                                          AS HCP_DR,
    PAADM_HCR_DR                                                          AS HCR_DR,
    NULLIF(TRIM(PAADM_REMARK), 'NULL')                                    AS REMARK,
    NULLIF(TRIM(PAADM_URGENT), 'NULL')                                    AS URGENT,
    PAADM_ADMDATE                                                         AS ADM_DATE,
    PAADM_ADMTIME                                                         AS ADM_TIME,
    NULLIF(TRIM(PAADM_CURRENT), 'NULL')                                   AS PAADM_CURRENT,
    NULLIF(TRIM(PAADM_HOMERID), 'NULL')                                   AS HOMER_ID,
    NULLIF(TRIM(PAADM_INPATNO), 'NULL')                                   AS INPAT_NO,
    NULLIF(TRIM(PAADM_ISOLATE), 'NULL')                                   AS ISOLATE,
    PAADM_OPER_DR                                                         AS OPER_DR,
    PAADM_REFDATE                                                         AS REF_DATE,
    NULLIF(TRIM(PAADM_RELATED), 'NULL')                                   AS RELATED,
    NULLIF(TRIM(PAADM_ADMREADM), 'NULL')                                  AS ADM_READM,
    NULLIF(TRIM(PAADM_BILLFLAG), 'NULL')                                  AS BILL_FLAG,
    NULLIF(TRIM(PAADM_LONGSTAY), 'NULL')                                  AS LONG_STAY,
    NULLIF(TRIM(PAADM_PREADMNO), 'NULL')                                  AS PRE_ADM_NO,
    PAADM_RUGTOTAL                                                        AS RUG_TOTAL,
    NULLIF(TRIM(PAADM_READONLY), 'NULL')                                  AS READ_ONLY,
    PAADM_SEENDATE                                                        AS SEEN_DATE,
    PAADM_SEENTIME                                                        AS SEEN_TIME,
    NULLIF(TRIM(PAADM_VERIFIED), 'NULL')                                  AS VERIFIED,
    PAADM_ADMSRC_DR                                                       AS ADM_SRC_DR,
    PAADM_AGREEDEDD                                                       AS AGREED_EDD,
    NULLIF(TRIM(PAADM_COMPLETED), 'NULL')                                 AS COMPLETED,
    PAADM_DNAREASON                                                       AS DNA_REASON,
    PAADM_DISPOS_DR                                                       AS DISPOS_DR,
    PAADM_EATING_DR                                                       AS EATING_DR,
    PAADM_INFECT_DR                                                       AS INFECT_DR,
    PAADM_ONSETDATE                                                       AS ONSET_DATE,
    PAADM_ORDERTIME                                                       AS ORDER_TIME,
    PAADM_PAADM2_DR                                                       AS ADM2_DR,
    PAADM_REFADM_DR                                                       AS REF_ADM_DR,
    PAADM_REGION_DR                                                       AS REGION_DR,
    NULLIF(TRIM(PAADM_REQUESTMR), 'NULL')                                 AS REQUEST_MR,
    NULLIF(TRIM(PAADM_APPOINT_DR), 'NULL')                                AS APPOINT_DR,
    NULLIF(TRIM(PAADM_CONSENTDVA), 'NULL')                                AS CONSENT_DVA,
    PAADM_CREATEDATE                                                      AS CREATED_DATE,
    PAADM_CREATETIME                                                      AS CREATED_TIME,
    PAADM_CREATEUSER                                                      AS CREATED_USER,
    PAADM_DEPCODE_DR                                                      AS DEP_CODE_DR,
    PAADM_DISCHGDATE                                                      AS DISCHARGE_DATE,
    PAADM_DISCHGTIME                                                      AS DISCHARGE_TIME,
    PAADM_EXPADMDATE                                                      AS EXP_ADM_DATE,
    NULLIF(TRIM(PAADM_HASFUNDING), 'NULL')                                AS HAS_FUNDING,
    NULLIF(TRIM(PAADM_PATTYPE_DR), 'NULL')                                AS PAT_TYPE_DR,
    PAADM_REFSTAT_DR                                                      AS REF_STAT_DR,
    PAADM_REPORTDATE                                                      AS REPORT_DATE,
    PAADM_TEMPLOC_DR                                                      AS TEMP_LOC_DR,
    PAADM_TRIAGEDATE                                                      AS TRIAGE_DATE,
    PAADM_TRIAGETIME                                                      AS TRIAGE_TIME,
    PAADM_UPDATEDATE                                                      AS UPDATED_DATE,
    PAADM_UPDATETIME                                                      AS UPDATED_TIME,
    PAADM_ADMCATEG_DR                                                     AS ADM_CATEG_DR,
    PAADM_CAUSEINJ_DR                                                     AS CAUSE_INJ_DR,
    PAADM_CONVERTDATE                                                     AS CONVERT_DATE,
    PAADM_CONVERTTIME                                                     AS CONVERT_TIME,
    PAADM_DATEOFENTRY                                                     AS ENTRY_DATE,
    NULLIF(TRIM(PAADM_DELAYREASON), 'NULL')                               AS DELAY_REASON,
    PAADM_DIETTYPE_DR                                                     AS DIET_TYPE_DR,
    NULLIF(TRIM(PAADM_EMERGENCYNO), 'NULL')                               AS EMERGENCY_NO,
    PAADM_HOSPITAL_DR                                                     AS HOSPITAL_DR,
    PAADM_OESUBCAT_DR                                                     AS OE_SUB_CAT_DR,
    NULLIF(TRIM(PAADM_PREADMITTED), 'NULL')                               AS PRE_ADMITTED,
    PAADM_PRIORITY_DR                                                     AS PRIORITY_DR,
    NULLIF(TRIM(PAADM_REFAPPROVNO), 'NULL')                               AS REF_APPROVAL_NO,
    PAADM_ROOMTYPE_DR                                                     AS ROOM_TYPE_DR,
    NULLIF(TRIM(PAADM_SPECIFICLOC), 'NULL')                               AS SPECIFIC_LOC,
    PAADM_STATEPPP_DR                                                     AS STATE_PPP_DR,
    PAADM_TEMPLOCDATE                                                      AS TEMP_LOC_DATE,
    PAADM_TEMPLOCTIME                                                      AS TEMP_LOC_TIME,
    PAADM_TRANSFER_DR                                                     AS TRANSFER_DR,
    NULLIF(TRIM(PAADM_VISITSTATUS), 'NULL')                               AS VISIT_STATUS,
    PAADM_WAITLIST_DR                                                     AS WAIT_LIST_DR,
    NULLIF(TRIM(PAADM_ADMDOCCODEDR), 'NULL')                              AS ADM_DOC_CODE_DR,
    PAADM_ADMMETHOD_DR                                                    AS ADM_METHOD_DR,
    PAADM_ADMREASON_DR                                                    AS ADM_REASON_DR,
    NULLIF(TRIM(PAADM_ADMISSIONFIM), 'NULL')                              AS ADMISSION_FIM,
    PAADM_BARTHELSCORE                                                    AS BARTHEL_SCORE,
    NULLIF(TRIM(PAADM_BOOKLOCREADY), 'NULL')                              AS BOOK_LOC_READY,
    NULLIF(TRIM(PAADM_CHAPLAINNAME), 'NULL')                              AS CHAPLAIN_NAME,
    NULLIF(TRIM(PAADM_CONFIDENTIAL), 'NULL')                              AS CONFIDENTIAL,
    PAADM_DATERECEIVED                                                    AS DATE_RECEIVED,
    PAADM_DISCHCOND_DR                                                    AS DISCH_COND_DR,
    NULLIF(TRIM(PAADM_DISCHARGEFIM), 'NULL')                              AS DISCHARGE_FIM,
    NULLIF(TRIM(PAADM_DISCHGDOC_DR), 'NULL')                              AS DISCHARGE_DOC_DR,
    NULLIF(TRIM(PAADM_FAMILYDOCTOR), 'NULL')                              AS FAMILY_DOCTOR,
    PAADM_FINDISCHDATE                                                    AS FIN_DISCH_DATE,
    PAADM_FINDISCHTIME                                                    AS FIN_DISCH_TIME,
    NULLIF(TRIM(PAADM_INTERVIEWREC), 'NULL')                              AS INTERVIEW_REC,
    PAADM_MAINMRADM_DR                                                    AS MAIN_MR_ADM_DR,
    PAADM_MEDDISCHDATE                                                    AS MED_DISCH_DATE,
    PAADM_MEDDISCHTIME                                                    AS MED_DISCH_TIME,
    PAADM_METHODREF_DR                                                    AS METHOD_REF_DR,
    PAADM_MOTHERADM_DR                                                    AS MOTHER_ADM_DR,
    PAADM_NONGOVORG_DR                                                    AS NON_GOV_ORG_DR,
    PAADM_PATACUITY_DR                                                    AS PAT_ACUITY_DR,
    PAADM_PREADMITDATE                                                    AS PRE_ADMIT_DATE,
    PAADM_PREADMITTIME                                                    AS PRE_ADMIT_TIME,
    PAADM_PREGNANCY_DR                                                    AS PREGNANCY_DR,
    PAADM_REFCLINTO_DR                                                    AS REF_CLIN_TO_DR,
    PAADM_REFCLINIC_DR                                                    AS REF_CLINIC_DR,
    NULLIF(TRIM(PAADM_REFDOCCODEDR), 'NULL')                              AS REF_DOC_CODE_DR,
    NULLIF(TRIM(PAADM_REFDRCONSENT), 'NULL')                              AS REF_DR_CONSENT,
    PAADM_REFPERIOD_DR                                                    AS REF_PERIOD_DR,
    PAADM_REFERRALTYPE                                                    AS REFERRAL_TYPE_DR,
    PAADM_SOURCEREF_DR                                                    AS SOURCE_REF_DR,
    NULLIF(TRIM(PAADM_SPECIALTY_DR), 'NULL')                              AS SPECIALTY_DR,
    PAADM_TOILETING_DR                                                    AS TOILETING_DR,
    PAADM_APPTMETHOD_DR                                                   AS APPT_METHOD_DR,
    NULLIF(TRIM(PAADM_CHAPLAINPHONE), 'NULL')                             AS CHAPLAIN_PHONE,
    NULLIF(TRIM(PAADM_CURRENTBED_DR), 'NULL')                             AS CURRENT_BED_DR,
    PAADM_DATEDISCHHOSP                                                   AS DATE_DISCH_HOSP,
    PAADM_DATEFIRSTAPPT                                                   AS FIRST_APPT_DATE,
    NULLIF(TRIM(PAADM_DISCHCOMMENTS), 'NULL')                             AS DISCH_COMMENTS,
    PAADM_EDDBASEDONLMP                                                   AS EDD_BASED_ON_LMP,
    PAADM_EMERGENCYDATE                                                   AS EMERGENCY_DATE,
    PAADM_EMERGENCYTIME                                                   AS EMERGENCY_TIME,
    PAADM_ESTIMOPERDATE                                                   AS ESTIM_OPER_DATE,
    NULLIF(TRIM(PAADM_INTERVIEWEDBY), 'NULL')                             AS INTERVIEWED_BY,
    PAADM_OCCUPATION_DR                                                   AS OCCUPATION_DR,
    NULLIF(TRIM(PAADM_OTHERHOSPITAL), 'NULL')                             AS OTHER_HOSPITAL,
    PAADM_PARENTWARD_DR                                                   AS PARENT_WARD_DR,
    PAADM_PATCLASSIF_DR                                                   AS PAT_CLASSIF_DR,
    PAADM_PLACEOFINJ_DR                                                   AS PLACE_OF_INJ_DR,
    PAADM_REFDOCLIST_DR                                                   AS REF_DOC_LIST_DR,
    PAADM_REFEXPIRYDATE                                                   AS REF_EXPIRY_DATE,
    NULLIF(TRIM(PAADM_REFORGADDRESS), 'NULL')                             AS REF_ORG_ADDRESS,
    NULLIF(TRIM(PAADM_TREATINGDR_DR), 'NULL')                             AS TREATING_DR_DR,
    PAADM_UPDATEUSER_DR                                                   AS UPDATED_USER_DR,
    PAADM_USUALACCOM_DR                                                   AS USUAL_ACCOM_DR,
    PAADM_BEDMOBILITY_DR                                                  AS BED_MOBILITY_DR,
    NULLIF(TRIM(PAADM_CASEMANAGER_DR), 'NULL')                            AS CASE_MANAGER_DR,
    PAADM_CONVERTUSER_DR                                                  AS CONVERT_USER_DR,
    PAADM_CURRENTROOM_DR                                                  AS CURRENT_ROOM_DR,
    PAADM_CURRENTWARD_DR                                                  AS CURRENT_WARD_DR,
    NULLIF(TRIM(PAADM_DAYSURGERYTYPE), 'NULL')                            AS DAY_SURGERY_TYPE,
    NULLIF(TRIM(PAADM_DISCHGHOSPITAL), 'NULL')                            AS DISCHARGE_HOSPITAL,
    PAADM_EPISSUBTYPE_DR                                                  AS EPIS_SUB_TYPE_DR,
    NULLIF(TRIM(PAADM_FIRSTORREADMIS), 'NULL')                            AS FIRST_OR_READMIS,
    NULLIF(TRIM(PAADM_FLAGGEDPATIENT), 'NULL')                            AS FLAGGED_PATIENT,
    PAADM_HCPPRIORITY_DR                                                  AS HCP_PRIORITY_DR,
    PAADM_HUMANINTENT_DR                                                  AS HUMAN_INTENT_DR,
    NULLIF(TRIM(PAADM_MEALPREFERENCE), 'NULL')                            AS MEAL_PREFERENCE,
    NULLIF(TRIM(PAADM_MEDDISCHDOC_DR), 'NULL')                            AS MED_DISCH_DOC_DR,
    NULLIF(TRIM(PAADM_OTHERDISCHTYPE), 'NULL')                            AS OTHER_DISCH_TYPE,
    NULLIF(TRIM(PAADM_PATDESTINATION), 'NULL')                            AS PAT_DESTINATION,
    NULLIF(TRIM(PAADM_POLICEDIVISION), 'NULL')                            AS POLICE_DIVISION,
    PAADM_REFTONONGOV_DR                                                  AS REF_TO_NON_GOV_DR,
    PAADM_SERIOUSDISEASE                                                  AS SERIOUS_DISEASE,
    NULLIF(TRIM(PAADM_TRIAGENURSE_DR), 'NULL')                            AS TRIAGE_NURSE_DR,
    PAADM_CANCELREASON_DR                                                 AS CANCEL_REASON_DR,
    NULLIF(TRIM(PAADM_CONFIRMREFERRAL), 'NULL')                           AS CONFIRM_REFERRAL,
    NULLIF(TRIM(PAADM_CONSENTFEEDBACK), 'NULL')                           AS CONSENT_FEEDBACK,
    PAADM_CONTRACTROLE_DR                                                 AS CONTRACT_ROLE_DR,
    PAADM_CONTRACTTYPE_DR                                                 AS CONTRACT_TYPE_DR,
    PAADM_DATEHCPRECEIVED                                                 AS DATE_HCP_RECEIVED,
    PAADM_DATEOFINTERVIEW                                                 AS INTERVIEW_DATE,
    PAADM_DATEREFDECISION                                                 AS REF_DECISION_DATE,
    NULLIF(TRIM(PAADM_EMERGENCYSTATUS), 'NULL')                           AS EMERGENCY_STATUS,
    PAADM_INPATADMTYPE_DR                                                 AS INPAT_ADM_TYPE_DR,
    PAADM_INPATBEDREQDATE                                                 AS INPAT_BED_REQ_DATE,
    PAADM_INPATBEDREQTIME                                                 AS INPAT_BED_REQ_TIME,
    NULLIF(TRIM(PAADM_LIKELIHOODADMIT), 'NULL')                           AS LIKELIHOOD_ADMIT,
    NULLIF(TRIM(PAADM_OTHERINFECTTYPE), 'NULL')                           AS OTHER_INFECT_TYPE,
    NULLIF(TRIM(PAADM_OVERSEASVISITOR), 'NULL')                           AS OVERSEAS_VISITOR,
    PAADM_QUALIFSTATUS_DR                                                 AS QUALIF_STATUS_DR,
    PAADM_READMTOREHAB_DR                                                 AS READM_TO_REHAB_DR,
    PAADM_REASONNOTREGFEE                                                 AS REASON_NOT_REG_FEE,
    NULLIF(TRIM(PAADM_REFDOCCLINIC_DR), 'NULL')                           AS REF_DOC_CLINIC_DR,
    NULLIF(TRIM(PAADM_REGISTRATIONFEE), 'NULL')                           AS REGISTRATION_FEE,
    NULLIF(TRIM(PAADM_REJECTIONREASON), 'NULL')                           AS REJECTION_REASON,
    NULLIF(TRIM(PAADM_SPECIALCATEGORY), 'NULL')                           AS SPECIAL_CATEGORY,
    NULLIF(TRIM(PAADM_SPECIALDOCUMENT), 'NULL')                           AS SPECIAL_DOCUMENT,
    PAADM_STUDENTMRADM_DR                                                 AS STUDENT_MR_ADM_DR,
    NULLIF(TRIM(PAADM_TELEPHONEACTIVE), 'NULL')                           AS TELEPHONE_ACTIVE,
    PAADM_AEARRIVALMODE_DR                                                AS AE_ARRIVAL_MODE_DR,
    NULLIF(TRIM(PAADM_AUTOCODEREQUIRED), 'NULL')                          AS AUTO_CODE_REQUIRED,
    PAADM_BILLINGMETHOD_DR                                                AS BILLING_METHOD_DR,
    PAADM_CODINGUPDATEDATE                                                AS CODING_UPDATE_DATE,
    PAADM_CODINGUPDATETIME                                                AS CODING_UPDATE_TIME,
    NULLIF(TRIM(PAADM_CONFIDENTMESSAGE), 'NULL')                          AS CONFIDENT_MESSAGE,
    PAADM_CONTRACTSPOKE_DR                                                AS CONTRACT_SPOKE_DR,
    NULLIF(TRIM(PAADM_CONVERTEDFROMOUT), 'NULL')                          AS CONVERTED_FROM_OUT,
    PAADM_GUARANTEEADMDATE                                                AS GUARANTEE_ADM_DATE,
    PAADM_MAJORINCIDENT_DR                                                AS MAJOR_INCIDENT_DR,
    PAADM_MARITALSTATUS_DR                                                AS MARITAL_STATUS_DR,
    NULLIF(TRIM(PAADM_MEDICALDISCHARGE), 'NULL')                          AS MEDICAL_DISCHARGE,
    NULLIF(TRIM(PAADM_NURSINGNOTESFLAG), 'NULL')                          AS NURSING_NOTES_FLAG,
    PAADM_OSVISITSTATUS_DR                                                AS OS_VISIT_STATUS_DR,
    NULLIF(TRIM(PAADM_PATIENTCONTACTED), 'NULL')                          AS PATIENT_CONTACTED,
    NULLIF(TRIM(PAADM_SOCIALWORKERNAME), 'NULL')                          AS SOCIAL_WORKER_NAME,
    NULLIF(TRIM(PAADM_TRANSFERFACILITY), 'NULL')                          AS TRANSFER_FACILITY,
    PAADM_CURRENTPROCESS_DR                                               AS CURRENT_PROCESS_DR,
    NULLIF(TRIM(PAADM_DOCTORLETTERNOTES), 'NULL')                         AS DOCTOR_LETTER_NOTES,
    NULLIF(TRIM(PAADM_ESTDISCHCONFIRMED), 'NULL')                         AS EST_DISCH_CONFIRMED,
    NULLIF(TRIM(PAADM_INTERNALREFDOC_DR), 'NULL')                         AS INTERNAL_REF_DOC_DR,
    PAADM_INTERNALREFLOC_DR                                               AS INTERNAL_REF_LOC_DR,
    PAADM_LABOURACCIDENT_DR                                               AS LABOUR_ACCIDENT_DR,
    PAADM_LASTCONTACTFAMILY                                               AS LAST_CONTACT_FAMILY,
    PAADM_LIKELYTRANSICU_DR                                               AS LIKELY_TRANS_ICU_DR,
    PAADM_LOCALAUTHORITY_DR                                               AS LOCAL_AUTHORITY_DR,
    PAADM_OSVCOUNTRYFROM_DR                                               AS OSV_COUNTRY_FROM_DR,
    PAADM_PALLIATIVECARE_DR                                               AS PALLIATIVE_CARE_DR,
    NULLIF(TRIM(PAADM_PERMANENTRESIDENT), 'NULL')                         AS PERMANENT_RESIDENT,
    NULLIF(TRIM(PAADM_PERSONRESPPAYMENT), 'NULL')                         AS PERSON_RESP_PAYMENT,
    PAADM_REASONDELDISCH_DR                                               AS REASON_DEL_DISCH_DR,
    PAADM_SOURCEOFATTEND_DR                                               AS SOURCE_OF_ATTEND_DR,
    PAADM_ACTIVITYINJURED_DR                                              AS ACTIVITY_INJURED_DR,
    NULLIF(TRIM(PAADM_CONSENTRECFUNDINFO), 'NULL')                        AS CONSENT_REC_FUND_INFO,
    NULLIF(TRIM(PAADM_CONSENTWORKCOMPENS), 'NULL')                        AS CONSENT_WORK_COMPENS,
    NULLIF(TRIM(PAADM_CREATEPREADMISSION), 'NULL')                        AS CREATE_PRE_ADMISSION,
    PAADM_CURRENTRESOURCE_DR                                              AS CURRENT_RESOURCE_DR,
    PAADM_DATEHCPREQUESTSENT                                              AS DATE_HCP_REQUEST_SENT,
    PAADM_DAYSCARRIEDFORWARD                                              AS DAYS_CARRIED_FORWARD,
    PAADM_ESTIMDISCHARGEDATE                                              AS ESTIM_DISCHARGE_DATE,
    PAADM_ESTIMDISCHARGETIME                                              AS ESTIM_DISCHARGE_TIME,
    NULLIF(TRIM(PAADM_FREQUENTADMISSIONS), 'NULL')                        AS FREQUENT_ADMISSIONS,
    NULLIF(TRIM(PAADM_HASCOMMUNSOCWORKER), 'NULL')                        AS HAS_COMMUN_SOC_WORKER,
    PAADM_INJURYINCIDENTDATE                                              AS INJURY_INCIDENT_DATE,
    PAADM_MINIMENTALASSSCORE                                              AS MINI_MENTAL_ASS_SCORE,
    NULLIF(TRIM(PAADM_PATIENTLETTERNOTES), 'NULL')                        AS PATIENT_LETTER_NOTES,
    PAADM_POSTDISCHSTATUS_DR                                              AS POST_DISCH_STATUS_DR,
    PAADM_PREVIOUSPROCESS_DR                                              AS PREVIOUS_PROCESS_DR,
    PAADM_RBCCANCELREASON_DR                                              AS RBC_CANCEL_REASON_DR,
    PAADM_SECONDARYREASON_DR                                              AS SECONDARY_REASON_DR,
    PAADM_TRAFFICACCIDENT_DR                                              AS TRAFFIC_ACCIDENT_DR,
    PAADM_TUMOURSITEGROUP_DR                                              AS TUMOUR_SITE_GROUP_DR,
    PAADM_APPOINTTRANSPORT_DR                                             AS APPT_TRANSPORT_DR,
    NULLIF(TRIM(PAADM_AUDITLETTERRESPONSE), 'NULL')                       AS AUDIT_LETTER_RESPONSE,
    PAADM_CODINGUPDATEUSER_DR                                             AS CODING_UPDATE_USER_DR,
    NULLIF(TRIM(PAADM_CONSENTDEPOFDEFENCE), 'NULL')                       AS CONSENT_DEP_OF_DEFENCE,
    NULLIF(TRIM(PAADM_CONSENTMOTORVEHICLE), 'NULL')                       AS CONSENT_MOTOR_VEHICLE,
    NULLIF(TRIM(PAADM_DISCHARGEAPPOINT_DR), 'NULL')                       AS DISCHARGE_APPOINT_DR,
    PAADM_MATERNITYVISTYPE_DR                                             AS MATERNITY_VIS_TYPE_DR,
    PAADM_ORIGINALADMISSIONDR                                             AS ORIGINAL_ADMISSION_DR,
    NULLIF(TRIM(PAADM_REFTONGOCONTACTNAME), 'NULL')                       AS REF_TO_NGO_CONTACT_NAME,
    PAADM_REFERRALPRIORITY_DR                                             AS REFERRAL_PRIORITY_DR,
    NULLIF(TRIM(PAADM_SHOWINFUTUREEPISODE), 'NULL')                       AS SHOW_IN_FUTURE_EPISODE,
    NULLIF(TRIM(PAADM_HOSPCHAPLAINVISITREQ), 'NULL')                      AS HOSP_CHAPLAIN_VISIT_REQ,
    NULLIF(TRIM(PAADM_LABCLINICALCONDITION), 'NULL')                      AS LAB_CLINICAL_CONDITION,
    PAADM_LOCATIONATTELEHEALTH                                            AS LOCATION_AT_TELEHEALTH,
    NULLIF(TRIM(PAADM_OWNMINISTERINDICATOR), 'NULL')                      AS OWN_MINISTER_INDICATOR,
    PAADM_SERVICETYPEOUTLET_DR                                            AS SERVICE_TYPE_OUTLET_DR,
    PAADM_SUSPECTCANCERTYPE_DR                                            AS SUSPECT_CANCER_TYPE_DR,
    NULLIF(TRIM(PAADM_TYPE_OF_PATIENT_CALC), 'NULL')                      AS TYPE_OF_PATIENT_CALC,
    NULLIF(TRIM(PAADM_VIEWABLEBYEPCAREPROV), 'NULL')                      AS VIEWABLE_BY_EP_CARE_PROV,
    NULLIF(TRIM(PAADM_CHAPLAINCHURCHADDRESS), 'NULL')                     AS CHAPLAIN_CHURCH_ADDRESS,
    PAADM_CLINICALSUBPROGRAM_DR                                           AS CLINICAL_SUB_PROGRAM_DR,
    NULLIF(TRIM(PAADM_CONSENTPATSATISFSURVE), 'NULL')                     AS CONSENT_PAT_SATISF_SURVE,
    PAADM_DATEPATREFFEREDASSESS                                           AS DATE_PAT_REFFERED_ASSESS,
    PAADM_DATESOCIALWORKERALLOC                                           AS DATE_SOCIAL_WORKER_ALLOC,
    PAADM_DISCHARGEBARTHELSCORE                                           AS DISCHARGE_BARTHEL_SCORE,
    PAADM_FUNDINGARRANGEMENT_DR                                           AS FUNDING_ARRANGEMENT_DR,
    PAADM_SOCIALWORKERCENTRE_DR                                           AS SOCIAL_WORKER_CENTRE_DR,
    NULLIF(TRIM(PAADM_TERMINOLOGYINJURYCODE), 'NULL')                     AS TERMINOLOGY_INJURY_CODE,
    NULLIF(TRIM(PAADM_TERMINOLOGYINJURYDESC), 'NULL')                     AS TERMINOLOGY_INJURY_DESC,
    PAADM_UPDATEUSERHOSPITAL_DR                                           AS UPDATE_USER_HOSPITAL_DR,
    NULLIF(TRIM(PAADM_PAIDEMERGENCYSURCHARGE), 'NULL')                    AS PAID_EMERGENCY_SURCHARGE,
    NULLIF(TRIM(PAADM_TERMCHIEFCOMPLAINTCODE), 'NULL')                    AS TERM_CHIEF_COMPLAINT_CODE,
    NULLIF(TRIM(PAADM_TERMCHIEFCOMPLAINTDESC), 'NULL')                    AS TERM_CHIEF_COMPLAINT_DESC,
    PAADM_APPOINTBOOKINGSYSTEM_DR                                         AS APPT_BOOKING_SYSTEM_DR,
    PAADM_DATEASSESSMENTCOMPLETED                                         AS DATE_ASSESSMENT_COMPLETED,
    PAADM_PERSONRESPONSIBLEPAYMENT                                        AS PERSON_RESPONSIBLE_PAYMENT,
    PAADM_DATESOCIALWORKERCOMPLETED                                       AS DATE_SOCIAL_WORKER_COMPLETED,
    NULLIF(TRIM(PAADM_TERMINOLOGYINJURYSELECTED), 'NULL')                 AS TERMINOLOGY_INJURY_SELECTED,
    NULLIF(TRIM(PAADM_PREVINPATADMPALLIATIVECARE), 'NULL')                AS PREV_INPAT_ADM_PALLIATIVE_CARE,
    NULLIF(TRIM(PAADM_PREVNONINPATPALLIATIVECARE), 'NULL')                AS PREV_NON_INPAT_PALLIATIVE_CARE,
    NULLIF(TRIM(PAADM_TERMCHIEFCOMPLAINTSELECTED), 'NULL')                AS TERM_CHIEF_COMPLAINT_SELECTED,
    PAADM_LMP                                                             AS LMP,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_PA_ADM') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')