SELECT
    SER_ROWID                                                             AS ROW_ID,
    NULLIF(TRIM(SER_ARCIM_DR), 'NULL')                                    AS ARCIM_DR,
    NULLIF(TRIM(SER_ARCOS_DR), 'NULL')                                    AS ARCOS_DR,
    SER_NOOFSLOTS                                                         AS NO_OF_SLOTS,
    NULLIF(TRIM(SER_CTCP_DR), 'NULL')                                     AS CT_CP_DR,
    NULLIF(TRIM(SER_EQUIP_DR), 'NULL')                                    AS EQUIP_DR,
    NULLIF(TRIM(SER_DESC), 'NULL')                                        AS DESCRIPTION,
    NULLIF(TRIM(SER_CTLOC_DR), 'NULL')                                    AS CT_LOC_DR,
    NULLIF(TRIM(SER_MINUTES), 'NULL')                                     AS MINUTES,
    NULLIF(TRIM(SER_SERVGROUP_DR), 'NULL')                                AS SERV_GROUP_DR,
    NULLIF(TRIM(SER_ACTIVE), 'NULL')                                      AS ACTIVE,
    NULLIF(TRIM(SER_SUBCATEGORYDR), 'NULL')                               AS SUB_CATEGORY_DR,
    NULLIF(TRIM(SER_DATEFROM), 'NULL')                                    AS DATE_FROM,
    NULLIF(TRIM(SER_DATETO), 'NULL')                                      AS DATE_TO,
    NULLIF(TRIM(SER_1STAPPT), 'NULL')                                     AS FIRST_APPT,
    NULLIF(TRIM(SER_PROJECTEDWEEKSWAIT), 'NULL')                          AS PROJECTED_WEEKS_WAIT,
    NULLIF(TRIM(SER_AVERAGEWEEKSPYEAR), 'NULL')                           AS AVERAGE_WEEKS_PER_YEAR,
    NULLIF(TRIM(SER_FIRSTAVAILABLE), 'NULL')                              AS FIRST_AVAILABLE,
    NULLIF(TRIM(SER_EXTRACONTACTPATIENTSPERC), 'NULL')                    AS EXTRA_CONTACT_PATIENTS_PERC,
    NULLIF(TRIM(SER_PFB), 'NULL')                                         AS PFB,
    NULLIF(TRIM(SER_CALCPROJECTEDWAIT), 'NULL')                           AS CALC_PROJECTED_WAIT,
    NULLIF(TRIM(SER_NEWWAYS), 'NULL')                                     AS NEW_WAYS,
    NULLIF(TRIM(SER_DRESSTIME), 'NULL')                                   AS DRESS_TIME,
    TRY_TO_DATE(NULLIF(TRIM(SER_CREATEDDATE), 'NULL'))                    AS CREATED_DATE,
    NULLIF(TRIM(SER_CREATEDTIME), 'NULL')                                 AS CREATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(SER_CREATEDUSER_DR), 'NULL'), 18, 6)        AS CREATED_USER_DR,
    TRY_TO_DATE(NULLIF(TRIM(SER_UPDATEDDATE), 'NULL'))                    AS UPDATED_DATE,
    NULLIF(TRIM(SER_UPDATEDTIME), 'NULL')                                 AS UPDATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(SER_UPDATEDUSER_DR), 'NULL'), 18, 6)        AS UPDATED_USER_DR,
    NULLIF(TRIM(SER_DESCTRANSLATED), 'NULL')                              AS DESC_TRANSLATED,
    SER_ROWIDTRANSLATED                                                   AS ROW_ID_TRANSLATED

FROM {{ ref('HIST_TRAKCARE_RBC_SERVICES') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')