SELECT
    TRIM(FPM)                                     AS FPM,
    {{ format_name('SITE') }}                      AS SITE,
    TRIM(PRICE)                                    AS PRICE,
    TRIM(ABSENT)                                   AS ABSENT,
    TRIM(FUNDING)                                  AS FUNDING,
    TRIM(PROGRAM)                                  AS PROGRAM,
    TRIM(SERVICE)                                  AS SERVICE,
    TRIM(QUANTITY)                                 AS QUANTITY,
    TRIM(BPR_ID)                                   AS BPR_ID,
    TRIM(CLIENT_ID)                                AS SUPPORTABILITY_CLIENT_ID,
    TRIM(COST_TYPE)                                AS COST_TYPE,
    TRIM(DEBTOR_ID)                                AS DEBTOR_ID,
    TRIM(NO_CHARGE)                                AS NO_CHARGE,
    TRIM(CLAIM_TYPE)                                AS CLAIM_TYPE,
    TRIM(ACTIVITY_ID)                              AS ACTIVITY_ID,
    TRIM(NDIS_NUMBER)                              AS NDIS_NO,
    TRIM(CLAIM_STATUS)                             AS CLAIM_STATUS,
    {{ format_date('INVOICE_DATE') }}              AS INVOICE_DATE,
    {{ format_name('ACTIVITY_NAME') }}             AS ACTIVITY_NAME,
    TRIM(AGENCY_CAPPED)                            AS AGENCY_CAPPED,
    TRIM(CLAIMED_PRICE)                            AS CLAIMED_PRICE,
    TRIM(FINANCE_NOTES)                            AS FINANCE_NOTES,
    TRIM(PRICE_PORTION)                            AS PRICE_PORTION,
    {{ format_name('STAFF_MEMBERS') }}             AS STAFF_MEMBERS,
    TRIM(ACTIVITY_HOURS)                           AS ACTIVITY_HOURS,
    {{ format_name('CLIENT_SURNAME') }}            AS LAST_NAME,
    TRIM(INVOICE_NUMBER)                           AS INVOICE_NO,
    TRIM(OUTCOME_DOMAIN)                           AS OUTCOME_DOMAIN,
    TRIM(VALUE_INCL_GST)                           AS VALUE_INCL_GST,
    TRIM(SUPPORT_PURPOSE)                          AS SUPPORT_PURPOSE,
    TRIM(UNIT_OF_MEASURE)                          AS MEASURE_UNIT,
    {{ format_date('ACTIVITY_TO_DATE') }}          AS ACTIVITY_TO_DATE,
    {{ format_date('BPRF_UPLOAD_DATE') }}          AS BPRF_UPLOAD_DATE,
    TRIM(CLIENT_DEBTOR_ID)                         AS CLIENT_DEBTOR_ID,
    {{ format_date('FUNDING_END_DATE') }}          AS FUNDING_END_DATE,
    TRIM(INVOICE_BATCH_ID)                         AS INVOICE_BATCH_ID,
    TRIM(SUPPORT_CATEGORY)                         AS SUPPORT_CATEGORY,
    {{ format_name('ACTIVITY_LOCATION') }}         AS ACTIVITY_LOCATION,
    {{ format_date('BPR_CREATION_DATE') }}         AS BPR_CREATION_DATE,
    {{ format_name('CLIENT_FIRST_NAME') }}         AS FIRST_NAME,
    TRIM(CLIENT_FUNDING_ID)                        AS CLIENT_FUNDING_ID,
    TRIM(PROCESSING_STATUS)                        AS PROCESSING_STATUS,
    TRIM(START_DAY_OF_WEEK)                        AS WEEK_START_DAY,
    TRIM(SUPPORT_ITEM_NAME)                        AS SUPPORT_ITEM_NAME,
    {{ format_date('FUNDING_START_DATE') }}        AS FUNDING_START_DATE,
    TRIM(PROGRAM_OF_SUPPORT)                       AS SUPPORT_PROGRAM,
    TRIM(REGISTRATION_GROUP)                       AS REGISTRATION_GROUP,
    TRIM(NDIA_REJECTED_REASON)                     AS NDIA_REJECTED_REASON,
    {{ format_date('ACTIVITY_SIGN_OFF_DATE') }}    AS ACTIVITY_SIGN_OFF_DATE,
    TRIM(CLAIM_REFERENCE_NUMBER)                   AS CLAIM_REF_NO,
    TRIM(CLAIMED_VALUE_INCL_GST)                   AS CLAIMED_VALUE_INCL_GST,
    TRIM(SUPPORT_ITEM_REFERENCE)                   AS SUPPORT_ITEM_REF,
    {{ format_date('CLIENT_SUPPORT_LOG_DATE') }}   AS CLIENT_SUPPORT_LOG_DATE,
    {{ format_date('ACTIVITY_FROM_DATE') }}        AS ACTIVITY_FROM_DATE,
    TRIM(NOTIONAL_UNIT_PRICE_SUPPORT)              AS NOTIONAL_UNIT_PRICE_SUPPORT,
    TRIM(CLIENT_FUNDING_ON_BILLING_HOLD)           AS CLIENT_FUNDING_ON_BILLING_HOLD,
    TRIM(SHORT_NOTICE_CANCELLATION_REASON)         AS SHORT_NOTICE_CANCEL_REASON,
    TRIM(CLIENT_FUNDING_ON_BILLING_HOLD_BY)        AS CLIENT_FUNDING_ON_BILLING_HOLD_BY,
    TRIM(SUPPORTABILITY_CLIENT_CUSTOMER_ID)        AS SUPPORTABILITY_CLIENT_CUSTOMER_ID,
    TRIM(SUPPORTABILITY_DEBTOR_CUSTOMER_ID)        AS SUPPORTABILITY_DEBTOR_CUSTOMER_ID,
    TRIM(CLIENT_FUNDING_ON_BILLING_HOLD_SINCE)     AS CLIENT_FUNDING_ON_BILLING_HOLD_SINCE,

    _AIRBYTE_EXTRACTED_AT                           AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_SUPPORTABILITY_ALLOCATIONS_REPORT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')