SELECT
    {{ format_name('LASTNAME') }}          AS LAST_NAME,
    TRIM(USERNAME)                         AS USER_NAME,
    {{ format_name('FIRSTNAME') }}         AS FIRST_NAME,
    CAST(HOURSWORKED AS INT)               AS WORKED_HOURS,
    {{ format_name('ACTIVITYNAME') }}      AS ACTIVITY_NAME,
    CAST(DATABASEUSERID AS TEXT)           AS BETTER_IMPACT_USER_ID,
    CAST(DATEVOLUNTEERED AS DATE)          AS VOLUNTEERED_DATE,

    CAST(FF_NO_OF_VISITS AS TEXT)          AS FF_NO_OF_VISITS,
    TRIM(FF_TYPE_OF_VISIT)                 AS FF_VISIT_TYPE,
    {{ format_name('ACTIVITYCATEGORYNAME') }} AS ACTIVITY_CATEGORY_NAME,
    TRIM(FF_CLIENT_CONCERNS)               AS FF_CONCERNS_1,
    TRIM(FF_MATCH_END_REASON)              AS FF_MATCH_END_REASON,
    {{ format_name('FF_NAME_OF_RESIDENT') }} AS FF_RESIDENT_NAME,
    TRIM(FF_GOOD_NEWS_STORIES)             AS FF_GOOD_NEWS_STORIES_1,
    {{ format_name('ACTIVITYREPORTGROUPNAME') }} AS ACTIVITY_REPORT_GROUP_NAME,
    TRIM(FF_CLIENT_CONCERNS_1)             AS FF_CONCERNS_2,
    TRIM(FF_GOOD_NEWS_STORIES_1)           AS FF_GOOD_NEWS_STORIES_2,
    TRIM(FF_IF_NO_VISITS_WERE_MADE_PLEASE_INDICATE_REASON) AS FF_REASON_FOR_NO_VISITS,
    CAST(FF_HMS AS TEXT)                   AS FF_KMS,

    _AIRBYTE_EXTRACTED_AT                   AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_BETTER_IMPACT_PIVOTED_FEEDBACK_REPORT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')