SELECT
    REA_ROWID                                             AS ROW_ID,
    NULLIF(TRIM(REA_CODE), 'NULL')                        AS CODE,
    NULLIF(TRIM(REA_DESC), 'NULL')                        AS DESCRIPTION,
    REA_AGETO                                             AS AGE_TO,
    NULLIF(TRIM(REA_OWNER), 'NULL')                       AS OWNER,
    REA_AGE1TO                                            AS AGE_1_TO,
    REA_DATETO                                            AS DATE_TO,
    REA_AGEFROM                                           AS AGE_FROM,
    NULLIF(TRIM(REA_AGETYPE), 'NULL')                     AS AGE_TYPE,
    REA_AGE1FROM                                          AS AGE_1_FROM,
    NULLIF(TRIM(REA_AGE1TYPE), 'NULL')                    AS AGE_1_TYPE,
    NULLIF(TRIM(REA_CARETYPE), 'NULL')                    AS CARE_TYPE,
    REA_DATEFROM                                          AS DATE_FROM,
    NULLIF(TRIM(REA_ADMSOURCE), 'NULL')                   AS ADM_SOURCE,
    NULLIF(TRIM(REA_EMERGENCY), 'NULL')                   AS EMERGENCY,
    NULLIF(TRIM(REA_INPATIENT), 'NULL')                   AS INPATIENT,
    NULLIF(TRIM(REA_OUTPATIENT), 'NULL')                  AS OUTPATIENT,
    REA_CREATEDDATE                                       AS CREATED_DATE,
    REA_CREATEDTIME                                       AS CREATED_TIME,
    NULLIF(TRIM(REA_EPISSUBTYPE), 'NULL')                 AS EPIS_SUBTYPE,
    NULLIF(TRIM(REA_INPATADM_DR), 'NULL')                 AS INPAT_ADM_DR,
    REA_UPDATEDDATE                                       AS UPDATED_DATE,
    REA_UPDATEDTIME                                       AS UPDATED_TIME,
    NULLIF(TRIM(REA_NATIONALCODE), 'NULL')                AS NATIONAL_CODE,
    NULLIF(TRIM(REA_QUALIFSTATUS), 'NULL')                AS QUALIF_STATUS,
    REA_SUBREGION_DR                                      AS SUB_REGION_DR,
    NULLIF(TRIM(REA_CODETABLETAGS), 'NULL')               AS CODE_TABLE_TAGS,
    REA_CREATEDUSER_DR                                    AS CREATED_USER_DR,
    REA_UPDATEDUSER_DR                                    AS UPDATED_USER_DR,
    _AIRBYTE_EXTRACTED_AT                                 AS AIRBYTE_EXTRACTED_TS
FROM {{ ref('HIST_TRAKCARE_PAC_ADMREASON') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')