SELECT
    MRADM_ROWID                                                           AS ROW_ID,
    MRADM_ADM_DR                                                          AS ADM_DR,
    MRADM_DATE                                                            AS ADM_DATE,
    MRADM_TIME                                                            AS ADM_TIME,
    MRADM_DISCHARGEDATE                                                   AS DISCHARGE_DATE,
    MRADM_DISCHCLASSIF_DR                                                 AS DISCH_CLASSIF_DR,
    MRADM_DISCHTYPE_DR                                                    AS DISCH_TYPE_DR,
    MRADM_DISCHDESTIN_DR                                                  AS DISCH_DESTIN_DR,
    MRADM_DISCHTRANSFER_DR                                                AS DISCH_TRANSFER_DR,
    MRADM_DISCHTRANSPORT_DR                                               AS DISCH_TRANSPORT_DR,
    MRADM_DISCHTOILETING_DR                                               AS DISCH_TOILETING_DR,
    MRADM_DISCHBEDMOBILITY_DR                                             AS DISCH_BED_MOBILITY_DR,
    MRADM_DISCHEATING_DR                                                  AS DISCH_EATING_DR,
    MRADM_DISCHPALLCARE_DR                                                AS DISCH_PALL_CARE_DR,
    NULLIF(TRIM(MRADM_PRESENTCOMPLAINT), 'NULL')                          AS PRESENTING_COMPLAINT,
    NULLIF(TRIM(MRADM_REMARKS), 'NULL')                                   AS REMARKS,
    NULLIF(TRIM(MRADM_OBJECTIVE), 'NULL')                                 AS OBJECTIVE,
    NULLIF(TRIM(MRADM_SUBJECTIVE), 'NULL')                                AS SUBJECTIVE,
    NULLIF(TRIM(MRADM_GPCONSENT), 'NULL')                                 AS GP_CONSENT,
    MRADM_REFERREDTO_DR                                                   AS REFERRED_TO_DR,
    MRADM_TRANSFDEST_DR                                                   AS TRANSF_DEST_DR,
    MRADM_TRANSDEST2_DR                                                   AS TRANS_DEST_2_DR,
    MRADM_REASONTRANSFER_DR                                               AS REASON_TRANSFER_DR,
    NULLIF(TRIM(MRADM_OTHERTRANSFERREASON), 'NULL')                       AS OTHER_TRANSFER_REASON,
    MRADM_CARETYPE_DR                                                     AS CARE_TYPE_DR,
    MRADM_CARERAVAIL_DR                                                   AS CARER_AVAIL_DR,
    MRADM_ADMROUTE_DR                                                     AS ADM_ROUTE_DR,
    MRADM_ACTIVITY_DR                                                     AS ACTIVITY_DR,
    MRADM_TRAFFIC_DR                                                      AS TRAFFIC_DR,
    MRADM_CONSCSTATE_DR                                                   AS CONSC_STATE_DR,
    MRADM_PATCOND_DR                                                      AS PAT_COND_DR,
    MRADM_PATCONDDATE                                                     AS PAT_COND_DATE,
    MRADM_PATCONDTIME                                                     AS PAT_COND_TIME,
    MRADM_CONDITATDISCH_DR                                                AS CONDIT_AT_DISCH_DR,
    MRADM_RISKOFMORTALITY_DR                                              AS RISK_OF_MORTALITY_DR,
    MRADM_FUNDINGARRANG_DR                                                AS FUNDING_ARRANG_DR,
    MRADM_PROGRFUNDSOURCE_DR                                              AS PROGR_FUND_SOURCE_DR,
    MRADM_MENTHEALTHSTAT_DR                                               AS MENT_HEALTH_STAT_DR,
    MRADM_DRG_DR                                                          AS DRG_DR,
    NULLIF(TRIM(MRADM_DRGCODINGWEIGHT), 'NULL')                           AS DRG_CODING_WEIGHT,
    MRADM_DRGWEIGHT                                                       AS DRG_WEIGHT,
    MRADM_DRGTARIFF                                                       AS DRG_TARIFF,
    MRADM_DRGPROCESSTIMES                                                 AS DRG_PROCESS_TIMES,
    MRADM_DRGSTATUTORY_DR                                                 AS DRG_STATUTORY_DR,
    MRADM_DRGGROUPERVERSION_DR                                            AS DRG_GROUPER_VERSION_DR,
    MRADM_DRGGROUPERVERSIONSTATUTORY_DR                                   AS DRG_GROUPER_VERSION_STATUTORY_DR,
    NULLIF(TRIM(MRADM_DRGFREETEXT1), 'NULL')                              AS DRG_FREE_TEXT_1,
    NULLIF(TRIM(MRADM_DRGFREETEXT2), 'NULL')                              AS DRG_FREE_TEXT_2,
    NULLIF(TRIM(MRADM_DRGFREETEXT3), 'NULL')                              AS DRG_FREE_TEXT_3,
    NULLIF(TRIM(MRADM_DRGFREETEXT4), 'NULL')                              AS DRG_FREE_TEXT_4,
    NULLIF(TRIM(MRADM_DRGGENLOOKUP1), 'NULL')                             AS DRG_GEN_LOOKUP_1,
    NULLIF(TRIM(MRADM_DRGGENLOOKUP2), 'NULL')                             AS DRG_GEN_LOOKUP_2,
    MRADM_DRGGENFLOAT1                                                    AS DRG_GEN_FLOAT_1,
    MRADM_DRGGENFLOAT2                                                    AS DRG_GEN_FLOAT_2,
    MRADM_DRGGENINTEGER1                                                  AS DRG_GEN_INTEGER_1,
    MRADM_DRGGENINTEGER2                                                  AS DRG_GEN_INTEGER_2,
    MRADM_PCCL                                                            AS PCCL,
    MRADM_CCUHOURS                                                        AS CCU_HOURS,
    MRADM_ICUHOURS                                                        AS ICU_HOURS,
    MRADM_CPAPHOURS                                                       AS CPAP_HOURS,
    MRADM_DURATIONMECHVENT                                                AS DURATION_MECH_VENT,
    MRADM_NUMBEROFDAYS                                                    AS NUMBER_OF_DAYS,
    MRADM_HIGHOUTLIERDAYS                                                 AS HIGH_OUTLIER_DAYS,
    MRADM_GLASGOWCOMASCORE                                                AS GLASGOW_COMA_SCORE,
    MRADM_PAINSCORE                                                       AS PAIN_SCORE,
    NULLIF(TRIM(MRADM_PAINRANGE), 'NULL')                                 AS PAIN_RANGE,
    NULLIF(TRIM(MRADM_HEIGHT), 'NULL')                                    AS HEIGHT,
    MRADM_HEIGHTUOM_DR                                                    AS HEIGHT_UOM_DR,
    MRADM_DATEHEIGHT                                                      AS DATE_HEIGHT,
    NULLIF(TRIM(MRADM_WEIGHT), 'NULL')                                    AS WEIGHT,
    MRADM_WEIGHTUOM_DR                                                    AS WEIGHT_UOM_DR,
    MRADM_DATEWEIGHT                                                      AS DATE_WEIGHT,
    NULLIF(TRIM(MRADM_PULSERATE), 'NULL')                                 AS PULSE_RATE,
    NULLIF(TRIM(MRADM_BPSYSTOLIC), 'NULL')                                AS BP_SYSTOLIC,
    NULLIF(TRIM(MRADM_BPDIASTOLIC), 'NULL')                               AS BP_DIASTOLIC,
    NULLIF(TRIM(MRADM_TEMP), 'NULL')                                      AS TEMP,
    NULLIF(TRIM(MRADM_RESP), 'NULL')                                      AS RESP,
    NULLIF(TRIM(MRADM_OXYGENSATURATION), 'NULL')                          AS OXYGEN_SATURATION,
    MRADM_SERUMCREATININE                                                 AS SERUM_CREATININE,
    MRADM_DATESERUMCREATININE                                             AS DATE_SERUM_CREATININE,
    NULLIF(TRIM(MRADM_BLOODSUGARTESTRESULT), 'NULL')                      AS BLOOD_SUGAR_TEST_RESULT,
    NULLIF(TRIM(MRADM_URINESUGARTESTRESULT), 'NULL')                      AS URINE_SUGAR_TEST_RESULT,
    NULLIF(TRIM(MRADM_HEADCIRCUMFERENCE), 'NULL')                         AS HEAD_CIRCUMFERENCE,
    NULLIF(TRIM(MRADM_WAISTCIRCUMFERENCE), 'NULL')                        AS WAIST_CIRCUMFERENCE,
    NULLIF(TRIM(MRADM_VISIONSCORELEFT), 'NULL')                           AS VISION_SCORE_LEFT,
    NULLIF(TRIM(MRADM_VISIONSCORERIGHT), 'NULL')                          AS VISION_SCORE_RIGHT,
    MRADM_ONSETDATE                                                       AS ONSET_DATE,
    NULLIF(TRIM(MRADM_INJURYDESC), 'NULL')                                AS INJURY_DESC,
    MRADM_CODER_DR                                                        AS CODER_DR,
    MRADM_CODINGUPDATEDATE                                                AS CODING_UPDATE_DATE,
    MRADM_CODINGUPDATETIME                                                AS CODING_UPDATE_TIME,
    MRADM_CODINGUPDATEUSER_DR                                             AS CODING_UPDATE_USER_DR,
    MRADM_CODINGUPDATEHOSPITAL_DR                                         AS CODING_UPDATE_HOSPITAL_DR,
    MRADM_PMUPDATEDATE                                                    AS PM_UPDATE_DATE,
    MRADM_PMUPDATETIME                                                    AS PM_UPDATE_TIME,
    MRADM_PMUPDATEUSER_DR                                                 AS PM_UPDATE_USER_DR,
    MRADM_PMUPDATEHOSPITAL_DR                                             AS PM_UPDATE_HOSPITAL_DR,
    MRADM_PATINQUPDATEDATE                                                AS PAT_INQ_UPDATE_DATE,
    MRADM_PATINQUPDATETIME                                                AS PAT_INQ_UPDATE_TIME,
    MRADM_PATINQUPDUSER_DR                                                AS PAT_INQ_UPD_USER_DR,
    MRADM_PATINQUPDUSERHOSP_DR                                            AS PAT_INQ_UPD_USER_HOSP_DR,
    NULLIF(TRIM(MRADM_SEPARATIONREFERRAL_DR), 'NULL')                     AS SEPARATION_REFERRAL_DR,
    NULLIF(TRIM(MRADM_SPECIALINSTR), 'NULL')                              AS SPECIAL_INSTR,
    NULLIF(TRIM(MRADM_DIETCOMMENTS), 'NULL')                              AS DIET_COMMENTS,
    NULLIF(TRIM(MRADM_PATIENTREQUIREMENTS), 'NULL')                       AS PATIENT_REQUIREMENTS,
    NULLIF(TRIM(MRADM_PREHOSPTREATMENT), 'NULL')                          AS PRE_HOSP_TREATMENT,
    MRADM_REFBOOKDATE                                                     AS REF_BOOK_DATE,
    MRADM_REFCLIN_DR                                                      AS REF_CLIN_DR,
    MRADM_ACAS_DR                                                         AS ACAS_DR,
    MRADM_TUMOR_DR                                                        AS TUMOR_DR,
    MRADM_BLOODTYPE_DR                                                    AS BLOOD_TYPE_DR,
    MRADM_AUTOPSYTYPE_DR                                                  AS AUTOPSY_TYPE_DR,
    MRADM_INTENTREADMIT_DR                                                AS INTENT_READMIT_DR,
    MRADM_UNPLANREADMISSION_DR                                            AS UNPLAN_READMISSION_DR,
    MRADM_ADMREADMREHAB_DR                                                AS ADM_READM_REHAB_DR,
    MRADM_GROUPERSTATUS_DR                                                AS GROUPER_STATUS_DR,
    MRADM_WOUNDTYPE_DR                                                    AS WOUND_TYPE_DR,
    MRADM_DRAINTUBES_DR                                                   AS DRAIN_TUBES_DR,
    MRADM_ISOLATION_DR                                                    AS ISOLATION_DR,
    MRADM_INFECTTYPE_DR                                                   AS INFECT_TYPE_DR,
    MRADM_IVTHERAPY_DR                                                    AS IV_THERAPY_DR,
    MRADM_OVERNIGHT_DR                                                    AS OVERNIGHT_DR,
    MRADM_MATERTYPE_DR                                                    AS MATER_TYPE_DR,
    MRADM_VISITTYPE_DR                                                    AS VISIT_TYPE_DR,
    MRADM_PROGRESS_DR                                                     AS PROGRESS_DR,
    MRADM_DEGREEPROGRESSION_DR                                            AS DEGREE_PROGRESSION_DR,
    MRADM_WORKINGDIAGNOSIS_DR                                             AS WORKING_DIAGNOSIS_DR,
    MRADM_OTHERCONDITIONS_DR                                              AS OTHER_CONDITIONS_DR,
    MRADM_VISITORSTATUS_DR                                                AS VISITOR_STATUS_DR,
    MRADM_VENTILATION_DR                                                  AS VENTILATION_DR,
    MRADM_ESCORTSOURCE_DR                                                 AS ESCORT_SOURCE_DR,
    MRADM_TRANSFERMEANS_DR                                                AS TRANSFER_MEANS_DR,
    MRADM_CONSCSTATE_DR                                                   AS CONSC_STATE_2_DR,
    MRADM_REASONCRITCARETRANS_DR                                          AS REASON_CRIT_CARE_TRANS_DR,
    MRADM_REASONFORREVFINDISCH_DR                                         AS REASON_FOR_REV_FIN_DISCH_DR,
    MRADM_DISCHREASONBEDUNAVAIL_DR                                        AS DISCH_REASON_BED_UNAVAIL_DR,
    MRADM_SOURCEREFERRALPALCARE_DR                                        AS SOURCE_REFERRAL_PAL_CARE_DR,
    MRADM_CONTRSPOKEIDENTIF_DR                                            AS CONTR_SPOKE_IDENTIF_DR,
    MRADM_ACCOUNTCLASS_DR                                                 AS ACCOUNT_CLASS_DR,
    MRADM_DRGCODINGWEIGHTUOM_DR                                           AS DRG_CODING_WEIGHT_UOM_DR,
    NULLIF(TRIM(MRADM_HEALTHSPECCODE_DR), 'NULL')                         AS HEALTH_SPEC_CODE_DR,
    MRADM_PACSDISCHARGEDATE                                               AS PACS_DISCHARGE_DATE,
    MRADM_CAREPLANSTARTDATE                                               AS CARE_PLAN_START_DATE,
    MRADM_CAREPLANENDDATE                                                 AS CARE_PLAN_END_DATE,
    MRADM_CAREPLANREVIEWDATE                                              AS CARE_PLAN_REVIEW_DATE,
    MRADM_PROGRESSDATE                                                    AS PROGRESS_DATE,
    MRADM_PROGRESSTIME                                                    AS PROGRESS_TIME,
    MRADM_DATEPROOFPRINTED                                                AS DATE_PROOF_PRINTED,
    MRADM_DRGFIRSTDATEPROCESSING                                          AS DRG_FIRST_DATE_PROCESSING,
    MRADM_DRGLASTDATEPROCESSING                                           AS DRG_LAST_DATE_PROCESSING,
    MRADM_TRANSFERDATEREFCLN                                              AS TRANSFER_DATE_REF_CLN,
    NULLIF(TRIM(MRADM_SEQNO), 'NULL')                                     AS SEQ_NO,
    NULLIF(TRIM(MRADM_NURSINGHOURS), 'NULL')                              AS NURSING_HOURS,
    NULLIF(TRIM(MRADM_ATISWIES), 'NULL')                                  AS ATIS_WIES,
    NULLIF(TRIM(MRADM_BASEWIES), 'NULL')                                  AS BASE_WIES,
    NULLIF(TRIM(MRADM_TOTALWIESPRICE), 'NULL')                            AS TOTAL_WIES_PRICE,
    NULLIF(TRIM(MRADM_TOTALWIESSCORE), 'NULL')                            AS TOTAL_WIES_SCORE,
    NULLIF(TRIM(MRADM_INLIEREQUIVALENCE), 'NULL')                         AS INLIER_EQUIVALENCE,
    NULLIF(TRIM(MRADM_DRG_WEIGHTING), 'NULL')                             AS DRG_WEIGHTING,
    NULLIF(TRIM(MRADM_RESEND), 'NULL')                                    AS RESEND,
    NULLIF(TRIM(MRADM_DELETION), 'NULL')                                  AS DELETION,
    NULLIF(TRIM(MRADM_SENTPRS2), 'NULL')                                  AS SENT_PRS2,
    NULLIF(TRIM(MRADM_PRS2STATUS), 'NULL')                                AS PRS2_STATUS,
    NULLIF(TRIM(MRADM_RECORDSTORESUBMIT), 'NULL')                         AS RECORD_STORE_SUBMIT,
    NULLIF(TRIM(MRADM_MEDICALLYFIT), 'NULL')                              AS MEDICALLY_FIT,
    NULLIF(TRIM(MRADM_TAKINGCALLS), 'NULL')                               AS TAKING_CALLS,
    NULLIF(TRIM(MRADM_RINGWARD), 'NULL')                                  AS RING_WARD,
    NULLIF(TRIM(MRADM_AMBULANCECASE), 'NULL')                             AS AMBULANCE_CASE,
    NULLIF(TRIM(MRADM_NOSTILLBIRTH), 'NULL')                              AS NO_STILL_BIRTH,
    NULLIF(TRIM(MRADM_TUBALLIGATION), 'NULL')                             AS TUBAL_LIGATION,
    NULLIF(TRIM(MRADM_CEASARIANSECTION), 'NULL')                          AS CEASARIAN_SECTION,
    NULLIF(TRIM(MRADM_ECTOPIC), 'NULL')                                   AS ECTOPIC,
    NULLIF(TRIM(MRADM_KIDNEYTRANSPLANT), 'NULL')                          AS KIDNEY_TRANSPLANT,
    NULLIF(TRIM(MRADM_KIDNEYTRANSPDES), 'NULL')                           AS KIDNEY_TRANSP_DES,
    NULLIF(TRIM(MRADM_OTHERINFECTTYPE), 'NULL')                           AS OTHER_INFECT_TYPE,
    NULLIF(TRIM(MRADM_DOCDISCH_DR), 'NULL')                               AS DOC_DISCH_DR,
    NULLIF(TRIM(MRADM_NURSEDISCH_DR), 'NULL')                             AS NURSE_DISCH_DR,
    NULLIF(TRIM(MRADM_DATERANGEFROM), 'NULL')                             AS DATE_RANGE_FROM,
    NULLIF(TRIM(MRADM_DATERANGETO), 'NULL')                               AS DATE_RANGE_TO,
    MRADM_RESTPERIODFROM                                                  AS REST_PERIOD_FROM,
    MRADM_RESTPERIODTO                                                    AS REST_PERIOD_TO,
    MRADM_VISITHRFROM                                                     AS VISIT_HR_FROM,
    MRADM_VISITHRTO                                                       AS VISIT_HR_TO,
    MRADM_DISCHRUGTOTAL                                                   AS DISCH_RUG_TOTAL,
    MRADM_MEDICSUFFIX_DR                                                  AS MEDIC_SUFFIX_DR,
    NULLIF(TRIM(MRADM_OTHERDISCHTYPE), 'NULL')                            AS OTHER_DISCH_TYPE,
    NULLIF(TRIM(MRADM_MULTIVISITINGHOURSRANGES), 'NULL')                  AS MULTI_VISITING_HOURS_RANGES,
    NULLIF(TRIM(MRADM_FOLLOWUPREASONFREETEXT), 'NULL')                    AS FOLLOW_UP_REASON_FREE_TEXT,
    NULLIF(TRIM(MRADM_MRADMMEDICATIONHISTORY_DR), 'NULL')                 AS MRADM_MEDICATION_HISTORY_DR,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_MR_ADM') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')