SELECT
    NULLIF(TRIM(CLN_KEY), 'NULL')                                         AS CLN_KEY,
    CLN_ROWID                                                             AS ROWID,
    NULLIF(TRIM(CLN_PARREF), 'NULL')                                      AS PAR_REF,
    NULLIF(TRIM(CLN_CHILDSUB), 'NULL')                                    AS CHILD_SUB,
    NULLIF(TRIM(CLN_CODE), 'NULL')                                        AS CODE,
    NULLIF(TRIM(CLN_ADDRESS1), 'NULL')                                    AS ADDRESS_1,
    NULLIF(TRIM(CLN_ADDRESS2), 'NULL')                                    AS ADDRESS_2,
    NULLIF(TRIM(CLN_CITY_DR), 'NULL')                                     AS CITY_DR,
    NULLIF(TRIM(CLN_ZIP_DR), 'NULL')                                      AS ZIP_DR,
    NULLIF(TRIM(CLN_PHONE), 'NULL')                                       AS PHONE,
    NULLIF(TRIM(CLN_PROVIDERNO), 'NULL')                                  AS PROVIDER_NO,
    NULLIF(TRIM(CLN_BUSPHONE), 'NULL')                                    AS BUS_PHONE,
    NULLIF(TRIM(CLN_MOBPHONE), 'NULL')                                    AS MOB_PHONE,
    NULLIF(TRIM(CLN_FAX), 'NULL')                                         AS FAX,
    LOWER(NULLIF(TRIM(CLN_EMAIL), 'NULL'))                                AS EMAIL,
    NULLIF(TRIM(CLN_PREFERREDCONTACT), 'NULL')                            AS PREFERRED_CONTACT,
    NULLIF(TRIM(CLN_VEMD), 'NULL')                                        AS VEMD,
    TRY_TO_DATE(NULLIF(TRIM(CLN_DATEFROM), 'NULL'))                       AS DATE_FROM,
    TRY_TO_DATE(NULLIF(TRIM(CLN_DATETO), 'NULL'))                         AS DATE_TO,
    NULLIF(TRIM(CLN_CLINIC_DR), 'NULL')                                   AS CLINIC_DR,
    NULLIF(TRIM(CLN_ALIAS), 'NULL')                                       AS ALIAS,
    NULLIF(TRIM(CLN_LOCATION), 'NULL')                                    AS LOCATION,
    NULLIF(TRIM(CLN_SYSTEM), 'NULL')                                      AS SYSTEM,
    NULLIF(TRIM(CLN_DEFAULTSEND), 'NULL')                                 AS DEFAULT_SEND,
    TRY_TO_DATE(NULLIF(TRIM(CLN_CREATEDDATE), 'NULL'))                    AS CREATED_DATE,
    NULLIF(TRIM(CLN_CREATEDTIME), 'NULL')                                 AS CREATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(CLN_CREATEDUSER_DR), 'NULL'), 18, 6)        AS CREATED_USER_DR,
    TRY_TO_DATE(NULLIF(TRIM(CLN_UPDATEDDATE), 'NULL'))                    AS UPDATED_DATE,
    NULLIF(TRIM(CLN_UPDATEDTIME), 'NULL')                                 AS UPDATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(CLN_UPDATEDUSER_DR), 'NULL'), 18, 6)        AS UPDATED_USER_DR,
    NULLIF(TRIM(CLN_CONFIDENTIALFAX), 'NULL')                             AS CONFIDENTIAL_FAX,
    NULLIF(TRIM(CLN_TEXT1), 'NULL')                                       AS TEXT_1,
    NULLIF(TRIM(CLN_TEXT2), 'NULL')                                       AS TEXT_2

FROM {{ ref('HIST_TRAKCARE_PAC_REFDOCTORCLINIC') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')