SELECT
    ATTEND_ROWID                                                          AS ROW_ID,
    NULLIF(TRIM(ATTEND_CODE), 'NULL')                                     AS CODE,
    NULLIF(TRIM(ATTEND_DESC), 'NULL')                                     AS DESCRIPTION,
    TRY_TO_DATE(NULLIF(TRIM(ATTEND_DATEFROM), 'NULL'))                    AS DATE_FROM,
    TRY_TO_DATE(NULLIF(TRIM(ATTEND_DATETO), 'NULL'))                      AS DATE_TO,
    NULLIF(TRIM(ATTEND_STATISTICINDICATOR), 'NULL')                       AS STATISTIC_INDICATOR,
    NULLIF(TRIM(ATTEND_NATIONALCODE), 'NULL')                             AS NATIONAL_CODE,
    NULLIF(TRIM(ATTEND_EPISODETYPE), 'NULL')                              AS EPISODE_TYPE,
    NULLIF(TRIM(ATTEND_REFTYPE), 'NULL')                                  AS REF_TYPE,
    NULLIF(TRIM(ATTEND_MANDATORYREFDOCTOR), 'NULL')                       AS MANDATORY_REF_DOCTOR,
    NULLIF(TRIM(ATTEND_MANDATORYREFHOSPITAL), 'NULL')                     AS MANDATORY_REF_HOSPITAL,
    NULLIF(TRIM(ATTEND_BOOKPASTGD), 'NULL')                               AS BOOK_PAST_GD,
    NULLIF(TRIM(ATTEND_BOOKPASTGDTYPE), 'NULL')                           AS BOOK_PAST_GD_TYPE,
    NULLIF(TRIM(ATTEND_OWNER), 'NULL')                                    AS OWNER,
    NULLIF(TRIM(ATTEND_CODETABLETAGS), 'NULL')                            AS CODE_TABLE_TAGS,
    TRY_TO_DATE(NULLIF(TRIM(ATTEND_CREATEDDATE), 'NULL'))                 AS CREATED_DATE,
    NULLIF(TRIM(ATTEND_CREATEDTIME), 'NULL')                              AS CREATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(ATTEND_CREATEDUSER_DR), 'NULL'), 18, 6)     AS CREATED_USER_DR,
    TRY_TO_DATE(NULLIF(TRIM(ATTEND_UPDATEDDATE), 'NULL'))                 AS UPDATED_DATE,
    NULLIF(TRIM(ATTEND_UPDATEDTIME), 'NULL')                              AS UPDATED_TIME,
    TRY_TO_NUMBER(NULLIF(TRIM(ATTEND_UPDATEDUSER_DR), 'NULL'), 18, 6)     AS UPDATED_USER_DR

FROM {{ ref('HIST_TRAKCARE_PAC_SOURCEOFATTENDANCE') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')