SELECT
    HOSP_ROWID                                                            AS ROW_ID,
    NULLIF(TRIM(HOSP_CODE), 'NULL')                                       AS CODE,
    NULLIF(TRIM(HOSP_DESC), 'NULL')                                       AS DESCRIPTION,
    NULLIF(TRIM(HOSP_FAX), 'NULL')                                        AS FAX,
    HOSP_CITY                                                             AS CITY_DR,
    NULLIF(TRIM(HOSP_LOGO), 'NULL')                                       AS LOGO,
    LOWER(NULLIF(TRIM(HOSP_EMAIL), 'NULL'))                               AS EMAIL,
    NULLIF(TRIM(HOSP_OWNER), 'NULL')                                      AS OWNER,
    NULLIF(TRIM(HOSP_PHONE), 'NULL')                                      AS PHONE,
    HOSP_STATE                                                            AS STATE_DR,
    HOSP_ZIPDR                                                            AS ZIP_DR,
    HOSP_DATETO                                                           AS DATE_TO,
    LOWER(NULLIF(TRIM(HOSP_EMAIL1), 'NULL'))                              AS EMAIL_1,
    NULLIF(TRIM(HOSP_ISLAND), 'NULL')                                     AS ISLAND,
    NULLIF(TRIM(HOSP_ADDRESS), 'NULL')                                    AS ADDRESS_1,
    NULLIF(TRIM(HOSP_NEWWAYS), 'NULL')                                    AS NEW_WAYS,
    HOSP_DATEFROM                                                         AS DATE_FROM,
    HOSP_MHACT_DR                                                         AS MH_ACT_DR,
    NULLIF(TRIM(HOSP_TIMEZONE), 'NULL')                                   AS TIMEZONE,
    HOSP_TRUST_DR                                                         AS TRUST_DR,
    HOSP_BILLNO_DR                                                        AS BILL_NO_DR,
    NULLIF(TRIM(HOSP_CARETYPES), 'NULL')                                  AS CARE_TYPES,
    HOSP_REGION_DR                                                        AS REGION_DR,
    HOSP_TARIFF_DR                                                        AS TARIFF_DR,
    HOSP_COUNTRY_DR                                                       AS COUNTRY_DR,
    NULLIF(TRIM(HOSP_FACILITYID), 'NULL')                                 AS FACILITY_ID,
    NULLIF(TRIM(HOSP_APPLYVCFEES), 'NULL')                                AS APPLY_VC_FEES,
    NULLIF(TRIM(HOSP_BANKACCOUNT), 'NULL')                                AS BANK_ACCOUNT,
    NULLIF(TRIM(HOSP_BILLADDRESS), 'NULL')                                AS BILL_ADDRESS_1,
    HOSP_CREATEDDATE                                                      AS CREATED_DATE,
    HOSP_CREATEDTIME                                                      AS CREATED_TIME,
    HOSP_PROVINCE_DR                                                      AS PROVINCE_DR,
    HOSP_UPDATEDDATE                                                      AS UPDATED_DATE,
    HOSP_UPDATEDTIME                                                      AS UPDATED_TIME,
    NULLIF(TRIM(HOSP_BANKACCOUNT1), 'NULL')                               AS BANK_ACCOUNT_1,
    NULLIF(TRIM(HOSP_NATIONALCODE), 'NULL')                               AS NATIONAL_CODE,
    HOSP_SUBREGION_DR                                                     AS SUB_REGION_DR,
    NULLIF(TRIM(HOSP_CLAIMTYPECODE), 'NULL')                              AS CLAIM_TYPE_CODE,
    NULLIF(TRIM(HOSP_CODETABLETAGS), 'NULL')                              AS CODE_TABLE_TAGS,
    NULLIF(TRIM(HOSP_DEBTORCONTROL), 'NULL')                              AS DEBTOR_CONTROL,
    HOSP_POSTOFFICE_DR                                                    AS POST_OFFICE_DR,
    NULLIF(TRIM(HOSP_CODETRANSLATED), 'NULL')                             AS CODE_TRANSLATED,
    HOSP_CREATEDUSER_DR                                                   AS CREATED_USER_DR,
    NULLIF(TRIM(HOSP_DESCTRANSLATED), 'NULL')                             AS DESC_TRANSLATED,
    LOWER(NULLIF(TRIM(HOSP_FAXSERVEREMAIL), 'NULL'))                      AS FAX_SERVER_EMAIL,
    NULLIF(TRIM(HOSP_ORGANIZATIONID), 'NULL')                             AS ORGANIZATION_ID,
    NULLIF(TRIM(HOSP_UNALLOCPAYMENT), 'NULL')                             AS UNALLOC_PAYMENT,
    HOSP_UPDATEDUSER_DR                                                   AS UPDATED_USER_DR,
    NULLIF(TRIM(HOSP_USESAMECOUNTER), 'NULL')                             AS USE_SAME_COUNTER,
    NULLIF(TRIM(HOSP_ACCRUALSCONTROL), 'NULL')                            AS ACCRUALS_CONTROL,
    HOSP_COUNTYPARISH_DR                                                  AS COUNTY_PARISH_DR,
    HOSP_CREDITNOTENO_DR                                                  AS CREDIT_NOTE_NO_DR,
    HOSP_DAYSFOROPDOFFER                                                  AS DAYS_FOR_OP_OFFER,
    HOSP_FACILITYTYPE_DR                                                  AS FACILITY_TYPE_DR,
    HOSP_HOSPDRGCATEG_DR                                                  AS HOSP_DRG_CATEG_DR,
    NULLIF(TRIM(HOSP_MEDICALDIRECTOR), 'NULL')                            AS MEDICAL_DIRECTOR,
    HOSP_INSURANCETYPE_DR                                                 AS INSURANCE_TYPE_DR,
    NULLIF(TRIM(HOSP_PAYORAPPROVALREQ), 'NULL')                           AS PAYOR_APPROVAL_REQ,
    HOSP_GUARANTORGROUP_DR                                                AS GUARANTOR_GROUP_DR,
    NULLIF(TRIM(HOSP_PBSFACILITYNUMBER), 'NULL')                          AS PBS_FACILITY_NO,
    NULLIF(TRIM(HOSP_APPLYDRGOUTLIERCALC), 'NULL')                        AS APPLY_DRG_OUTLIER_CALC,
    NULLIF(TRIM(HOSP_CPGROUPAFFILIATIONS), 'NULL')                        AS CP_GROUP_AFFILIATIONS,
    HOSP_POSESSIONCOUNTER_DR                                              AS POSSESSION_COUNTER_DR,
    NULLIF(TRIM(HOSP_MANDATORYREFHOSPITAL), 'NULL')                       AS MANDATORY_REF_HOSPITAL,
    NULLIF(TRIM(HOSP_ASSIGNEDGROUPCATEGORY), 'NULL')                      AS ASSIGNED_GROUP_CATEGORY,
    NULLIF(TRIM(HOSP_PBSDISPENSINGRULELIST), 'NULL')                      AS PBS_DISPENSING_RULE_LIST,
    NULLIF(TRIM(HOSP_PROCANAESTHETICORDERS), 'NULL')                      AS PROC_ANAESTHETIC_ORDERS,
    NULLIF(TRIM(HOSP_SHOWAPPWTIMEVIOLATION), 'NULL')                      AS SHOW_APP_W_TIME_VIOLATION,
    HOSP_WEEKSSUSPENSIONREVIEW                                            AS WEEKS_SUSPENSION_REVIEW,
    HOSP_DAYSOFFEROUTCOMECHANGE                                           AS DAYS_OFFER_OUTCOME_CHANGE,
    HOSP_WARNSAMESERVICEWNXDAYS                                           AS WARN_SAME_SERVICE_W_N_X_DAYS,
    HOSP_DAYSFOROPLETTERRESPONSE                                          AS DAYS_FOR_OP_LETTER_RESPONSE,
    NULLIF(TRIM(HOSP_EPTYPEMEDDISBEFOREFINDIS), 'NULL')                   AS EP_TYPE_MED_DIS_BEFORE_FIN_DIS,
    HOSP_OFFERSBEFOREIP_OPWAITRESET                                       AS OFFERS_BEFORE_IP_OP_WAIT_RESET,

    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_CT_HOSPITAL') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')