SELECT
    TRIM(AGE)                                       AS AGE,
    {{ format_name('LGA') }}                        AS LGA,
    TRIM(ATSI)                                      AS ATSI,
    TRIM(TAGS)                                      AS TAGS,
    UPPER(TRIM(STATE))                              AS STATE,
    UPPER(TRIM(GENDER))                             AS GENDER,
    {{ format_name('REGION') }}                     AS REGION,
    {{ format_name('SUBURB') }}                     AS CITY,
    {{ format_name('ADDRESS') }}                    AS ADDRESS,
    {{ format_name('LANGUAGE') }}                   AS LANGUAGE,
    CAST(TRIM(POSTCODE) AS TEXT)                    AS POSTCODE,
    TRIM(RELATIONSHIP)                              AS RELATIONSHIP,
    {{ format_date('END_DATE') }}                   AS END_DATE,
    TRY_TO_NUMBER(TRIM(DEBTOR_ID),18,6)             AS DEBTOR_ID,
    {{ format_name('LAST_NAME') }}                  AS LAST_NAME,
    {{ format_name('FIRST_NAME') }}                 AS FIRST_NAME,
    {{ format_phone('HOME_PHONE') }}                AS HOME_PHONE,
    {{ format_date('START_DATE') }}                 AS START_DATE,
    TRY_TO_NUMBER(TRIM(NDIS_NUMBER),18,6)           AS NDIS_NO,
    TRIM(RECORD_TYPE)                               AS RECORD_TYPE,
    {{ format_phone('MOBILE_PHONE') }}              AS MOBILE_PHONE,
    {{ format_date('DATE_OF_BIRTH') }}              AS DOB,
    LOWER(TRIM(EMAIL_ADDRESS))                      AS EMAIL,
    TRIM(REASON_FOR_EXIT)                           AS EXIT_REASON,
    {{ format_name('COUNTRY_OF_BIRTH') }}           AS BIRTH_COUNTRY,
    TRIM(CARER_PREFERENCES)                         AS CARER_PREFERENCE,
    {{ format_date('LAST_JOURNAL_DATE') }}          AS LAST_JOURNAL_DATE,
    TRIM(SUPPORTABILITY_ID)                         AS SUPPORTABILITY_ID,
    TRIM(IS_BILLING_CONTACT)                        AS IS_BILLING_CONTACT,
    TRIM(IS_PRIMARY_CONTACT)                        AS IS_PRIMARY_CONTACT,
    {{ format_date('LAST_ACTIVITY_DATE') }}         AS LAST_ACTIVITY_DATE,
    TRIM(PRIMARY_DISABILITY)                        AS PRIMARY_DISABILITY,
    TRIM(LABOUR_FORCE_STATUS)                       AS LABOUR_FORCE_STATUS,
    TRIM(LIVING_ARRANGEMENTS)                       AS LIVING_ARRANGEMENTS,
    TRIM(HOUSEHOLD_COMPOSITION)                     AS HOUSEHOLD_COMPOSITION,
    TRIM(IS_REGISTERED_TO_VOTE)                     AS IS_REGISTERED_TO_VOTE,
    TRIM(HIGHEST_LEVEL_OF_EDUCATION)                AS EDUCATION_LEVEL,
    TRY_TO_NUMBER(TRIM(UNIQUE_STUDENT_IDENTIFIER_USI_),18,6) AS USI,

    _AIRBYTE_EXTRACTED_AT                            AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_SUPPORTABILITY_CLIENT_LIST_INC_PERSONAL_CONTACTS') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')