SELECT
    NULLIF(TRIM(PAINS_ROWID), 'NULL')                                     AS ROW_ID,
    NULLIF(TRIM(PAINS_RANK), 'NULL')                                      AS RANK,
    NULLIF(TRIM(PAINS_CARDNO), 'NULL')                                    AS CARD_NO,
    PAINS_PARREF                                                          AS PAR_REF,
    PAINS_SPEC_DR                                                         AS SPEC_DR,
    NULLIF(TRIM(PAINS_APPLYGST), 'NULL')                                  AS APPLY_GST,
    PAINS_CTLOC_DR                                                        AS CT_LOC_DR,
    NULLIF(TRIM(PAINS_CTPCP_DR), 'NULL')                                  AS CT_PCP_DR,
    PAINS_CTREL_DR                                                        AS CT_REL_DR,
    PAINS_CHILDSUB                                                        AS CHILD_SUB,
    PAINS_DATETYPETO                                                      AS DATE_TYPE_TO,
    PAINS_INSTYPE_DR                                                      AS INS_TYPE_DR,
    PAINS_UPDATEDATE                                                      AS UPDATED_DATE,
    PAINS_UPDATETIME                                                      AS UPDATED_TIME,
    PAINS_CARDTYPE_DR                                                     AS CARD_TYPE_DR,
    PAINS_DATEVALIDTO                                                     AS DATE_VALID_TO,
    PAINS_NUMOFVISITS                                                     AS NUM_OF_VISITS,
    PAINS_ROOMTYPE_DR                                                     AS ROOM_TYPE_DR,
    NULLIF(TRIM(PAINS_CARDHOLDERID), 'NULL')                              AS CARD_HOLDER_ID,
    PAINS_DATETYPEFROM                                                    AS DATE_TYPE_FROM,
    NULLIF(TRIM(PAINS_DEPENDENT_DR), 'NULL')                              AS DEPENDENT_DR,
    PAINS_AUXINSTYPE_DR                                                   AS AUX_INS_TYPE_DR,
    PAINS_DATEVALIDFROM                                                   AS DATE_VALID_FROM,
    NULLIF(TRIM(PAINS_DEPENDENTFLAG), 'NULL')                             AS DEPENDENT_FLAG,
    PAINS_UPDATEUSER_DR                                                   AS UPDATED_USER_DR,
    NULLIF(TRIM(PAINS_CARDHOLDERNAME), 'NULL')                            AS CARD_HOLDER_NAME,
    PAINS_EPISSUBTYPE_DR                                                  AS EPIS_SUBTYPE_DR,
    NULLIF(TRIM(PAINS_BENEFITPACKAGE_DR), 'NULL')                         AS BENEFIT_PACKAGE_DR,
    PAINS_NUMOFVISITSREMAIN                                               AS NUM_OF_VISITS_REMAIN,
    NULLIF(TRIM(PAINS_PERSONRESPONSIBLE), 'NULL')                         AS PERSON_RESPONSIBLE,
    PAINS_UPDATEUSERHOSPITAL_DR                                           AS UPDATED_USER_HOSPITAL_DR,
    NULLIF(TRIM(PAINS_PAYORVARIATIONCOMMENTS), 'NULL')                    AS PAYOR_VARIATION_COMMENTS,
    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS
FROM {{ ref('HIST_TRAKCARE_PA_PERSONADMINSURANCE') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')