SELECT
    CAST(AGE AS TEXT) AS AGE,
    {{ format_name('SUFFIX') }}            AS SUFFIX,
    CAST(BIRTHDAY AS DATE)                 AS DOB,
    {{ format_name('LASTNAME') }}          AS LAST_NAME,
    TRIM(USERNAME)                         AS USER_NAME,
    {{ format_name('FIRSTNAME') }}         AS FIRST_NAME,
    {{ format_name('MIDDLENAME') }}        AS MIDDLE_NAME,
    TRIM(POSTALCODE)                       AS POSTCODE,
    {{ format_name('SALUTATION') }}        AS TITLE,
    TRIM(CLIENTSTATUS)                     AS STATUS,
    LOWER(TRIM(EMAILADDRESS))              AS EMAIL,
    TRY_TO_NUMBER(TRIM(DATABASEUSERID),18,6)  AS BETTER_IMPACT_USER_ID,
    {{ format_name('LEGALFIRSTNAME') }}    AS LEGAL_FIRST_NAME,
    CAST(CLIENTDATEJOINED AS DATE)         AS JOINED_TS,
    CAST(YEARSSINCECLIENTDATEJOINED AS TEXT)    AS TENURE_YEARS,
    DATEOFLASTCLIENTSTATUSCHANGE           AS LAST_STATUS_CHANGE_TS,

    TRIM(CF_ABOUT_YOUR_CLIENT_GENDER)      AS CF_GENDER,
    {{ format_date('CF_MATCH_DETAILS_DATE_OF_MATCH') }} AS CF_MATCH_DETAILS_MATCH_DATE,
    {{ format_name('CF_MATCH_DETAILS_NAME_OF_VISITOR') }} AS CF_MATCH_DETAILS_VISITOR_NAME,
    TRIM(CF_ABOUT_YOUR_CLIENT_WORK_BACKGROUND) AS CF_WORK_BACKGROUND,
    {{ format_name('CF_MATCH_DETAILS_POTENTIAL_VOLUNTEER') }} AS CF_MATCH_DETAILS_POTENTIAL_VOLUNTEER,
    {{ format_name('CF_ABOUT_YOUR_CLIENT_PREFERRED_LANGUAGE') }} AS CF_PREF_LANGUAGE,

    TRIM(CF_AGED_CARE_FACILITY_MATCH_INFORMATION_AGED_CARE_FACILITY_LIST_) AS CF_FACILITY_LIST,
    TRIM(CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_IF_MORE_THAN_ONE_SPECIAL_NEED_APPLIES_PLEASE_LIST_HERE) AS CF_IDENTIFY_AS_PART_OF_SPECIAL_NEEDS_GROUPS,
    TRIM(CF_AGED_CARE_FUNDING_DETAILS_IF_RELEVANT_SELECT_NAME_OF_HOME_CARE_PACKAGE_PROVIDER_OR_RESIDENTIAL_AGED_CARE_FACILITY_WHERE_THE_CLIENT_RESIDES) AS CF_AGED_CARE_FUNDING_DETAILS,
    TRIM(CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_DOES_THE_RECIPIENT_IDENTIFY_AS_BEING_FROM_A_SPECIAL_NEEDS_GROUP_) AS CF_SPECIAL_NEEDS_GROUPS,

    {{ format_name('CF_ABOUT_YOUR_CLIENT_COUNTRY_OF_ORIGIN') }} AS CF_COUNTRY_OF_ORIGIN,

    _AIRBYTE_EXTRACTED_AT                   AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_BETTER_IMPACT_PROFILE_EXPORT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')