SELECT
    NULLIF(TRIM(ITP_ROWID), 'NULL')                                       AS ROW_ID,
    NULLIF(TRIM(ITP_PARREF), 'NULL')                                      AS PAR_REF,
    ITP_CHILDSUB                                                          AS CHILD_SUB,
    ITP_RANK                                                              AS RANK,
    ITP_DAYTO                                                             AS DAY_TO,
    ITP_DAYFROM                                                           AS DAY_FROM,
    ITP_PRICE                                                             AS PRICE,
    ITP_DATETO                                                            AS DATE_TO,
    ITP_DATEFROM                                                          AS DATE_FROM,
    ITP_UOM_DR                                                            AS UOM_DR,
    ITP_BASEUNIT                                                          AS BASE_UNIT,
    ITP_PAYORAMT                                                          AS PAYOR_AMT,
    ITP_TARIFF_DR                                                         AS TARIFF_DR,
    ITP_URGENTFEE                                                         AS URGENT_FEE,
    NULLIF(TRIM(ITP_ACCOUTCODE), 'NULL')                                  AS ACCOUNT_CODE,
    ITP_BEDTYPE_DR                                                        AS BED_TYPE_DR,
    ITP_COUNTRY_DR                                                        AS COUNTRY_DR,
    NULLIF(TRIM(ITP_EXCLUDEVAT), 'NULL')                                  AS EXCLUDE_VAT,
    ITP_HOSPITALDR                                                        AS HOSPITAL_DR,
    ITP_INSTYPE_DR                                                        AS INS_TYPE_DR,
    ITP_PAYORSHARE                                                        AS PAYOR_SHARE,
    NULLIF(TRIM(ITP_CAREPROV_DR), 'NULL')                                 AS CARE_PROV_DR,
    ITP_CREATEDDATE                                                       AS CREATED_DATE,
    ITP_CREATEDTIME                                                       AS CREATED_TIME,
    ITP_CURRENCY_DR                                                       AS CURRENCY_DR,
    ITP_EPISBILL_DR                                                       AS EPIS_BILL_DR,
    NULLIF(TRIM(ITP_EPISODETYPE), 'NULL')                                 AS EPISODE_TYPE,
    ITP_LOCATION_DR                                                       AS LOCATION_DR,
    ITP_ROOMTYPE_DR                                                       AS ROOM_TYPE_DR,
    ITP_UPDATEDDATE                                                       AS UPDATED_DATE,
    ITP_UPDATEDTIME                                                       AS UPDATED_TIME,
    ITP_OPERCATEG_DR                                                      AS OPER_CATEG_DR,
    NULLIF(TRIM(ITP_CODETABLETAGS), 'NULL')                               AS CODE_TABLE_TAGS,
    ITP_PAYORGROUP_DR                                                     AS PAYOR_GROUP_DR,
    ITP_POSTOFFICE_DR                                                     AS POST_OFFICE_DR,
    ITP_SPECIALITY_DR                                                     AS SPECIALITY_DR,
    ITP_URGENTFEERATE                                                     AS URGENT_FEE_RATE,
    ITP_CREATEDUSER_DR                                                    AS CREATED_USER_DR,
    ITP_EPISSUBTYPE_DR                                                    AS EPIS_SUBTYPE_DR,
    ITP_UPDATEDUSER_DR                                                    AS UPDATED_USER_DR,
    NULLIF(TRIM(ITP_EXTERNALCAREPROV), 'NULL')                            AS EXTERNAL_CARE_PROV,
    ITP_NATIONALITYGROUP_DR                                               AS NATIONALITY_GROUP_DR,
    NULLIF(TRIM(ITP_MAINORDERTARIFFPRICE), 'NULL')                        AS MAIN_ORDER_TARIFF_PRICE,
    _AIRBYTE_EXTRACTED_AT                                                 AS AIRBYTE_EXTRACTED_TS
FROM {{ ref('HIST_TRAKCARE_ARC_ITEMPRICEITALY') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')