SELECT
    NULLIF(TRIM(PAPER_ROWID), 'NULL')                                         AS PERSON_ID,
    NULLIF(TRIM(PAPER_ID), 'NULL')                                            AS PERSON_NO,
    {{ format_name('PAPER_NAME') }}                                           AS LAST_NAME,
    {{ format_name('PAPER_NAME2') }}                                          AS FIRST_NAME,
    {{ format_name('PAPER_NAME3') }}                                          AS MIDDLE_NAME,
    {{ format_name('PAPER_NAME4') }}                                          AS NAME_4,
    {{ format_name('PAPER_SURNAME') }}                                        AS SURNAME,
    PAPER_DOB                                                                 AS DOB,
    NULLIF(TRIM(PAPER_ESTDOB), 'NULL')                                        AS EST_DOB,
    NULLIF(TRIM(PAPER_AGEYR), 'NULL')                                         AS AGE_YR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_SEX_DR), 'NULL'), 18, 6)                  AS SEX_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_BIRTHGENDER_DR), 'NULL'), 18, 6)          AS BIRTH_GENDER_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_GENDERIDENTITY_DR), 'NULL'), 18, 6)       AS GENDER_IDENTITY_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_PREFGENDERINTERPRETER_DR), 'NULL'), 18, 6) AS PREF_GENDER_INTERPRETER_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_TITLE_DR), 'NULL'), 18, 6)                AS TITLE_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_MARITAL_DR), 'NULL'), 18, 6)              AS MARITAL_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_DEPENDCHILDREN_DR), 'NULL'), 18, 6)       AS DEPEND_CHILDREN_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_NATION_DR), 'NULL'), 18, 6)               AS NATION_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_RELIGION_DR), 'NULL'), 18, 6)             AS RELIGION_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_COUNTRY_DR), 'NULL'), 18, 6)              AS COUNTRY_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_COUNTRY_BIRTH_DR), 'NULL'), 18, 6)        AS BIRTH_COUNTRY_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_OCCUPATION_DR), 'NULL'), 18, 6)           AS OCCUPATION_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_INDIGSTAT_DR), 'NULL'), 18, 6)            AS INDIGENOUS_STATUS_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_PREFLANGUAGE_DR), 'NULL'), 18, 6)         AS PREF_LANGUAGE_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_LANGUAGESPOKENATHOME_DR), 'NULL'), 18, 6) AS LANG_SPOKEN_AT_HOME_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_COMMUNICATIONNEEDS_DR), 'NULL'), 18, 6)   AS COMMUNICATION_NEEDS_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_LIVINGARRANGEMENT_DR), 'NULL'), 18, 6)    AS LIVING_ARRANGEMENT_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_ACCOMSETTING_DR), 'NULL'), 18, 6)         AS ACCOM_SETTING_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CARERAVAILABILITY_DR), 'NULL'), 18, 6)    AS CARER_AVAILABILITY_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_EMPLOYMENTSTAT_DR), 'NULL'), 18, 6)       AS EMPLOYMENT_STATUS_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_SOURCEOFINCOME_DR), 'NULL'), 18, 6)       AS SOURCE_OF_INCOME_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_LANGPRIM_DR), 'NULL'), 18, 6)             AS LANG_PRIM_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_SOCIALSTATUS_DR), 'NULL'), 18, 6)         AS SOCIAL_STATUS_DR,
    LOWER(NULLIF(TRIM(PAPER_EMAIL), 'NULL'))                                  AS EMAIL,
    LOWER(NULLIF(TRIM(PAPER_EMAIL2), 'NULL'))                                 AS EMAIL_2,
    {{ format_phone('PAPER_MOBPHONE') }}                                      AS MOBILE_PHONE,
    {{ format_phone('PAPER_TELH') }}                                          AS HOME_PHONE,
    {{ format_phone('PAPER_TELO') }}                                          AS WORK_PHONE,
    {{ format_phone('PAPER_SECONDPHONE') }}                                   AS SECOND_PHONE,
    {{ format_address('PAPER_STNAME') }}                                      AS STREET_NAME,
    {{ format_address('PAPER_STNAMELINE1') }}                                 AS STREET_NAME_LINE_1,
    NULL                                                                      AS ADDRESS_1,
    NULLIF(TRIM(PAPER_ADDRESS2), 'NULL')                                      AS ADDRESS_2,
    NULLIF(TRIM(PAPER_FOREIGNADDRESS), 'NULL')                                AS FOREIGN_ADDRESS,
    NULLIF(TRIM(PAPER_POSTCODE), 'NULL')                                      AS POSTCODE,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_ZIP_DR), 'NULL'), 18, 6)                  AS ZIP_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CITYCODE_DR), 'NULL'), 18, 6)             AS CITY_CODE_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_STATECODE_DR), 'NULL'), 18, 6)            AS STATE_CODE_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CITYAREA_DR), 'NULL'), 18, 6)             AS CITY_AREA_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CT_REGION_DR), 'NULL'), 18, 6)            AS REGION_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CT_PROVINCE_DR), 'NULL'), 18, 6)          AS PROVINCE_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CT_HCA_DR), 'NULL'), 18, 6)               AS HCA_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CITYBIRTH_DR), 'NULL'), 18, 6)            AS BIRTH_CITY_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_REGIONBIRTH_DR), 'NULL'), 18, 6)          AS BIRTH_REGION_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_PROVINCE_BIRTH_DR), 'NULL'), 18, 6)       AS BIRTH_PROVINCE_DR,
    NULLIF(TRIM(PAPER_DECEASED), 'NULL')                                      AS DECEASED,
    PAPER_DECEASED_DATE                                                       AS DECEASED_DATE,
    NULLIF(TRIM(PAPER_DECEASEDTIME), 'NULL')                                  AS DECEASED_TIME,
    {{ format_name('PAPER_NOKNAME') }}                                        AS NOK_NAME,
    {{ format_phone('PAPER_NOKPHONE') }}                                      AS NOK_PHONE,
    {{ format_phone('PAPER_NOKBUSPHONE') }}                                   AS NOK_BUS_PHONE,
    NULLIF(TRIM(PAPER_NOKTEXT), 'NULL')                                       AS NOK_TEXT,
    {{ format_address('PAPER_NOKADDRESS1') }}                                 AS NOK_ADDRESS_1,
    NULLIF(TRIM(PAPER_NOKADDRESS2), 'NULL')                                   AS NOK_ADDRESS_2,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_NOKCITY_DR), 'NULL'), 18, 6)              AS NOK_CITY_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_NOKZIP_DR), 'NULL'), 18, 6)               AS NOK_ZIP_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_NOKCTRLT_DR), 'NULL'), 18, 6)             AS NOK_CTRLT_DR,
    NULLIF(TRIM(PAPER_REMARK), 'NULL')                                        AS REMARK,
    NULLIF(TRIM(PAPER_FEEDBACKCONSENT), 'NULL')                               AS FEEDBACK_CONSENT,
    PAPER_FEEDBACKCONSENTDATE                                                 AS FEEDBACK_CONSENT_DATE,
    NULLIF(TRIM(PAPER_INTERPRETERREQUIRED), 'NULL')                           AS INTERPRETER_REQUIRED,
    NULLIF(TRIM(PAPER_CANLEAVEMESSAGESON), 'NULL')                            AS CAN_LEAVE_MESSAGES_ON,
    NULLIF(TRIM(PAPER_APPOINTMENTSMS), 'NULL')                                AS APPOINTMENT_SMS,
    NULLIF(TRIM(PAPER_PREFERREDCONTACTMETHOD), 'NULL')                        AS PREF_CONTACT_METHOD,
    NULLIF(TRIM(PAPER_GOVERNCARDNO), 'NULL')                                  AS GOVERN_CARD_NO,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_CONCESSCARDTYPE_DR), 'NULL'), 18, 6)      AS CONCESSION_CARD_TYPE_DR,
    NULLIF(TRIM(PAPER_FREETEXT1), 'NULL')                                     AS FREE_TEXT_1,
    NULLIF(TRIM(PAPER_FREETEXT2), 'NULL')                                     AS FREE_TEXT_2,
    NULLIF(TRIM(PAPER_FREETEXT3), 'NULL')                                     AS FREE_TEXT_3,
    NULLIF(TRIM(PAPER_FREETEXT4), 'NULL')                                     AS FREE_TEXT_4,
    NULLIF(TRIM(PAPER_FREETEXT5), 'NULL')                                     AS FREE_TEXT_5,
    NULLIF(TRIM(PAPER_STAYINGPERMANENTLY), 'NULL')                            AS CHRONIC_COMPLEX_CLIENT,
    NULLIF(TRIM(PAPER_FAMILYDOCTORCLINIC_DR), 'NULL')                         AS FAMILY_DOCTOR_CLINIC_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_HCP_DR), 'NULL'), 18, 6)                  AS HCP_DR,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_HOSPITAL_DR), 'NULL'), 18, 6)             AS HOSPITAL_DR,
    NULLIF(TRIM(PAPER_REFUGEESTATUS_DR), 'NULL')                              AS REFUGEE_STATUS_DR,
    NULLIF(TRIM(PAPER_SOCIALSTATUSLIST), 'NULL')                              AS SOCIAL_STATUS_LIST,
    NULLIF(TRIM(PAPER_GPCONSENT), 'NULL')                                     AS GP_CONSENT,
    NULLIF(TRIM(PAPER_SMSCONSENT), 'NULL')                                    AS SMS_CONSENT,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_PAPMI_DR), 'NULL'), 18, 6)                AS PATIENT_DR,
    PAPER_UPDATEDATE                                                          AS UPDATED_DATE,
    NULLIF(TRIM(PAPER_UPDATETIME), 'NULL')                                    AS UPDATED_TIME,
    NULLIF(TRIM(PAPER_USERUPDATE), 'NULL')                                    AS UPDATED_USER,
    PAPER_DATEADDED                                                           AS CREATED_DATE,
    TRY_TO_NUMBER(NULLIF(TRIM(PAPER_USERADDED_DR), 'NULL'), 18, 6)            AS CREATED_USER_DR,

    _AIRBYTE_EXTRACTED_AT                                                     AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_TRAKCARE_PA_PERSON') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')