SELECT
    TRY_TO_NUMBER(TRIM(NO_),38)                     AS ROW_NO,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(SERVICE),'$',''),'(','-'),')',''),',',''),18,6)                                  AS SERVICE,
    {{ format_name('FIRST_NAME') }}                 AS FIRST_NAME,
    {{ format_name('LAST_NAME') }}                  AS LAST_NAME,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(SUPPLEMENTS),'$',''),'(','-'),')',''),',',''),18,6)                              AS SUPPLEMENTS_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(PKG_MGMT_COST),'$',''),'(','-'),')',''),',',''),18,6)                            AS PKG_MGMT_COST,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(CARE_MGMT_COST),'$',''),'(','-'),')',''),',',''),18,6)                           AS CARE_MGMT_COST,
    {{ format_date('DISCHARGE_DATE') }}             AS DISCHARGE_DATE,
    TRY_TO_NUMBER(TRIM(CARE_RECIPIENT_ID),38)       AS CARE_RECIPIENT_ID,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(GOVERNMENT_SUBSIDY),'$',''),'(','-'),')',''),',',''),18,6)                       AS GOVERNMENT_SUBSIDY_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TOTAL_AVAILABLE_FUNDS),'$',''),'(','-'),')',''),',',''),18,6)                    AS TOTAL_AVAILABLE_FUNDS_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(ALLOCATED_TO_CONTINGENCY),'$',''),'(','-'),')',''),',',''),18,6)                 AS ALLOCATED_TO_CONTINGENCY_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(CONTINGENCY_BROUGHT_FORWARD),'$',''),'(','-'),')',''),',',''),18,6)              AS CONTINGENCY_BROUGHT_FORWARD_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(CONTINGENCY_CARRIED_FORWARD),'$',''),'(','-'),')',''),',',''),18,6)              AS CONTINGENCY_CARRIED_FORWARD_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(PROVIDER_SUBSIDISED_ITF_FEE),'$',''),'(','-'),')',''),',',''),18,6)              AS PROVIDER_SUBSIDISED_ITF_FEE,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(CONSUMER_AND_ADDITIONAL_CONTRIBUTION),'$',''),'(','-'),')',''),',',''),18,6)     AS CONSUMER_AND_ADDITIONAL_CONTRIBUTION_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(UNALLOCATED_UNSPENT_FUNDS_BROUGHT_FORWARD),'$',''),'(','-'),')',''),',',''),18,6) AS UNALLOCATED_UNSPENT_FUNDS_BROUGHT_FORWARD_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(UNALLOCATED_UNSPENT_FUNDS_CARRIED_FORWARD),'$',''),'(','-'),')',''),',',''),18,6) AS UNALLOCATED_UNSPENT_FUNDS_CARRIED_FORWARD_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_CONTINGENCY),'$',''),'(','-'),')',''),',',''),18,6) AS ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_CONTINGENCY_AMT,
    TRY_TO_NUMBER(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_UNALLOCATED),'$',''),'(','-'),')',''),',',''),18,6) AS ONE_OFF_EMERGENCY_SERVICES_PURCHASES_FROM_UNALLOCATED_AMT,

    _AIRBYTE_EXTRACTED_AT                          AS AIRBYTE_EXTRACTED_TS

FROM {{ ref('HIST_E_TOOLS_PROVIDER_STATEMENT') }}
WHERE dbt_valid_to = TO_DATE('9999-12-31')