name: 'my_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

snapshots:
  my_project:
    hist_02:
      +target_database: "02_HIST_DB"
      best_practice:
        +target_schema: BEST_PRACTICE
      better_impact:
        +target_schema: BETTER_IMPACT