name: 'BHN_Updated_DW'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

snapshots:
  BHN_Updated_DW:
    +database: DEV_02_HIST_DB
    best_practice:
      +schema: BEST_PRACTICE
    titanium:
      +schema: TITANIUM
    echidna:
      +schema: ECHIDNA
    trips:
      +schema: TRIPS
    e_tools:
      +schema: E_TOOLS
    supportability:
      +schema: SUPPORTABILITY
    micropay:
      +schema: MICROPAY
    better_impact:
      +schema: BETTER_IMPACT
    gh_connect:
      +schema: GH_CONNECT
    connx:
      +schema: CONNX
    trakcare:
      +schema: TRAKCARE

models:
  BHN_Updated_DW:
    03_prep:
      stg:
        +materialized: view
        +database: DEV_03_PREP_DB
        +schema: STG