WITH clean_parent_stream AS (
    SELECT *,
        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
            PARENT_STREAM,
            '- 34301', ''), '- 34303', ''),
            '- 34307', ''), '- 34306', ''), '- 34300', '')) AS PARENT_STREAM_CLEAN
    FROM {{ ref('rpt_vadc_fund_data') }}
    WHERE DISCHARGE_DT IS NOT NULL
)

SELECT DISTINCT
    EPISODE_ID,
    UR,
    EPISODE_DT,
    DISCHARGE_DT,
    SERVICE,
    EPISODE_CP,
    EPISODE_TEAM,
    PROGRAM_STREAM_CODE,
    PROGRAM_STREAM                                        AS PROGRAM_STREAM,
    PARENT_STREAM_CLEAN                                   AS PARENT_STREAM,
    'VADC Questionnaire must be attached to be valid'     AS EXCEPTION
FROM clean_parent_stream
WHERE Q_ROW_ID IS NULL
  AND TOTAL_HRS > 0

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'The Episode must have at least one contact to be Valid'
FROM clean_parent_stream
WHERE TOTAL_HRS = 0
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Percentage Completed must be at least 25% to be Valid'
FROM clean_parent_stream
WHERE PERCENTAGE_COMPLETED IN (
    'Not Stated / Inadequately Described', 'None of course completed'
)
AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'An outcome Questionnaire must be attached to be valid'
FROM clean_parent_stream
WHERE (
    LEFT(PROGRAM_STREAM_CODE, 4) IN ('AD71', 'AD11', 'AD20', 'AD50')
    OR PROGRAM_STREAM_CODE IN ('AODTSCOU5', 'AODTSCRC5', 'AODTSNRW5')
)
AND OUTCOME_ID IS NULL
AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'End of Treatment Reason must be completed to be valid'
FROM clean_parent_stream
WHERE COALESCE(END_OF_TREATMENT_REASON::VARCHAR, 'Not stated / inadequately described')
      = 'Not stated / inadequately described'
  AND (
      LEFT(PROGRAM_STREAM_CODE, 4) IN ('AD11', 'AD20', 'AD50')
      OR PROGRAM_STREAM_CODE IN ('AODTSCOU5', 'AODTSCRC5', 'AODTSNRW5')
  )
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'ACSO Identifier required to be valid'
FROM clean_parent_stream
WHERE (ACSO IS NULL OR LEFT(ACSO, 4) = '9999')
  AND FORENSIC_TYPE NOT IN ('None', 'not stated / inadequately described')
  AND REF_IN IS NOT NULL
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Self or Family member/friend are not valid provider types for Referral out'
FROM clean_parent_stream
WHERE REF_OUT IS NOT NULL
  AND PROVIDER_OUT_TYPE IN ('Self', 'Family member/friend')
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Referral provider, can only be self, family police or court or Correctional service for Referral In to be valid'
FROM clean_parent_stream
WHERE REF_IN IS NOT NULL
  AND PROVIDER_IN_TYPE NOT IN (
      'Police', 'Court', 'Self', 'Family member/friend', 'Correctional Service'
  )
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Discharge dt must be greater than Last contact date to be valid'
FROM clean_parent_stream
WHERE DISCHARGE_DT < LAST_CONTACT_DT
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Assessment date cannot be greater than first contact date to be valid'
FROM clean_parent_stream
WHERE QVADCASSESS_COMP > FIRST_CONTACT_DT
  AND (
      LEFT(PROGRAM_STREAM_CODE, 4) IN ('AD11', 'AD20', 'AD50')
      OR PROGRAM_STREAM_CODE IN ('AODTSCOU5', 'AODTSCRC5', 'AODTSNRW5')
  )
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Episode Date cannot be greater than First Contact date to be valid'
FROM clean_parent_stream
WHERE EPISODE_DT > FIRST_CONTACT_DT
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Contact cannot occur after discharge date to be valid'
FROM clean_parent_stream
WHERE FIRST_CONTACT_DT > DISCHARGE_DT
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Referral IN Date cannot be greater than Episode start date to be valid'
FROM clean_parent_stream
WHERE REF_IN IS NOT NULL
  AND REF_IN_DATE > EPISODE_DT
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Drug of Concern - Frequency of use cannot be null to be Valid'
FROM clean_parent_stream
WHERE DOC_OCCURRENCE IS NULL
  AND PRINCIPAL_DOC IS NOT NULL
  AND RELATIONSHIP_TO_SELF IN ('Self')
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Drug of Concern - Method of use cannot be null to be Valid'
FROM clean_parent_stream
WHERE DOC_METHOD IS NULL
  AND PRINCIPAL_DOC IS NOT NULL
  AND RELATIONSHIP_TO_SELF IN ('Self')
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Client is person of concern and Maltreatment code cannot be blank to be valid'
FROM clean_parent_stream
WHERE QVADCMALTRT IS NULL
  AND RELATIONSHIP_TO_SELF IN ('Self')
  AND (
      LEFT(PROGRAM_STREAM_CODE, 4) IN ('AD71', 'AD11', 'AD20', 'AD50', 'AD80')
      OR PROGRAM_STREAM_CODE IN ('AODTSCOU5', 'AODTSCRC5', 'AODTSNRW5')
  )
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Maltreatment Perpetrator selected and Type of Maltreatment is No maltreatment or Not Stated. Not valid'
FROM clean_parent_stream
WHERE QVADCMALTRT IN ('Not Stated', 'No Maltreatment')
  AND PERPETRATOR IS NOT NULL
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Outcomes K-10 score must be in the range between 10 and 50 to be Valid'
FROM clean_parent_stream
WHERE K10_SCORE IS NULL
  AND OUTCOME_ID IS NOT NULL
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT DISTINCT
    EPISODE_ID, UR, EPISODE_DT, DISCHARGE_DT, SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, PROGRAM_STREAM, PARENT_STREAM_CLEAN,
    'Outcomes K-10 score must be in the range between 10 and 50 to be Valid'
FROM clean_parent_stream
WHERE TRY_TO_NUMBER(K10_SCORE::VARCHAR, 18, 0) IS NOT NULL
  AND (
      TRY_TO_NUMBER(K10_SCORE::VARCHAR, 18, 0) < 10
      OR TRY_TO_NUMBER(K10_SCORE::VARCHAR, 18, 0) > 50
  )
  AND OUTCOME_ID IS NOT NULL
  AND Q_ROW_ID IS NOT NULL

UNION ALL

SELECT
    EPISODE_ID, UR, EPISODE_DT,
    CONTACT_DATE_TIME AS DISCHARGE_DT,
    SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, STREAM AS PROGRAM_STREAM,
    TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        PARENT_STREAM, '- 34301', ''), '- 34303', ''),
        '- 34307', ''), '- 34306', ''), '- 34300', '')) AS PARENT_STREAM,
    'Support Activity must be entered in Direct time and greater than or = to 15 min'
FROM {{ ref('rpt_vadc_fund_data_support_activities') }}
WHERE STREAM = 'Support Activity'
  AND (DIRECT < 15 OR INDIRECT IS NOT NULL)

UNION ALL

SELECT
    EPISODE_ID, UR, EPISODE_DT,
    CONTACT_DATE_TIME AS DISCHARGE_DT,
    SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, STREAM AS PROGRAM_STREAM,
    TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        PARENT_STREAM, '- 34301', ''), '- 34303', ''),
        '- 34307', ''), '- 34306', ''), '- 34300', '')) AS PARENT_STREAM,
    'Support Activity contacts can not be associated with ' || PROGRAM_STREAM
FROM {{ ref('rpt_vadc_fund_data_support_activities') }}
WHERE PROGRAM_STREAM_CODE IN (
    'AODTSCRC5', 'AD50-100', 'AD21-135', 'AD21-136', 'AD21-134',
    'AD21-102', 'AD52-133', 'AD52-132', 'AD52-131', 'AD52-130', 'AD52-116'
)
AND STREAM = 'Support Activity'

UNION ALL

SELECT
    EPISODE_ID, UR, EPISODE_DT,
    CONTACT_DATE_TIME AS DISCHARGE_DT,
    SERVICE, EPISODE_CP, EPISODE_TEAM,
    PROGRAM_STREAM_CODE, STREAM AS PROGRAM_STREAM,
    TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
        PARENT_STREAM, '- 34301', ''), '- 34303', ''),
        '- 34307', ''), '- 34306', ''), '- 34300', '')) AS PARENT_STREAM,
    'Contact Method must be Support Activity'
FROM {{ ref('rpt_vadc_fund_data_support_activities') }}
WHERE STREAM = 'Support Activity'
  AND CONTACT_METHOD != 'Support Activity'