{% snapshot HIST_TRAKCARE_PA_PERSON %}

{{
    config(
        schema='TRAKCARE',
        unique_key='PAPER_ROWID',
        strategy='check',
        check_cols=[
            'PAPER_ID', 'PAPER_NAME', 'PAPER_NAME2', 'PAPER_NAME3', 'PAPER_NAME4',
            'PAPER_SURNAME', 'PAPER_DOB', 'PAPER_ESTDOB', 'PAPER_AGEYR',
            'PAPER_SEX_DR', 'PAPER_BIRTHGENDER_DR', 'PAPER_GENDERIDENTITY_DR',
            'PAPER_PREFGENDERINTERPRETER_DR', 'PAPER_TITLE_DR', 'PAPER_MARITAL_DR',
            'PAPER_DEPENDCHILDREN_DR', 'PAPER_NATION_DR', 'PAPER_RELIGION_DR',
            'PAPER_COUNTRY_DR', 'PAPER_COUNTRY_BIRTH_DR', 'PAPER_OCCUPATION_DR',
            'PAPER_INDIGSTAT_DR', 'PAPER_PREFLANGUAGE_DR', 'PAPER_LANGUAGESPOKENATHOME_DR',
            'PAPER_COMMUNICATIONNEEDS_DR', 'PAPER_LIVINGARRANGEMENT_DR',
            'PAPER_ACCOMSETTING_DR', 'PAPER_CARERAVAILABILITY_DR',
            'PAPER_EMPLOYMENTSTAT_DR', 'PAPER_SOURCEOFINCOME_DR',
            'PAPER_LANGPRIM_DR', 'PAPER_EMAIL', 'PAPER_EMAIL2',
            'PAPER_MOBPHONE', 'PAPER_TELH', 'PAPER_TELO', 'PAPER_SECONDPHONE',
            'PAPER_STNAME', 'PAPER_STNAMELINE1', 'PAPER_ADDRESS2',
            'PAPER_FOREIGNADDRESS', 'PAPER_POSTCODE', 'PAPER_ZIP_DR',
            'PAPER_CITYCODE_DR', 'PAPER_STATECODE_DR', 'PAPER_CITYAREA_DR',
            'PAPER_CT_REGION_DR', 'PAPER_CT_PROVINCE_DR', 'PAPER_CT_HCA_DR',
            'PAPER_CITYBIRTH_DR', 'PAPER_REGIONBIRTH_DR', 'PAPER_PROVINCE_BIRTH_DR',
            'PAPER_DECEASED', 'PAPER_DECEASED_DATE', 'PAPER_DECEASEDTIME',
            'PAPER_NOKNAME', 'PAPER_NOKPHONE', 'PAPER_NOKBUSPHONE',
            'PAPER_NOKTEXT', 'PAPER_NOKADDRESS1', 'PAPER_NOKADDRESS2',
            'PAPER_NOKCITY_DR', 'PAPER_NOKZIP_DR', 'PAPER_NOKCTRLT_DR',
            'PAPER_REMARK', 'PAPER_FEEDBACKCONSENT', 'PAPER_FEEDBACKCONSENTDATE',
            'PAPER_INTERPRETERREQUIRED', 'PAPER_CANLEAVEMESSAGESON',
            'PAPER_APPOINTMENTSMS', 'PAPER_PREFERREDCONTACTMETHOD',
            'PAPER_GOVERNCARDNO', 'PAPER_CONCESSCARDTYPE_DR',
            'PAPER_FREETEXT1', 'PAPER_FREETEXT2', 'PAPER_FREETEXT3',
            'PAPER_FREETEXT4', 'PAPER_FREETEXT5',
            'PAPER_STAYINGPERMANENTLY', 'PAPER_FAMILYDOCTORCLINIC_DR',
            'PAPER_PAPMI_DR', 'PAPER_UPDATEDATE', 'PAPER_UPDATETIME',
            'PAPER_USERUPDATE', 'PAPER_DATEADDED', 'PAPER_USERADDED_DR',
            'PAPER_SOCIALSTATUS_DR', 'PAPER_HCP_DR', 'PAPER_HOSPITAL_DR',
            'PAPER_REFUGEESTATUS_DR', 'PAPER_SOCIALSTATUSLIST',
            'PAPER_GPCONSENT', 'PAPER_SMSCONSENT'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT * FROM {{ source('raw_trakcare', 'PA_PERSON') }}

{% endsnapshot %}