{% snapshot HIST_TRAKCARE_PA_ENQUIRYCONTACT %}
{{
    config(
        unique_key='ENQ_ROWID',
        strategy='check',
        check_cols=[
            'ENQ_FEE', 'ENQ_DATE', 'ENQ_TIME', 'ENQ_TEXT1', 'ENQ_TEXT2',
            'ENQ_TEXT3', 'ENQ_TEXT4', 'ENQ_SEX_DR', 'ENQ_YESNO1', 'ENQ_YESNO2',
            'ENQ_YESNO3', 'ENQ_YESNO4', 'ENQ_CTCP_DR', 'ENQ_CITY_DR',
            'ENQ_REQDESC', 'ENQ_USER_DR', 'ENQ_DURATION', 'ENQ_PAPER_DR',
            'ENQ_ESTIMMINS', 'ENQ_ESTIMTIME', 'ENQ_REQREASON', 'ENQ_DATEUPDATE',
            'ENQ_INSTYPE_DR', 'ENQ_ITEMCAT_DR', 'ENQ_RBEVENT_DR', 'ENQ_TIMEUPDATE',
            'ENQ_TRAVELTIME', 'ENQ_CITYAREA_DR', 'ENQ_CONTTIMEBHR', 'ENQ_CONTACTNAME',
            'ENQ_CONTACTTYPE', 'ENQ_HOSPITAL_DR', 'ENQ_LOCATION_DR', 'ENQ_PICTURES_DR',
            'ENQ_RESOURCE_DR', 'ENQ_CONTVENUE_DR', 'ENQ_INDIRECTTIME', 'ENQ_NONGOVORG_DR',
            'ENQ_OEORDITEM_DR', 'ENQ_VOLUNTEERSER', 'ENQ_ACTIONDETAILS', 'ENQ_AUXINSTYPE_DR',
            'ENQ_CONTMETHOD_DR', 'ENQ_CONTACTNUMBER', 'ENQ_INPATIENTFLAG', 'ENQ_URGENTCONTACT',
            'ENQ_CONTOUTCOME_DR', 'ENQ_REQUESTTYPE_DR', 'ENQ_WAITINGLIST_DR',
            'ENQ_CONSULTCATEG_DR', 'ENQ_GOVERNDEPART_DR', 'ENQ_RBEVENTTIMES_DR',
            'ENQ_CONTDELIVMODE_DR', 'ENQ_CONTLOCALGOAL_DR', 'ENQ_INTERPRETINGTIME',
            'ENQ_REQUESTSTATUS_DR', 'ENQ_CONTWORKERTYPE_DR', 'ENQ_DISTANCETRAVELLED',
            'ENQ_VARIANCEREASON_DR', 'ENQ_CAREPROVIDERGROUPS', 'ENQ_CONTSERVICEREC2_DR',
            'ENQ_CONTSESSIONTYPE_DR', 'ENQ_VARIANCEREASONTEXT', 'ENQ_CONTDELIVSETTING_DR',
            'ENQ_INTERPRETERREQUIRED', 'ENQ_SOURCEOFREFERRAL_DR', 'ENQ_CONTACTINTERVENTIONS',
            'ENQ_SERVICETYPEOUTLET_DR', 'ENQ_CONTCLIENTPRESSTAT_DR', 'ENQ_CONTINTERPRETERTYPE_DR'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT *
FROM {{ source('raw_trakcare', 'PA_ENQUIRYCONTACT') }}
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ENQ_ROWID
    ORDER BY ENQ_DATEUPDATE DESC NULLS LAST,
             ENQ_TIMEUPDATE DESC NULLS LAST
) = 1

{% endsnapshot %}