{% snapshot HIST_TRAKCARE_QAUXXADOUT %}
{{
    config(
        unique_key='ID',
        strategy='check',
        check_cols=[
            'QUESDATE', 'QUESTIME', 'QUESANADR', 'QUESSCORE', 'QUESUSERDR',
            'QUESPAADMDR', 'QVADCOUTK10', 'QUESSTATUSDR', 'QVADCOUTDATE',
            'QVADCOUTEMPL', 'QUESCONSULTDR', 'QVADCOUTACCOM', 'QVADCOUTAUDIT',
            'QVADCOUTDUDIT', 'QVADCOUTSTUDY', 'QUESCOPIEDDATE', 'QUESCOPIEDEPDR',
            'QUESCOPIEDTIME', 'QUESCREATEDATE', 'QUESCREATETIME', 'QUESOBSENTRYDR',
            'QUESOPERROOMDR', 'QUESPAPATMASDR', 'QVADCOUTARREST', 'QUESOEORDEXECDR',
            'QVADCOUTINJDAYS', 'QVADCOUTQTYLIFE', 'QVADCOUTRISKOTH', 'QVADCOUTVIOLENT',
            'QUESCOPIEDUSERDR', 'QUESCREATEUSERDR', 'QUESFHRESIDENTDR', 'QUESRBAPPTSLOTDR',
            'QUESSECONDUSERDR', 'QUESTEXTRESULTDR', 'QVADCOUTARREST14', 'QVADCOUTK10OBSDR',
            'QVADCOUTPHYSHLTH', 'QVADCOUTRISKSELF', 'QUESERRORREASONDR', 'QUESPAPREGNANCYDR',
            'QUESPATHWAYITEMDR', 'QUESTRANSACTIONDR', 'QVADCOUTEMPLOBSDR', 'QVADCOUTPSYCHHLTH',
            'QVADCOUTQTYLIFE14', 'QVADCOUTRISKOTH14', 'QVADCOUTVIOLENT14', 'QVADCOUTVIOLENTV2',
            'QUESANAOPERATIONDR', 'QUESCOPIEDCOMMENTS', 'QUESCOPIEDSOURCEDR', 'QVADCOUTACCOMOBSDR',
            'QVADCOUTAUDITOBSDR', 'QVADCOUTDUDITOBSDR', 'QVADCOUTPHYSHLTH14', 'QVADCOUTRISKSELF14',
            'QVADCOUTSTUDYOBSDR', 'QUESPAWAITINGLISTDR', 'QUESRBAPPOINTMENTDR', 'QUESRBAPPTOUTCOMEDR',
            'QVADCOUTARRESTOBSDR', 'QVADCOUTPSYCHHLTH14', 'QUESPAADVERSEEVENTDR',
            'QVADCOUTINJDAYSOBSDR', 'QVADCOUTQTYLIFEOBSDR', 'QVADCOUTRISKOTHOBSDR',
            'QVADCOUTVIOLENTOBSDR', 'QUESSSUSERDEFWINDOWDR', 'QVADCOUTPHYSHLTHOBSDR',
            'QVADCOUTRISKSELFOBSDR', 'QUESNRCAREPLANISSUESDR', 'QVADCOUTPSYCHHLTHOBSDR',
            'QVADCOUTVIOLENTV2OBSDR', 'QUESMRCLINICALPATHWAYSDR', 'QUESREASONFORCORRECTIONDR',
            'QUESPREPOSTEXAMOEORDITEMDR', 'QUESORPREANAESTHETICCONSULTDR'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}
SELECT * FROM {{ source('raw_trakcare', 'QAUXXADOUT') }}
{% endsnapshot %}