{% snapshot HIST_TRAKCARE_QAUXXADVADC %}

{{
    config(
        schema='TRAKCARE',
        unique_key='ID',
        strategy='check',
        check_cols=[
            'QUESPAADMDR', 'QUESPAPATMASDR', 'QUESDATE', 'QUESTIME',
            'QUESSCORE', 'QUESSSUSERDEFWINDOWDR', 'QUESUSERDR',
            'QUESOEORDEXECDR', 'QUESMRCLINICALPATHWAYSDR', 'QUESCREATEDATE',
            'QUESCREATETIME', 'QUESCREATEUSERDR', 'QUESSTATUSDR',
            'QUESTEXTRESULTDR', 'QUESCONSULTDR', 'QUESOPERROOMDR',
            'QUESFHRESIDENTDR', 'QUESPATHWAYITEMDR', 'QUESPAWAITINGLISTDR',
            'QVADCOUTCODE', 'QVADCABI', 'QVADCLGB', 'QVADCMALTRT',
            'QVADCMALPERP', 'QVADCMHDIAG', 'QVADCBIRTHSEX', 'QVADCGENDREAS',
            'QVADCFORTYP', 'QVADCMASCOT', 'QVADCPRESDRUGOC', 'QVADCDELSET',
            'QVADCSIGGOAL', 'QVADCTIER', 'QVADCCRSLEN', 'QVADCFIRSTREG',
            'QVADCPERCOMP', 'QVADCASSESSCOMP', 'QVADCTARGPOP', 'QVADCMARAM',
            'QVADCFAMVIOLENCE', 'QVADCMALPERP1', 'QVADCMHDIAG1',
            'QUESCOPIEDEPDR', 'QUESCOPIEDUSERDR', 'QUESCOPIEDDATE',
            'QUESCOPIEDTIME', 'QUESCOPIEDCOMMENTS', 'QUESREASONFORCORRECTIONDR',
            'QUESERRORREASONDR', 'QUESNRCAREPLANISSUESDR', 'QUESRBAPPOINTMENTDR',
            'QUESANADR', 'QUESANAOPERATIONDR', 'QUESCOPIEDSOURCEDR',
            'QUESTRANSACTIONDR', 'QUESOBSENTRYDR', 'QUESPAPREGNANCYDR',
            'QUESPREPOSTEXAMOEORDITEMDR', 'QUESORPREANAESTHETICCONSULTDR',
            'QUESRBAPPTOUTCOMEDR', 'QUESRBAPPTSLOTDR', 'QUESSECONDUSERDR',
            'QUESPAADVERSEEVENTDR'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_trakcare', 'QAUXXADVADC') }}

{% endsnapshot %}