{% snapshot HIST_TRAKCARE_ARC_INSURANCETYPE %}
{{ config(unique_key='INST_ROWID', strategy='check',
    check_cols=['INST_CODE','INST_DESC','INST_CODE1','INST_CODE2','INST_CODE3',
        'INST_CODE4','INST_OWNER','INST_DATETO','INST_CARETYPE','INST_CATEGORY',
        'INST_DATEFROM','INST_MULTIPART','INST_PAYMODE_DR','INST_CREATEDDATE',
        'INST_CREATEDTIME','INST_PRIORITY_DR','INST_UPDATEDDATE','INST_UPDATEDTIME',
        'INST_ACCOUNTCLASS','INST_BILLINGLOGIC','INST_INSBATCHONLY',
        'INST_CODETABLETAGS','INST_PAYORGROUP_DR','INST_CODETRANSLATED',
        'INST_COMPANYADDRESS','INST_CREATEDUSER_DR','INST_DESCTRANSLATED',
        'INST_LINKINSTYPE_DR','INST_UNQUALIFIEDADM','INST_UPDATEDUSER_DR',
        'INST_REPORTONSETCODE','INST_SPLITBILLSBYLOC','INST_DONOTDEFAULTCOPY',
        'INST_ACCOMMODATIONTYPE','INST_DRGGROUPERVERSION_DR',
        'INST_DEFAULTAUXINSTYPE_DR','INST_PROGRAMFUNDINGSOURCE',
        'INST_REPORTPRIVATEROOMADDON'],
    invalidate_hard_deletes=True, dbt_valid_to_current="to_date('9999-12-31')") }}
SELECT * FROM {{ source('raw_trakcare', 'ARC_INSURANCETYPE') }}
{% endsnapshot %}