{% snapshot HIST_TRAKCARE_CT_HOSPITAL %}
{{
    config(
        unique_key='HOSP_ROWID',
        strategy='check',
        check_cols=[
            'HOSP_FAX', 'HOSP_CITY', 'HOSP_CODE', 'HOSP_DESC', 'HOSP_LOGO',
            'HOSP_EMAIL', 'HOSP_OWNER', 'HOSP_PHONE', 'HOSP_STATE',
            'HOSP_ZIPDR', 'HOSP_DATETO', 'HOSP_EMAIL1', 'HOSP_ISLAND',
            'HOSP_ADDRESS', 'HOSP_NEWWAYS', 'HOSP_DATEFROM', 'HOSP_MHACT_DR',
            'HOSP_TIMEZONE', 'HOSP_TRUST_DR', 'HOSP_BILLNO_DR',
            'HOSP_CARETYPES', 'HOSP_REGION_DR', 'HOSP_TARIFF_DR',
            'HOSP_COUNTRY_DR', 'HOSP_FACILITYID', 'HOSP_APPLYVCFEES',
            'HOSP_BANKACCOUNT', 'HOSP_BILLADDRESS', 'HOSP_CREATEDDATE',
            'HOSP_CREATEDTIME', 'HOSP_PROVINCE_DR', 'HOSP_UPDATEDDATE',
            'HOSP_UPDATEDTIME', 'HOSP_BANKACCOUNT1', 'HOSP_NATIONALCODE',
            'HOSP_SUBREGION_DR', 'HOSP_CLAIMTYPECODE', 'HOSP_CODETABLETAGS',
            'HOSP_DEBTORCONTROL', 'HOSP_POSTOFFICE_DR', 'HOSP_CODETRANSLATED',
            'HOSP_CREATEDUSER_DR', 'HOSP_DESCTRANSLATED', 'HOSP_FAXSERVEREMAIL',
            'HOSP_ORGANIZATIONID', 'HOSP_UNALLOCPAYMENT', 'HOSP_UPDATEDUSER_DR',
            'HOSP_USESAMECOUNTER', 'HOSP_ACCRUALSCONTROL', 'HOSP_COUNTYPARISH_DR',
            'HOSP_CREDITNOTENO_DR', 'HOSP_DAYSFOROPDOFFER', 'HOSP_FACILITYTYPE_DR',
            'HOSP_HOSPDRGCATEG_DR', 'HOSP_MEDICALDIRECTOR', 'HOSP_INSURANCETYPE_DR',
            'HOSP_PAYORAPPROVALREQ', 'HOSP_GUARANTORGROUP_DR', 'HOSP_PBSFACILITYNUMBER',
            'HOSP_APPLYDRGOUTLIERCALC', 'HOSP_CPGROUPAFFILIATIONS',
            'HOSP_POSESSIONCOUNTER_DR', 'HOSP_MANDATORYREFHOSPITAL',
            'HOSP_ASSIGNEDGROUPCATEGORY', 'HOSP_PBSDISPENSINGRULELIST',
            'HOSP_PROCANAESTHETICORDERS', 'HOSP_SHOWAPPWTIMEVIOLATION',
            'HOSP_WEEKSSUSPENSIONREVIEW', 'HOSP_DAYSOFFEROUTCOMECHANGE',
            'HOSP_WARNSAMESERVICEWNXDAYS', 'HOSP_DAYSFOROPLETTERRESPONSE',
            'HOSP_EPTYPEMEDDISBEFOREFINDIS', 'HOSP_OFFERSBEFOREIP_OPWAITRESET'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}
SELECT * FROM {{ source('raw_trakcare', 'CT_HOSPITAL') }}
{% endsnapshot %}