{% snapshot HIST_TRAKCARE_OE_ORDITEM2 %}
{{
    config(
        schema='TRAKCARE',
        unique_key='ITM2_ROWID',
        strategy='check',
        check_cols=[
            'ITM2_PARREF', 'ITM2_CHILDSUB', 'ITM2_NFMICATEGDEPART_DR',
            'ITM2_ACTIVITYTYPE_DR', 'ITM2_RESOURCE_DR', 'ITM2_REASONBRANDSUBS_DR',
            'ITM2_SUBSCOMMENTS', 'ITM2_REQUESTEDDATE', 'ITM2_REQUESTEDTIME',
            'ITM2_DONOTSUBSTITUTE', 'ITM2_TOBILLDATE', 'ITM2_ACCOUNTPERIOD_DR',
            'ITM2_LOANEQUIPRETDATE', 'ITM2_LOSTLOANITEM', 'ITM2_EXTCODE',
            'ITM2_DELIVERYRATE', 'ITM2_DELIVERYUOM_DR', 'ITM2_COMPLETIONDATE',
            'ITM2_FINANCEAPPROVED', 'ITM2_PAYORAPPRSTATUS', 'ITM2_FINAPPRLASTUPDATEDATE',
            'ITM2_FINAPPRLASTUPDATETIME', 'ITM2_FINAPPRLASTUPDATEUSER_DR',
            'ITM2_FINANCEAPPRVCOMMENTS', 'ITM2_FINANCEAPPROVEDOVERRIDE',
            'ITM2_PAADVERSEEVENT_DR', 'ITM2_EXPIRYDATE', 'ITM2_PATIENTWEIGHT',
            'ITM2_YESNO5', 'ITM2_YESNO6', 'ITM2_YESNO7', 'ITM2_YESNO8', 'ITM2_YESNO9',
            'ITM2_SUBSDATE', 'ITM2_SUBSTIME', 'ITM2_SUBSUSER_DR', 'ITM2_SUBSTYPE',
            'ITM2_EXTERNALPRESCRIPTIONID', 'ITM2_REVIEWSTATUS_DR', 'ITM2_REASONFORMODIFIC_DR',
            'ITM2_REASONFORVARIANCE', 'ITM2_PROSDESC', 'ITM2_PROSCATALOGNO',
            'ITM2_PROSPARTNO', 'ITM2_PROSUSED', 'ITM2_PROSREBATECODE',
            'ITM2_PRESCRIBEDAS_DR', 'ITM2_DURATIONVALUE', 'ITM2_DURATIONUNIT',
            'ITM2_EVENT', 'ITM2_ORDERVERSION', 'ITM2_DURATIONTYPE',
            'ITM2_FINDATE', 'ITM2_INSTRUCTIONS', 'ITM2_PATIENTHEIGHT',
            'ITM2_SERVICETEXT', 'ITM2_DERIVED', 'ITM2_CONFIDENTIAL',
            'ITM2_TREATMENTLOCCDE', 'ITM2_OVERRIDEORDERLINENAME',
            'ITM2_MEDICATION_DR', 'ITM2_ENTEREDINERROR',
            'ITM2_AUTHORITYCODE', 'ITM2_AUTHORITYNUMBER',
            'ITM2_PBSNONPBSFLAG', 'ITM2_PBSAUTHORITYNUMBER',
            'ITM2_RENDERINGDATE', 'ITM2_RENDERINGTIME',
            'ITM2_TELECONSULT', 'ITM2_INDICATION',
            'ITM2_PRNFLAG', 'ITM2_DISPENSETYPE'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}
SELECT * FROM {{ source('raw_trakcare', 'OE_ORDITEM2') }}
{% endsnapshot %}