{% snapshot HIST_TRAKCARE_ARC_ITMMAST %}

{{
    config(
        schema='TRAKCARE',
        unique_key='ARCIM_ROWID',
        strategy='check',
        check_cols=[
            'ARCIM_CAPD', 'ARCIM_CODE', 'ARCIM_DAYS', 'ARCIM_DESC',
            'ARCIM_OWNER', 'ARCIM_TEXT1', 'ARCIM_TEXT2', 'ARCIM_TEXT3',
            'ARCIM_TEXT4', 'ARCIM_TEXT5', 'ARCIM_TYPE1', 'ARCIM_TYPE2',
            'ARCIM_ABBREV', 'ARCIM_EXPLOS', 'ARCIM_MAXAMT', 'ARCIM_MAXQTY',
            'ARCIM_MINAMT', 'ARCIM_NONMBS', 'ARCIM_OTHERG', 'ARCIM_RVPFUD',
            'ARCIM_RVPUPD', 'ARCIM_STDAMT', 'ARCIM_UOM_DR', 'ARCIM_CHGCOST',
            'ARCIM_EFFDATE', 'ARCIM_EFFTIME', 'ARCIM_MINTIME', 'ARCIM_MINUTES',
            'ARCIM_RBNOTES', 'ARCIM_RANGETO', 'ARCIM_RVPANES', 'ARCIM_SAMEDAY',
            'ARCIM_SUGARSG', 'ARCIM_VERSION', 'ARCIM_DMDLEVEL', 'ARCIM_DAYBAND1',
            'ARCIM_DOSETYPE', 'ARCIM_ENERGYKJ', 'ARCIM_HAEMODAL', 'ARCIM_LOANITEM',
            'ARCIM_MAXPRICE', 'ARCIM_MINPRICE', 'ARCIM_NOCHARGE', 'ARCIM_OINTMENT',
            'ARCIM_PHCDF_DR', 'ARCIM_PHCPA_DR', 'ARCIM_PROTEING', 'ARCIM_ROW_CALC',
            'ARCIM_SODIUMMG', 'ARCIM_TYPEAAMT', 'ARCIM_TYPEBAMT', 'ARCIM_AUTOORDER',
            'ARCIM_CHGMAXAMT', 'ARCIM_CHGMINAMT', 'ARCIM_CURVERFLG', 'ARCIM_DRESSTIME',
            'ARCIM_EFFDATETO', 'ARCIM_ENERGYCAL', 'ARCIM_FILENOTES', 'ARCIM_FORMULARY',
            'ARCIM_INSCODESC', 'ARCIM_OEMESSAGE', 'ARCIM_P1CHGFACT', 'ARCIM_P2CHGFACT',
            'ARCIM_P3CHGFACT', 'ARCIM_P4CHGFACT', 'ARCIM_PROCEDURE', 'ARCIM_RANGEFROM',
            'ARCIM_SENSITIVE', 'ARCIM_SHORTDESC', 'ARCIM_SINGLEFEE', 'ARCIM_SNACKFLAG',
            'ARCIM_SUBMASFLG', 'ARCIM_SUBSCRIPT', 'ARCIM_TOTALFATG', 'ARCIM_TYPE_CALC',
            'ARCIM_BILLSUB_DR', 'ARCIM_CHGDISPFLG', 'ARCIM_CHGPOSTFLG', 'ARCIM_CURVERS_DR',
            'ARCIM_DMDFORM_DR', 'ARCIM_DRGMAST_DR', 'ARCIM_EXPIRYDAYS', 'ARCIM_GENERIC_DR',
            'ARCIM_ITEMCAT_DR', 'ARCIM_MAXCUMDOSE', 'ARCIM_PROFILEFLG', 'ARCIM_REBATECODE',
            'ARCIM_RESTRICTEM', 'ARCIM_RESTRICTHP', 'ARCIM_RESTRICTIP', 'ARCIM_RESTRICTOP',
            'ARCIM_SERVCAT_DR', 'ARCIM_SERVTAX_DR', 'ARCIM_TIMEDEPFLG', 'ARCIM_UPDATEDATE',
            'ARCIM_UPDATETIME', 'ARCIM_UPDATEUSER', 'ARCIM_ANAESTHETIC', 'ARCIM_CHGUNITFACT',
            'ARCIM_CONSULTDEPT', 'ARCIM_CREATEDDATE', 'ARCIM_CREATEDTIME', 'ARCIM_DMDVOLUMEML',
            'ARCIM_EFFDATETIME', 'ARCIM_EPISODETYPE', 'ARCIM_GENERICDESC', 'ARCIM_ISDRUGDBAPI',
            'ARCIM_MEALTYPE_DR', 'ARCIM_NOOFCUMDAYS', 'ARCIM_P1STDADDAMT', 'ARCIM_P2STDADDAMT',
            'ARCIM_P3STDADDAMT', 'ARCIM_P4STDADDAMT', 'ARCIM_REQAPPROVAL', 'ARCIM_RESULTGROUP',
            'ARCIM_RICETYPE_DR', 'ARCIM_ROOMTYPE_DR', 'ARCIM_RVPUNITSTAT', 'ARCIM_UPDATEDDATE',
            'ARCIM_UPDATEDTIME', 'ARCIM_BILLBODYP_DR', 'ARCIM_BILLINGLOGIC', 'ARCIM_DIETRYFIBREG',
            'ARCIM_INCSOURCE_DR', 'ARCIM_INSSUBCAT_DR', 'ARCIM_KIDNEYTRANSP', 'ARCIM_MANUFACTURED',
            'ARCIM_MAXQTYPERDAY', 'ARCIM_NOTHEATREREQ', 'ARCIM_P1TYPAADDAMT', 'ARCIM_P1TYPBADDAMT',
            'ARCIM_P2TYPAADDAMT', 'ARCIM_P2TYPBADDAMT', 'ARCIM_P3TYPAADDAMT', 'ARCIM_P3TYPBADDAMT',
            'ARCIM_P4TYPAADDAMT', 'ARCIM_P4TYPBADDAMT', 'ARCIM_SERVMATERIAL', 'ARCIM_SURCHARGE_DR',
            'ARCIM_WORDTEMPLATE', 'ARCIM_ADMINROUTE_DR', 'ARCIM_BILLINGUOM_DR', 'ARCIM_CHARGEPARTIAL',
            'ARCIM_CODETABLETAGS', 'ARCIM_COMMISSIONING', 'ARCIM_DMDGENERIC_DR', 'ARCIM_DISABLEYESNO1',
            'ARCIM_DISABLEYESNO2', 'ARCIM_DISABLEYESNO3', 'ARCIM_DISABLEYESNO4', 'ARCIM_EXPANAESTTIME',
            'ARCIM_HL7RESULTTYPE', 'ARCIM_LATERALITYREQ', 'ARCIM_LETTERTYPE_DR', 'ARCIM_NONREVIEWABLE',
            'ARCIM_ORDERONITSOWN', 'ARCIM_QUESMANDATORY', 'ARCIM_RMDURATION_DR', 'ARCIM_SEQUENCEORDER',
            'ARCIM_CARBOHYDRATESG', 'ARCIM_CODETRANSLATED', 'ARCIM_COMPSERVICE_DR', 'ARCIM_CREATEDUSER_DR',
            'ARCIM_DMDSTRENGTH_DR', 'ARCIM_DEDUCTIBLEITEM', 'ARCIM_DEFPRIORITY_DR', 'ARCIM_DENTALSTATE_DR',
            'ARCIM_DERFEERULES_DR', 'ARCIM_DERIVEDFEEITEM', 'ARCIM_DESCTRANSLATED', 'ARCIM_DRGFORMPACK_DR',
            'ARCIM_EREFITEMSCYCLE', 'ARCIM_RMFREQUENCY_DR', 'ARCIM_REMOTEDUTYTYPE', 'ARCIM_REVIEWREQUIRED',
            'ARCIM_RVPINTERIMYEAR', 'ARCIM_SATURATEDFATSG', 'ARCIM_SENSITIVEORDER', 'ARCIM_SNOMEDTERMS_DR',
            'ARCIM_UPDATEDUSER_DR', 'ARCIM_USEODBCFORWORD', 'ARCIM_ANAESTMETHOD_DR', 'ARCIM_ANAESTPROCEDURE',
            'ARCIM_BILLDESCRIPTION', 'ARCIM_CHGORDERPERHOUR', 'ARCIM_DIRECTLYEXECUTE', 'ARCIM_DOSECALCFORMULA',
            'ARCIM_EREFUNIQUEPRESC', 'ARCIM_EPISODICBILLING', 'ARCIM_PROCESSINGNOTES', 'ARCIM_REORDERONITSOWN',
            'ARCIM_SERVICEGROUP_DR', 'ARCIM_TESTITEMSEQUNCE', 'ARCIM_EXTERNALLOANDAYS', 'ARCIM_INTERNALLOANDAYS',
            'ARCIM_OUTPBILLINGLOGIC', 'ARCIM_PAYORICDGROUP_DR', 'ARCIM_QUESTIONNAIRE_DR', 'ARCIM_RESULTCATEGORIES',
            'ARCIM_SERVICECHARGE_DR', 'ARCIM_SNOMEDCONCEPT_DR', 'ARCIM_USERDEFWINDOW_DR', 'ARCIM_ADMINQUESTIONN_DR',
            'ARCIM_ANAESTPROCBILLING', 'ARCIM_BILLPARTIALPACKEM', 'ARCIM_BILLPARTIALPACKIP', 'ARCIM_BILLPARTIALPACKOP',
            'ARCIM_DISPLAYCUMULATIVE', 'ARCIM_EREFCOMPATIBILITY', 'ARCIM_EREFINCLUDEDCODES', 'ARCIM_EMERGBILLINGLOGIC',
            'ARCIM_EXTERNALSERVICEID', 'ARCIM_GLPOSTTOORDERDEPT', 'ARCIM_MODIFIERSREQUIRED', 'ARCIM_PATIENTORDERFILE1',
            'ARCIM_PATIENTORDERFILE2', 'ARCIM_PATIENTORDERFILE3', 'ARCIM_ADMIXTURERECIPE_DR', 'ARCIM_BILLBYTARIFFPRICES',
            'ARCIM_BILLONADMNSTREMERG', 'ARCIM_BILLONADMNSTRINPAT', 'ARCIM_CLINICALCONDITIONS', 'ARCIM_DAYSCHECKDUPLICATE',
            'ARCIM_DIAGNOSTICWAITTIME', 'ARCIM_EREFNONCOMPATITEMS', 'ARCIM_EXCLUDEFROMGRPWARN', 'ARCIM_MAXWEEKSAFTERONSET',
            'ARCIM_MINWEEKSAFTERONSET', 'ARCIM_PRERECOVERYTIMEMIN', 'ARCIM_SERVICEPRIORITY_DR', 'ARCIM_VISIBLEINORDERLIST',
            'ARCIM_BILLONADMNSTROUTPAT', 'ARCIM_DISCHPRIORITYBUP_DR', 'ARCIM_OBSERVATIONGROUP_DR', 'ARCIM_PRERECOVERYTIMETYPE',
            'ARCIM_PRICECOSTONORDERING', 'ARCIM_ADDTODIAGNOSTICSTAGE', 'ARCIM_AUTHORISINGCLINICIAN', 'ARCIM_BEDREASONNOTAVAIL_DR',
            'ARCIM_DECEASEDPATIENTSONLY', 'ARCIM_DEFAULTTOTELECONSULT', 'ARCIM_EREFPRESCWEIGHFACTOR', 'ARCIM_PHONEORDERREVIEWTIME',
            'ARCIM_RESULTDISPLAYGROUPDR', 'ARCIM_ADJUSTEDPROCEDURETIME', 'ARCIM_ORDMONITOROBSGROUP_DR', 'ARCIM_REFELIGIBILITYRULE_DR',
            'ARCIM_REFERRALACCESSTYPE_DR', 'ARCIM_ALLOWORDERWOSTOCKCHECK', 'ARCIM_CREATEINPATIENTEPISODE'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_trakcare', 'ARC_ITMMAST') }}

{% endsnapshot %}