{% snapshot HIST_TRAKCARE_PAC_CONTSERVICEREC2 %}
{{ config(unique_key='CONTSERREC2_ROWID', strategy='check',
    check_cols=['CONTSERREC2_CODE','CONTSERREC2_DESC','CONTSERREC2_OWNER',
        'CONTSERREC2_DATETO','CONTSERREC2_DATEFROM','CONTSERREC2_CREATEDDATE',
        'CONTSERREC2_CREATEDTIME','CONTSERREC2_UPDATEDDATE','CONTSERREC2_UPDATEDTIME',
        'CONTSERREC2_CODETABLETAGS','CONTSERREC2_CREATEDUSER_DR',
        'CONTSERREC2_UPDATEDUSER_DR'],
    invalidate_hard_deletes=True, dbt_valid_to_current="to_date('9999-12-31')") }}
SELECT * FROM {{ source('raw_trakcare', 'PAC_CONTSERVICEREC2') }}
{% endsnapshot %}