{% snapshot HIST_TRAKCARE_PA_ADMINSURANCE %}

{{
    config(
        schema='TRAKCARE',
        unique_key='INS_ROWID',
        strategy='check',
        check_cols=[
            'INS_PARREF', 'INS_CHILDSUB', 'INS_INSTYPE_DR', 'INS_INSASSOC_DR',
            'INS_DATEVALIDFROM', 'INS_DATEVALIDTO', 'INS_DATEFIRSTHAVEINSUR',
            'INS_CARDNO', 'INS_CARDHOLDERNAME', 'INS_CARDHOLDERID',
            'INS_CTREL_DR', 'INS_AUXINSTYPE_DR', 'INS_CONTACTINSURCO',
            'INS_APPROVEDGUARDATE', 'INS_ACCIDENTDATE', 'INS_CARREGONO',
            'INS_CASECLAIMNO', 'INS_NOTIFICATIONDATE', 'INS_ESTIMIPSTARTDATE',
            'INS_ESTIMIPENDDATE', 'INS_ESTIMOPSTARTDATE', 'INS_ESTIMOPENDDATE',
            'INS_DATETYPEFROM', 'INS_DATETYPETO', 'INS_MAININSURANCEFLAG',
            'INS_CARDHOLDERADDRESS', 'INS_CARDHOLDERCITY_DR', 'INS_CARDHOLDERZIP_DR',
            'INS_RANK', 'INS_AUTHORIZATIONCODE', 'INS_DAILYCOVER',
            'INS_TOTALCHARGECOVER', 'INS_STAMPDUTYPERCENTAGE', 'INS_EXCESS',
            'INS_DAILYICUCOVER', 'INS_PAYORSHARE', 'INS_PAYFROM', 'INS_PAYUNTILL',
            'INS_FIXEDPATSHARE', 'INS_CARDTYPE_DR', 'INS_CONCESSIONCARDNO',
            'INS_CONCESSIONCARDEXPDATE', 'INS_SAFETYNETCARDNO',
            'INS_SAFETYNETCARDEXPDATE', 'INS_PAYORCONTACTTYPE_DR', 'INS_DVANUMBER',
            'INS_DAILYCOPAYMENTAMT', 'INS_MAXCOPAYMENTAMT', 'INS_APPLYGST',
            'INS_SHAREDROOMCOPAYMENTAMT', 'INS_TIMEFROM', 'INS_TIMETO',
            'INS_UPDATEDATE', 'INS_UPDATETIME', 'INS_UPDATEUSER_DR',
            'INS_UPDATEUSERHOSPITAL_DR', 'INS_PAYORVARIATIONCOMMENTS',
            'INS_CARDINITDATE', 'INS_USEOWNTARIFF', 'INS_SURMOUNTINGPERCENTAGE',
            'INS_SURMOUNTINGLIMIT', 'INS_SURMOUNTINGAMOUNT', 'INS_COPAYMENTPERCENTAGE',
            'INS_MAXAMOUNTPERCENTAGE', 'INS_MINSURMOUNTAMT', 'INS_OFFICENO',
            'INS_ROYALORDERNO', 'INS_ROYALORDER_DR', 'INS_ACCOMRATE',
            'INS_VCFEERATE', 'INS_MAXDAILYAMOUNT', 'INS_APPLYSHARETOTALAMOUNT',
            'INS_COPIEDINS_DR', 'INS_PERSONPACKAGE_DR', 'INS_ROOMTYPE_DR',
            'INS_AUTOASSIGNEDFLG', 'INS_ADMINCATEGORY_DR', 'INS_COMMREPORTEDDATE',
            'INS_COMPENSATIONCLAIM', 'INS_MAXCOPAYMENTDAYS', 'INS_DAILYPRIVROOMCOPAYMENT',
            'INS_MAXPRIVROOMCOPAYMENTDAYS', 'INS_SAMEDAYCOPAYMENT', 'INS_THEATRECOPAYMENT',
            'INS_LASTVERIFIEDDATE', 'INS_TYPEOFPOLICY', 'INS_COORDINATIONOFBENEFITS',
            'INS_PRECERTIFICATIONREQUIREMENT', 'INS_BILLSERVICETAXTOPATIENT',
            'INS_GROUPNUMBER', 'INS_GROUPNAME', 'INS_BILLINGMETHOD_DR',
            'INS_BENEFITPACKAGE_DR', 'INS_INSURANCESTATUS_DR'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_trakcare', 'PA_ADMINSURANCE') }}

{% endsnapshot %}