{% snapshot HIST_TRAKCARE_PAC_CONTDELIVMODE %}
{{ config(unique_key='CONTDELMODE_ROWID', strategy='check',
    check_cols=['CONTDELMODE_CODE','CONTDELMODE_DESC','CONTDELMODE_OWNER',
        'CONTDELMODE_DATETO','CONTDELMODE_DATEFROM','CONTDELMODE_CREATEDDATE',
        'CONTDELMODE_CREATEDTIME','CONTDELMODE_UPDATEDDATE','CONTDELMODE_UPDATEDTIME',
        'CONTDELMODE_CODETABLETAGS','CONTDELMODE_CREATEDUSER_DR',
        'CONTDELMODE_UPDATEDUSER_DR'],
    invalidate_hard_deletes=True, dbt_valid_to_current="to_date('9999-12-31')") }}
SELECT * FROM {{ source('raw_trakcare', 'PAC_CONTDELIVMODE') }}
{% endsnapshot %}