{% snapshot HIST_TRAKCARE_RB_APPTSCHEDULE %}
{{
    config(
        schema='TRAKCARE',
        unique_key='AS_ROWID',
        strategy='check',
        check_cols=[
            'AS_RES_PARREF', 'AS_CHILDSUB', 'AS_DATE', 'AS_SESSION',
            'AS_SESSSTARTTIME', 'AS_SESSENDTIME', 'AS_NOAPPTSESSION',
            'AS_LOAD', 'AS_AVAILABILITY', 'AS_NUMPATIN', 'AS_NUMPATOUT',
            'AS_REMARKS', 'AS_SLOT', 'AS_QUEUENOCOUNT', 'AS_BOOKEDSLOTS',
            'AS_RBEFFDATESESSION_DR', 'AS_IRREGULARFLAG', 'AS_SESSIONTYPE_DR',
            'AS_ACTUALDATE', 'AS_ACTUALSTARTTIME', 'AS_ACTUALENDTIME',
            'AS_REASONFORDELAY_DR', 'AS_REASONFOROVERTIME_DR',
            'AS_GENERATIONDATE', 'AS_GENERATIONTIME', 'AS_LASTUPDATEUSER_DR',
            'AS_LASTUPDATEDATE', 'AS_LASTUPDATETIME', 'AS_NOTAVAILABLESLOT',
            'AS_OPDROOM_DR', 'AS_DAYCLINICOPTIONS', 'AS_WEBGENERATED',
            'AS_APPTLOC_DR', 'AS_EMERGENCYTHEATRE', 'AS_OPERBOOKINGMETHOD',
            'AS_NOMOREBOOKINGS', 'AS_ORIGSESSSTARTTIME', 'AS_ORIGSESSENDTIME',
            'AS_APPTLOCALL', 'AS_AUTOREQ', 'AS_OTSESSORIGINFLAG',
            'AS_BRIEFNOTREQUIRED', 'AS_DONTREINSTATEFLAG', 'AS_OTROOMSTATUS',
            'AS_REASONBRIEFNOTREQUIRED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}
SELECT * FROM {{ source('raw_trakcare', 'RB_APPTSCHEDULE') }}
{% endsnapshot %}