{% snapshot HIST_TRAKCARE_RB_RESOURCE %}
{{
    config(
        unique_key='RES_ROWID',
        strategy='check',
        check_cols=[
            'RES_CTLOC_DR', 'RES_CTPCP_DR', 'RES_EQ_DR', 'RES_CODE',
            'RES_DESC', 'RES_LASTSCHEDSDATE', 'RES_LASTSCHEDEDATE',
            'RES_AVAILABILITY', 'RES_CURRNUMPATIN', 'RES_CURRSESSSUMMARY',
            'RES_CURRNUMPATOUT', 'RES_CURRLOADLIMIT', 'RES_QUEUELEN',
            'RES_CURRSESSION_DR', 'RES_CURRPENDAPPT', 'RES_TYPE',
            'RES_SCHEDULEREQUIRED', 'RES_MRREQUEST', 'RES_OPERBOOKINGMETHOD',
            'RES_SCHEDULEFORTHISHOSPITAL', 'RES_REFHOSP_DR', 'RES_ROOM_DR',
            'RES_ALLOCATEDSCHEDULE', 'RES_DATEHOLD', 'RES_SHOWINOPERWB',
            'RES_DAYSOTCLOSED', 'RES_OPERTHEATRETYPE_DR', 'RES_ACTIVE',
            'RES_DATETO', 'RES_ADMITTINGRIGHTS', 'RES_IGNOREPUBHOL',
            'RES_DATEACTIVEFROM', 'RES_DATEACTIVETO', 'RES_CPCLINICOPTIONS',
            'RES_CPLOCATIONNO', 'RES_VENUE', 'RES_EXTERNALVENUE',
            'RES_EBOOKNOTES', 'RES_STOCKLOC_DR', 'RES_WLOUTPATIENTRIGHTS',
            'RES_WLTRIAGERIGHTS', 'RES_PRINCIPALCPNUMBER',
            'RES_BILLINGAGENTID', 'RES_COURIERCOPIES', 'RES_MAINLOCATION',
            'RES_CODETRANSLATED', 'RES_DESCTRANSLATED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}
SELECT * FROM {{ source('raw_trakcare', 'RB_RESOURCE') }}
{% endsnapshot %}