{% snapshot HIST_TRAKCARE_ARC_ITEMCAT %}

{{
    config(
        schema='TRAKCARE',
        unique_key='ARCIC_ROWID',
        strategy='check',
        check_cols=[
            'ARCIC_CODE', 'ARCIC_DESC', 'ARCIC_OWNER', 'ARCIC_DATETO',
            'ARCIC_ISTEST', 'ARCIC_DATEFROM', 'ARCIC_DOSETYPE',
            'ARCIC_EXECDOSE', 'ARCIC_EXECFLAG', 'ARCIC_EXECFREQ',
            'ARCIC_IVEXPIRY', 'ARCIC_TEMPLATE', 'ARCIC_AUTOORDER',
            'ARCIC_ORDCAT_DR', 'ARCIC_ORDERTYPE', 'ARCIC_EXPIRYDAYS',
            'ARCIC_BILLINGTYPE', 'ARCIC_CALCQTYFLAG', 'ARCIC_CREATEDDATE',
            'ARCIC_CREATEDTIME', 'ARCIC_DICOMRESULT', 'ARCIC_UPDATEDDATE',
            'ARCIC_UPDATEDTIME', 'ARCIC_DONTCREATEWL', 'ARCIC_EXECCATEG_DR',
            'ARCIC_FREQGROUP_DR', 'ARCIC_CODETABLETAGS', 'ARCIC_COMMISSIONING',
            'ARCIC_COUNTERTYPEDR', 'ARCIC_HL7RESULTTYPE', 'ARCIC_INHALEDMEDGAS',
            'ARCIC_LATERALITYREQ', 'ARCIC_LETTERTYPE_DR', 'ARCIC_NONREVIEWABLE',
            'ARCIC_OVERRIDEPRICE', 'ARCIC_PRESCREXPDAYS', 'ARCIC_SECSIGNFORADM',
            'ARCIC_CREATEDUSER_DR', 'ARCIC_ISCAREPLANGOAL', 'ARCIC_NURSEWORKBENCH',
            'ARCIC_ONLYSHOWVERRES', 'ARCIC_REVIEWREQUIRED', 'ARCIC_UPDATEDUSER_DR',
            'ARCIC_USEODBCFORWORD', 'ARCIC_DIRECTLYEXECUTE', 'ARCIC_LABORATORYCODES',
            'ARCIC_MARKREADYFORINV', 'ARCIC_RESTRICTEDORDER', 'ARCIC_PRESCRREPEATDAYS',
            'ARCIC_QUESTIONNAIRE_DR', 'ARCIC_RECIEVESPECIMENS', 'ARCIC_RENDERINGTRIGGER',
            'ARCIC_RESULTCATEGORIES', 'ARCIC_USERDEFWINDOW_DR', 'ARCIC_RESULTEPRCHART_DR',
            'ARCIC_TEXTRESULTTYPE_DR', 'ARCIC_DIAGNOSTICWAITTIME',
            'ARCIC_DISPLAYOPWHITEBOARD', 'ARCIC_WARNINGNONVERRESULT',
            'ARCIC_ADDTODIAGNOSTICSTAGE', 'ARCIC_EXECQUESTIONNAIRE_DR',
            'ARCIC_PHONEORDERREVIEWTIME', 'ARCIC_ALLOWQUESTEDITEXECORD',
            'ARCIC_READYFORINVOICEONPACK', 'ARCIC_IGNOREDISCORDITMINORDSET',
            'ARCIC_ALLOWTOENTERONERESULTONLY'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_trakcare', 'ARC_ITEMCAT') }}

{% endsnapshot %}