{% snapshot HIST_TRAKCARE_PA_PATMAS %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='TRAKCARE',
        unique_key='PAPMI_ROWID',
        strategy='check',
        check_cols=[
            'PAPMI_ROWID1', 'PAPMI_NO', 'PAPMI_ID', 'PAPMI_NAME', 'PAPMI_NAME2',
            'PAPMI_ALIAS', 'PAPMI_FOREIGNPHONENO', 'PAPMI_IPNO', 'PAPMI_OPNO',
            'PAPMI_DOB', 'PAPMI_ESTAGEYEAR', 'PAPMI_ESTAGEMONTH',
            'PAPMI_ESTAGETMSTMP', 'PAPMI_SEX_DR', 'PAPMI_SOUNDEX',
            'PAPMI_LANGPRIM_DR', 'PAPMI_ACTIVE', 'PAPMI_PATCATEGORY_DR',
            'PAPMI_HOMECLINICNO', 'PAPMI_NXTOPADMNO', 'PAPMI_LANGPRINTDR',
            'PAPMI_REMARK', 'PAPMI_LANGSECONDDR', 'PAPMI_DECEASED',
            'PAPMI_DECEASED_DATE', 'PAPMI_LOOKUPDISPLAY', 'PAPMI_DECEASEDTIME',
            'PAPMI_SURNAME', 'PAPMI_INDEXMARK', 'PAPMI_PAPER_DR',
            'PAPMI_BLACKLIST', 'PAPMI_MOTHER_DR', 'PAPMI_REFDOC_DR',
            'PAPMI_MEDICARE', 'PAPMI_NAME3', 'PAPMI_REFUND',
            'PAPMI_MEDICARESTRING', 'PAPMI_USERUPDATE', 'PAPMI_TRACESTATUS_DR',
            'PAPMI_MEDICARESUFFIX_DR', 'PAPMI_MEDICARECODE', 'PAPMI_ALLERGY',
            'PAPMI_EPRDESCRIPTION', 'PAPMI_CONCESSIONCARDNO',
            'PAPMI_CONCESSIONCARDEXPDATE', 'PAPMI_SAFETYNETCARDNO',
            'PAPMI_SAFETYNETCARDEXPDATE', 'PAPMI_DVANUMBER',
            'PAPMI_CARDTYPE_DR', 'PAPMI_MEDICAREEXPDATE', 'PAPMI_CHCPATIENT',
            'PAPMI_ESTIMATEDDEATHDATE', 'PAPMI_BATALLION',
            'PAPMI_HEALTHFUNDNO', 'PAPMI_COUNTRYOFBIRTH_DR', 'PAPMI_TITLE_DR',
            'PAPMI_PREFLANGUAGE_DR', 'PAPMI_CT_REGION_DR',
            'PAPMI_CT_PROVINCE_DR', 'PAPMI_GOVERNCARDNO',
            'PAPMI_INSURANCECARDHOLDER', 'PAPMI_CITYAREA_DR',
            'PAPMI_RESPONSIBLEFORPAYMENT', 'PAPMI_SECONDPHONE', 'PAPMI_EMAIL',
            'PAPMI_MOBPHONE', 'PAPMI_AUXINSTYPE_DR', 'PAPMI_INDIGSTAT_DR',
            'PAPMI_GPTEXT', 'PAPMI_DENTIST_DR', 'PAPMI_DENTISTCLINIC_DR',
            'PAPMI_VIPFLAG', 'PAPMI_GPORGADDRESS', 'PAPMI_CITYBIRTH_DR',
            'PAPMI_CT_HCA_DR', 'PAPMI_REQUIREASSISTANCEMEAL',
            'PAPMI_REQUIREASSISTANCEMENU', 'PAPMI_PENSIONTYPE_DR',
            'PAPMI_MOTHER1_DR', 'PAPMI_HEALTHCARDEXPIRYDATE', 'PAPMI_NAME4',
            'PAPMI_NAME5', 'PAPMI_NAME6', 'PAPMI_NAME7', 'PAPMI_NAME8',
            'PAPMI_PATIENTFUNDUPI', 'PAPMI_CHECKMEDICARE', 'PAPMI_CHECKFUND',
            'PAPMI_CHECKEPV', 'PAPMI_PAYORVERIFIEDDATE',
            'PAPMI_MEDICARECARDTYPE_DR', 'PAPMI_CHECKCONCESSION',
            'PAPMI_CONCESSIONVERIFIEDDATE', 'PAPMI_EMAILVALIDATIONSTATUS_DR'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *,
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_trakcare', 'PA_PATMAS') }}

{% endsnapshot %}