{% snapshot HIST_TRAKCARE_PAC_REFERRALPRIORITY %}
{{ config(unique_key='REFPRI_ROWID', strategy='check',
    check_cols=['REFPRI_CODE','REFPRI_DESC','REFPRI_OWNER','REFPRI_CANCER',
        'REFPRI_DATETO','REFPRI_DATEFROM','REFPRI_ICONNAME','REFPRI_CREATEDDATE',
        'REFPRI_CREATEDTIME','REFPRI_UPDATEDDATE','REFPRI_UPDATEDTIME',
        'REFPRI_ICONPRIORITY','REFPRI_NATIONALCODE','REFPRI_ADMISSIONTYPE',
        'REFPRI_CODETABLETAGS','REFPRI_CREATEDUSER_DR','REFPRI_UPDATEDUSER_DR',
        'REFPRI_MAXDAYSWAITAPPT'],
    invalidate_hard_deletes=True, dbt_valid_to_current="to_date('9999-12-31')") }}
SELECT * FROM {{ source('raw_trakcare', 'PAC_REFERRALPRIORITY') }}
{% endsnapshot %}