{% snapshot HIST_TRAKCARE_CT_CAREPROV %}

{{
    config(
        unique_key='CTPCP_ROWID',
        strategy='check',
        check_cols=[
            'CTPCP_CODE', 'CTPCP_DESC', 'CTPCP_ID', 'CTPCP_CATEGORY',
            'CTPCP_SMCNO', 'CTPCP_CARPRVTP_DR', 'CTPCP_ADDRTYPE_DR',
            'CTPCP_BLK', 'CTPCP_STNAME', 'CTPCP_LEVEL', 'CTPCP_UNIT',
            'CTPCP_CITY_DR', 'CTPCP_STATE_DR', 'CTPCP_ZIP_DR',
            'CTPCP_SPEC_DR', 'CTPCP_SUBSPEC_DR', 'CTPCP_TELO',
            'CTPCP_TELOEXT', 'CTPCP_TELH', 'CTPCP_PAGERNO',
            'CTPCP_HOSP_DR', 'CTPCP_CON1CODE_DR', 'CTPCP_CON2CODE_DR',
            'CTPCP_ACTIVEFLAG', 'CTPCP_VERSIONORIGIN_DR',
            'CTPCP_VERSIONNUMBER', 'CTPCP_VERSIONDATE', 'CTPCP_VERSIONTIME',
            'CTPCP_VERSIONDATETIME', 'CTPCP_AUTHORID', 'CTPCP_SPECIALISTYN',
            'CTPCP_FIRSTDIGITINQUEUE', 'CTPCP_DATEACTIVEFROM',
            'CTPCP_DATEACTIVETO', 'CTPCP_LINKDOCTOR_DR',
            'CTPCP_ALLOCATEDDOCTOR', 'CTPCP_SURGEON', 'CTPCP_ANAESTHETIST',
            'CTPCP_PRESCRIBERNUMBER', 'CTPCP_CPGROUP_DR', 'CTPCP_RESPUNIT_DR',
            'CTPCP_CTLOC_DR', 'CTPCP_TITLE', 'CTPCP_DOB',
            'CTPCP_MOBILEPHONE', 'CTPCP_FAX', 'CTPCP_MAILLIST',
            'CTPCP_EMAIL', 'CTPCP_PREFCONMETHOD', 'CTPCP_TEXTONE',
            'CTPCP_TEXTTWO', 'CTPCP_CONTACTFIRSTON', 'CTPCP_RADIOLOGIST',
            'CTPCP_ADMITTINGRIGHTS', 'CTPCP_ACCEPTANCE', 'CTPCP_PREVIOUS',
            'CTPCP_MANTOUXTEST', 'CTPCP_CONTINUING', 'CTPCP_NEW',
            'CTPCP_PREFMAILADDFLAD', 'CTPCP_UPDATEDATE', 'CTPCP_UPDATETIME',
            'CTPCP_UPDATEUSER_DR', 'CTPCP_BESTCONTACTTIME',
            'CTPCP_REFERRALDOCTOR_DR', 'CTPCP_FIRSTNAME', 'CTPCP_OTHERNAME',
            'CTPCP_TITLE_DR', 'CTPCP_SURNAME', 'CTPCP_HICAPPROVED',
            'CTPCP_PRACTITIONERFLAG1', 'CTPCP_CREATEDUSER_DR',
            'CTPCP_CREATEDDATE', 'CTPCP_CREATEDTIME', 'CTPCP_CREATEDHOSP_DR',
            'CTPCP_UPDATEHOSP_DR', 'CTPCP_TEXTTHREE', 'CTPCP_TEXTTITLE',
            'CTPCP_SIGNATURE', 'CTPCP_DOCTORSREPORTSTYPE', 'CTPCP_QUICKPRINT',
            'CTPCP_COURIER_DR', 'CTPCP_COURIERCOPIES',
            'CTPCP_DOCTORSREPORTSTO', 'CTPCP_DOCTORSREPORTSDELIVERYSORT',
            'CTPCP_SPECSTPALLIATIVECP', 'CTPCP_CUMULATIVEPREFERENCE',
            'CTPCP_CUMULATIVEORDER', 'CTPCP_CUMULATIVEEPISODES',
            'CTPCP_LANGUAGE_DR', 'CTPCP_WLOUTPATIENTRIGHTS',
            'CTPCP_WLTRIAGERIGHTS', 'CTPCP_REGISSUER', 'CTPCP_MANUALPRINT',
            'CTPCP_OTCONSULTANT', 'CTPCP_EXTERNALINTERFACEQUEUE_DR',
            'CTPCP_REPORTMODE', 'CTPCP_UPDATEDDATE', 'CTPCP_UPDATEDTIME',
            'CTPCP_UPDATEDUSER_DR', 'CTPCP_PATHOLOGYSELFDETERMINE',
            'CTPCP_SECONDARYPRESCRIBERNUMBER', 'CTPCP_PROVINCE_DR',
            'CTPCP_REGION_DR', 'CTPCP_CONFIDENTIALFAX',
            'CTPCP_CPGROUPAFFILIATIONS', 'CTPCP_EXTERNALCAREPROV',
            'CTPCP_PBSPROVIDERTYPE', 'CTPCP_YESNO1', 'CTPCP_YESNO2',
            'CTPCP_YESNO3', 'CTPCP_YESNO4', 'CTPCP_SEX_DR',
            'CTPCP_PREFLANGUAGE_DR', 'CTPCP_OTHERLANGUAGE_DR',
            'CTPCP_NATION_DR', 'CTPCP_TEXTFIELD', 'CTPCP_DEACTIVATIONREASON',
            'CTPCP_CODETRANSLATED', 'CTPCP_DESCTRANSLATED', 'CTPCP_ROWID1'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_trakcare', 'CT_CAREPROV') }}

{% endsnapshot %}