
WITH CTE_NULL_COUNTS AS
(
SELECT CLIENT_ID_HASH, SRC_SYS, SRC_SYS_CLIENT_ID,
       SUM(CASE WHEN FIRST_NAME IS NULL THEN 1 ELSE 0 END)  AS IS_FIRST_NAME_NULL,
       SUM(CASE WHEN LAST_NAME IS NULL THEN 1 ELSE 0 END)   AS IS_LAST_NAME_NULL,
       SUM(CASE WHEN DOB IS NULL THEN 1 ELSE 0 END)         AS IS_DOB_NULL,
       SUM(CASE WHEN ADDRESS IS NULL THEN 1 ELSE 0 END)     AS IS_ADDRESS_NULL,
       SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END)        AS IS_CITY_NULL,
       SUM(CASE WHEN POSTCODE IS NULL THEN 1 ELSE 0 END)    AS IS_POSTCODE_NULL,

FROM DEV_03_PREP_DB.DBT_SEANWOOLBHN_REF.PREP_REF_CLIENT_LINK_DETAILS
WHERE CLIENT_LINK_HASH IS NULL
GROUP BY ALL
)
SELECT CLIENT_ID_HASH,
       SRC_SYS, 
       SRC_SYS_CLIENT_ID,         
       IS_FIRST_NAME_NULL + IS_LAST_NAME_NULL + IS_DOB_NULL
       + IS_ADDRESS_NULL +  IS_CITY_NULL + IS_POSTCODE_NULL AS NULL_COLUMN_COUNT,
       CASE WHEN IS_FIRST_NAME_NULL::VARCHAR = '1' THEN 'YES' ELSE 'NO' END     AS IS_FIRST_NAME_NULL,
       CASE WHEN IS_LAST_NAME_NULL = 1 THEN 'YES' ELSE 'NO' END                 AS IS_LAST_NAME_NULL,
       CASE WHEN IS_DOB_NULL = 1 THEN 'YES' ELSE 'NO' END                       AS IS_DOB_NULL,
       CASE WHEN IS_ADDRESS_NULL = 1 THEN 'YES' ELSE 'NO' END                   AS IS_ADDRESS_NULL,
       CASE WHEN IS_CITY_NULL = 1 THEN 'YES' ELSE 'NO' END                      AS IS_CITY_NULL,
       CASE WHEN IS_POSTCODE_NULL = 1 THEN 'YES' ELSE 'NO' END                  AS IS_POSTCODE_NULL
FROM CTE_NULL_COUNTS