SELECT T1.CLIENT_ID_HASH, 
       T1.SRC_SYS               AS SOURCE_1, 
       T1.SRC_SYS_CLIENT_ID     AS CLIENT_ID_1, 
       T2.SRC_SYS               AS SOURCE_2, 
       T2.SRC_SYS_CLIENT_ID     AS CLIENT_ID_2
FROM DEV_03_PREP_DB.DBT_SEANWOOLBHN_REF.PREP_REF_CLIENT_LINK_DETAILS T1
INNER JOIN DEV_03_PREP_DB.DBT_SEANWOOLBHN_REF.PREP_REF_CLIENT_LINK_DETAILS T2
ON T1.CLIENT_ID_HASH = T2.CLIENT_ID_HASH
AND T1.SRC_SYS = T2.SRC_SYS
AND T1.SRC_SYS_CLIENT_ID <> T2.SRC_SYS_CLIENT_ID