SELECT 'SUPPORTABILITY'                     AS SRC_SYS, 
       'CLIENT_LIST_INC_PERSONAL_CONTACTS'  AS TABLE_NAME, 
       SUPPORTABILITY_ID, 
       FIRST_NAME, 
       LAST_NAME, 
       DATE_OF_BIRTH, 
       ADDRESS, 
       SUBURB, 
       POSTCODE

FROM {{ source('raw_supportability', 'CLIENT_LIST_INC_PERSONAL_CONTACTS') }}

WHERE UPPER(RELATIONSHIP) = 'CLIENT'
AND (NULLIF(SUPPORTABILITY_ID,'-') IS NULL
         OR FIRST_NAME IS NULL
         OR LAST_NAME IS NULL
         OR DATE_OF_BIRTH IS NULL
         OR NULLIF(ADDRESS,'.') IS NULL
         OR NULLIF(SUBURB,'.') IS NULL
         OR POSTCODE IS NULL)