SELECT 'BEST_PRACTICE'      AS SRC_SYS, 
       'BPS_SEARCH_RESULT'  AS TABLE_NAME, 
       INTERNALID, 
       FIRSTNAME, 
       SURNAME, 
       DOB, 
       ADDRESS1, 
       ADDRESS2, 
       CITY, 
       POSTCODE 

FROM {{ source('raw_best_practice', 'BPS_SEARCH_RESULT') }}

WHERE NULLIF(INTERNALID,'N/A') IS NULL
   OR NULLIF(FIRSTNAME,'N/A') IS NULL
   OR NULLIF(SURNAME,'N/A') IS NULL
   OR NULLIF(DOB,'N/A') IS NULL
   OR (NULLIF(ADDRESS1,'N/A') IS NULL AND NULLIF(ADDRESS2,'N/A') IS NULL)
   OR NULLIF(CITY,'N/A') IS NULL
   OR NULLIF(POSTCODE,'N/A') IS NULL