{% snapshot HIST_SUPPORTABILITY_ALLOCATIONS_REPORT %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='SUPPORTABILITY',
        unique_key='_AIRBYTE_RAW_ID',
        strategy='check',
        check_cols=[
            'FPM',
            'SITE',
            'PRICE',
            'ABSENT',
            '"BPR ID"',
            'FUNDING',
            'PROGRAM',
            'SERVICE',
            'QUANTITY',
            '"CLIENT ID"',
            '"COST TYPE"',
            '"DEBTOR ID"',
            '"NO CHARGE"',
            '"CLAIM TYPE"',
            '"ACTIVITY ID"',
            '"NDIS NUMBER"',
            '"CLAIM STATUS"',
            '"INVOICE DATE"',
            '"ACTIVITY NAME"',
            '"AGENCY CAPPED"',
            '"CLAIMED PRICE"',
            '"FINANCE NOTES"',
            '"PRICE PORTION"',
            '"STAFF MEMBERS"',
            '"ACTIVITY HOURS"',
            '"CLIENT SURNAME"',
            '"INVOICE NUMBER"',
            '"OUTCOME DOMAIN"',
            '"VALUE INCL GST"',
            '"SUPPORT PURPOSE"',
            '"UNIT OF MEASURE"',
            '"ACTIVITY TO DATE"',
            '"BPRF UPLOAD DATE"',
            '"CLIENT DEBTOR ID"',
            '"FUNDING END DATE"',
            '"INVOICE BATCH ID"',
            '"SUPPORT CATEGORY"',
            '"ACTIVITY LOCATION"',
            '"BPR CREATION DATE"',
            '"CLIENT FIRST NAME"',
            '"CLIENT FUNDING ID"',
            '"PROCESSING STATUS"',
            '"START DAY OF WEEK"',
            '"SUPPORT ITEM NAME"',
            '"FUNDING START DATE"',
            '"PROGRAM OF SUPPORT"',
            '"REGISTRATION GROUP"',
            '"NDIA REJECTED REASON"',
            '"ACTIVITY SIGN OFF DATE"',
            '"CLAIM REFERENCE NUMBER"',
            '"CLAIMED VALUE INCL GST"',
            '"SUPPORT ITEM REFERENCE"',
            '"CLIENT SUPPORT LOG DATE"',
            '"NOTIONAL UNIT PRICE SUPPORT"',
            '"CLIENT FUNDING ON BILLING HOLD"',
            '"SHORT NOTICE CANCELLATION REASON"',
            '"CLIENT FUNDING ON BILLING HOLD BY"',
            '"SUPPORTABILITY CLIENT CUSTOMER ID"',
            '"SUPPORTABILITY DEBTOR CUSTOMER ID"',
            '"CLIENT FUNDING ON BILLING HOLD SINCE"',
            '_AB_SOURCE_FILE_URL',
            '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META,
    _AIRBYTE_GENERATION_ID,
    FPM,
    SITE,
    PRICE,
    ABSENT,
    "BPR ID",
    FUNDING,
    PROGRAM,
    SERVICE,
    QUANTITY,
    "CLIENT ID",
    "COST TYPE",
    "DEBTOR ID",
    "NO CHARGE",
    "CLAIM TYPE",
    "ACTIVITY ID",
    "NDIS NUMBER",
    "CLAIM STATUS",
    "INVOICE DATE",
    "ACTIVITY NAME",
    "AGENCY CAPPED",
    "CLAIMED PRICE",
    "FINANCE NOTES",
    "PRICE PORTION",
    "STAFF MEMBERS",
    "ACTIVITY HOURS",
    "CLIENT SURNAME",
    "INVOICE NUMBER",
    "OUTCOME DOMAIN",
    "VALUE INCL GST",
    "SUPPORT PURPOSE",
    "UNIT OF MEASURE",
    "ACTIVITY TO DATE",
    "BPRF UPLOAD DATE",
    "CLIENT DEBTOR ID",
    "FUNDING END DATE",
    "INVOICE BATCH ID",
    "SUPPORT CATEGORY",
    "ACTIVITY LOCATION",
    "BPR CREATION DATE",
    "CLIENT FIRST NAME",
    "CLIENT FUNDING ID",
    "PROCESSING STATUS",
    "START DAY OF WEEK",
    "SUPPORT ITEM NAME",
    "FUNDING START DATE",
    "PROGRAM OF SUPPORT",
    "REGISTRATION GROUP",
    "NDIA REJECTED REASON",
    "ACTIVITY SIGN OFF DATE",
    "CLAIM REFERENCE NUMBER",
    "CLAIMED VALUE INCL GST",
    "SUPPORT ITEM REFERENCE",
    "CLIENT SUPPORT LOG DATE",
    "NOTIONAL UNIT PRICE SUPPORT",
    "CLIENT FUNDING ON BILLING HOLD",
    "SHORT NOTICE CANCELLATION REASON",
    "CLIENT FUNDING ON BILLING HOLD BY",
    "SUPPORTABILITY CLIENT CUSTOMER ID",
    "SUPPORTABILITY DEBTOR CUSTOMER ID",
    "CLIENT FUNDING ON BILLING HOLD SINCE",
    _AB_SOURCE_FILE_URL,
    _AB_SOURCE_FILE_LAST_MODIFIED,
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_supportability', 'ALLOCATIONS_REPORT') }}

{% endsnapshot %}