{% snapshot HIST_SUPPORTABILITY_ALLOCATIONS_REPORT %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='SUPPORTABILITY',
        unique_key='_AIRBYTE_RAW_ID',
        strategy='check',
        check_cols=[
            'FPM', 'SITE', 'PRICE', 'ABSENT', 'FUNDING', 'PROGRAM',
            'SERVICE', 'QUANTITY', 'BPR_ID', 'CLIENT_ID', 'COST_TYPE',
            'DEBTOR_ID', 'NO_CHARGE', 'CLAIM_TYPE', 'ACTIVITY_ID',
            'NDIS_NUMBER', 'CLAIM_STATUS', 'INVOICE_DATE', 'ACTIVITY_NAME',
            'AGENCY_CAPPED', 'CLAIMED_PRICE', 'FINANCE_NOTES',
            'PRICE_PORTION', 'STAFF_MEMBERS', 'ACTIVITY_HOURS',
            'CLIENT_SURNAME', 'INVOICE_NUMBER', 'OUTCOME_DOMAIN',
            'VALUE_INCL_GST', 'SUPPORT_PURPOSE', 'UNIT_OF_MEASURE',
            'ACTIVITY_TO_DATE', 'BPRF_UPLOAD_DATE', 'CLIENT_DEBTOR_ID',
            'FUNDING_END_DATE', 'INVOICE_BATCH_ID', 'SUPPORT_CATEGORY',
            'ACTIVITY_LOCATION', 'BPR_CREATION_DATE', 'CLIENT_FIRST_NAME',
            'CLIENT_FUNDING_ID', 'PROCESSING_STATUS', 'START_DAY_OF_WEEK',
            'SUPPORT_ITEM_NAME', 'FUNDING_START_DATE', 'PROGRAM_OF_SUPPORT',
            'REGISTRATION_GROUP', 'NDIA_REJECTED_REASON',
            'ACTIVITY_SIGN_OFF_DATE', 'CLAIM_REFERENCE_NUMBER',
            'CLAIMED_VALUE_INCL_GST', 'SUPPORT_ITEM_REFERENCE',
            'CLIENT_SUPPORT_LOG_DATE', 'ACTIVITY_FROM_DATE',
            'NOTIONAL_UNIT_PRICE_SUPPORT', 'CLIENT_FUNDING_ON_BILLING_HOLD',
            'SHORT_NOTICE_CANCELLATION_REASON',
            'CLIENT_FUNDING_ON_BILLING_HOLD_BY',
            'SUPPORTABILITY_CLIENT_CUSTOMER_ID',
            'SUPPORTABILITY_DEBTOR_CUSTOMER_ID',
            'CLIENT_FUNDING_ON_BILLING_HOLD_SINCE',
            '_AB_SOURCE_FILE_URL', '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *,
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_supportability', 'ALLOCATIONS_REPORT') }}

{% endsnapshot %}