{% snapshot HIST_CONNX_EMPLOYEE_DATA %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='CONNX',
        unique_key='_AIRBYTE_RAW_ID',
        strategy='check',
        check_cols=[
            'SURNAME',
            '"DATE HIRED"',
            'DEPARTMENT',
            '"FIRST NAME"',
            '"EMPLOYEE NO"',
            '"MIDDLE NAME"',
            '"RDO APPROVED"',
            '"WORK PATTERN"',
            '"CONTRACT HOURS"',
            '"PREFERRED NAME"',
            '"EMPLOYMENT TYPE"',
            '"CURRENT POSITION"',
            '"TERMINATION DATE"',
            '"PROBATION END DATE"',
            '"TIL LEAVE APPROVED"',
            '"WORK EMAIL ADDRESS"',
            '"FIXED TERM END DATE"',
            '"RDO BALANCE ACCRUED"',
            '"REPORTS TO(POSITION)"',
            '"ANNUAL LEAVE APPROVED"',
            '"FIXED TERM START DATE"',
            '"PERSONAL LEAVE APPROVED"',
            '"POSITION ALLOCATED HOURS"',
            '"REPORTS TO (MANAGER NAME)"',
            '"TIL LEAVE BALANCE ACCRUED"',
            '"ANNUAL LEAVE BALANCE ACCRUED"',
            '"PERSONAL LEAVE BALANCE ACCRUED"',
            '"TERMINATION REASON FOR LEAVING"',
            '"USED DEFINED PURCHASED LEAVE ACCRUED"',
            '"USER DEFINED PURCHASED LEAVE APPROVED"',
            '_AB_SOURCE_FILE_URL',
            '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META,
    _AIRBYTE_GENERATION_ID,
    SURNAME,
    "DATE HIRED",
    DEPARTMENT,
    "FIRST NAME",
    "EMPLOYEE NO",
    "MIDDLE NAME",
    "RDO APPROVED",
    "WORK PATTERN",
    "CONTRACT HOURS",
    "PREFERRED NAME",
    "EMPLOYMENT TYPE",
    "CURRENT POSITION",
    "TERMINATION DATE",
    "PROBATION END DATE",
    "TIL LEAVE APPROVED",
    "WORK EMAIL ADDRESS",
    "FIXED TERM END DATE",
    "RDO BALANCE ACCRUED",
    _AB_SOURCE_FILE_URL,
    "REPORTS TO(POSITION)",
    "ANNUAL LEAVE APPROVED",
    "FIXED TERM START DATE",
    "PERSONAL LEAVE APPROVED",
    "POSITION ALLOCATED HOURS",
    "REPORTS TO (MANAGER NAME)",
    "TIL LEAVE BALANCE ACCRUED",
    "ANNUAL LEAVE BALANCE ACCRUED",
    _AB_SOURCE_FILE_LAST_MODIFIED,
    "PERSONAL LEAVE BALANCE ACCRUED",
    "TERMINATION REASON FOR LEAVING",
    "USED DEFINED PURCHASED LEAVE ACCRUED",
    "USER DEFINED PURCHASED LEAVE APPROVED",
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_connx', 'EMPLOYEE_DATA') }}

{% endsnapshot %}