SELECT DISTINCT
    SRC_SYS,
    SRC_SYS_CLIENT_ID,
    UPPER(FIRST_NAME || LAST_NAME || CAST(DOB AS VARCHAR) || ADDRESS || CITY || POSTCODE) AS CLIENT_MATCH,
    UPPER(FIRST_NAME || LAST_NAME || ADDRESS || CITY || POSTCODE) AS NAME_ADD,
    UPPER(FIRST_NAME || LAST_NAME || CAST(DOB AS VARCHAR))        AS NAME_DOB,
    FIRST_NAME,
    LAST_NAME,
    DOB,
    EMAIL,
    MOBILE_PHONE,
    ADDRESS,
    CITY,
    POSTCODE

FROM (
    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS, CITY, POSTCODE
    FROM {{ ref('prep_src_client_trakcare') }}

    UNION ALL

    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS, CITY, POSTCODE
    FROM {{ ref('prep_src_client_best_practice') }}

    UNION ALL

    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS, CITY, POSTCODE
    FROM {{ ref('prep_src_client_e_tools') }}

    UNION ALL

    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS, CITY, POSTCODE
    FROM {{ ref('prep_src_client_echidna') }}

    UNION ALL

    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS_1, CITY, POSTCODE
    FROM {{ ref('prep_src_client_supportability') }}

    UNION ALL

    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS_1, CITY, POSTCODE
    FROM {{ ref('prep_src_client_titanium') }}

    UNION ALL

    SELECT SRC_SYS, SRC_SYS_CLIENT_ID, FIRST_NAME, LAST_NAME,
           DOB, EMAIL, MOBILE_PHONE, ADDRESS, CITY, POSTCODE
    FROM {{ ref('prep_src_client_trips') }}
) AS all_clients