{% snapshot HIST_BETTER_IMPACT_PROFILE_EXPORT %}

{{
    config(
        unique_key='DATABASEUSERID',
        strategy='check',
        check_cols=[
            'AGE', 'SUFFIX', 'BIRTHDAY', 'LASTNAME', 'USERNAME',
            'FIRSTNAME', 'MIDDLENAME', 'POSTALCODE', 'SALUTATION',
            'CLIENTSTATUS', 'EMAILADDRESS', 'DATABASEUSERID',
            'LEGALFIRSTNAME', 'CLIENTDATEJOINED',
            'YEARSSINCECLIENTDATEJOINED', 'DATEOFLASTCLIENTSTATUSCHANGE',
            'CF_ABOUT_YOUR_CLIENT_GENDER', 'CF_MATCH_DETAILS_DATE_OF_MATCH',
            'CF_MATCH_DETAILS_NAME_OF_VISITOR',
            'CF_ABOUT_YOUR_CLIENT_WORK_BACKGROUND',
            'CF_MATCH_DETAILS_POTENTIAL_VOLUNTEER',
            'CF_ABOUT_YOUR_CLIENT_PREFERRED_LANGUAGE',
            'CF_AGED_CARE_FACILITY_MATCH_INFORMATION_AGED_CARE_FACILITY_LIST_',
            'CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_IF_MORE_THAN_ONE_SPECIAL_NEED_APPLIES_PLEASE_LIST_HERE',
            'CF_AGED_CARE_FUNDING_DETAILS_IF_RELEVANT_SELECT_NAME_OF_HOME_CARE_PACKAGE_PROVIDER_OR_RESIDENTIAL_AGED_CARE_FACILITY_WHERE_THE_CLIENT_RESIDES',
            'CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_DOES_THE_RECIPIENT_IDENTIFY_AS_BEING_FROM_A_SPECIAL_NEEDS_GROUP_',
            'CF_ABOUT_YOUR_CLIENT_COUNTRY_OF_ORIGIN',
            '_AB_SOURCE_FILE_URL', '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_better_impact', 'PROFILE_EXPORT') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATABASEUSERID ORDER BY _AIRBYTE_GENERATION_ID DESC) = 1

{% endsnapshot %}