{% snapshot HIST_BETTER_IMPACT_PROFILE_EXPORT %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='BETTER_IMPACT',
        unique_key='_AIRBYTE_RAW_ID',
        strategy='check',
        check_cols=[
            'AGE', 'SUFFIX', 'BIRTHDAY', 'LASTNAME', 'USERNAME',
            'FIRSTNAME', 'MIDDLENAME', 'POSTALCODE', 'SALUTATION',
            'CLIENTSTATUS', 'EMAILADDRESS', 'DATABASEUSERID',
            'LEGALFIRSTNAME', 'CLIENTDATEJOINED',
            'YEARSSINCECLIENTDATEJOINED', 'DATEOFLASTCLIENTSTATUSCHANGE',
            'CF_ABOUT_YOUR_CLIENT_GENDER', 'CF_MATCH_DETAILS_DATE_OF_MATCH',
            'CF_MATCH_DETAILS_NAME_OF_VISITOR',
            'CF_ABOUT_YOUR_CLIENT_WORK_BACKGROUND',
            'CF_MATCH_DETAILS_POTENTIAL_VOLUNTEER',
            'CF_ABOUT_YOUR_CLIENT_PREFERRED_LANGUAGE',
            '"CF_AGED_CARE_FACILITY_MATCH_INFORMATION__AGED_CARE_FACILITY_(LIST)"',
            '"CF_SPECIAL_NEEDS_GROUPS_(THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT._OF_HEALTH)_IF_MORE_THAN_ONE_SPECIAL_NEED_APPLIES_PLEASE_LIST_HERE"',
            'CF_AGED_CARE_FUNDING_DETAILS_IF_RELEVANT_SELECT_NAME_OF_HOME_CARE_PACKAGE_PROVIDER_OR_RESIDENTIAL_AGED_CARE_FACILITY_WHERE_THE_CLIENT_RESIDES',
            '"CF_SPECIAL_NEEDS_GROUPS_(THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT._OF_HEALTH)_DOES_THE_RECIPIENT_IDENTIFY_AS_BEING_FROM_A_SPECIAL_NEEDS_GROUP?"',
            'CF_ABOUT_YOUR_CLIENT_COUNTRY_OF_ORIGIN',
            '_AB_SOURCE_FILE_URL', '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *,
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_better_impact', 'PROFILE_EXPORT') }}

{% endsnapshot %}