{% snapshot HIST_BETTER_IMPACT_VOLUNTEER_INFORMATION %}

{{
    config(
        unique_key='DATABASEUSERID',
        strategy='check',
        check_cols=[
            'BIRTHDAY', 'LASTNAME', 'FIRSTNAME', 'POSTALCODE',
            'DATABASEUSERID', 'VOLUNTEERSTATUS', 'VOLUNTEERDATEJOINED',
            'DATEOFLASTVOLUNTEERSTATUSCHANGE',
            'CF_ABOUT_YOU_PLEASE_INDICATE_YOUR_GENDER',
            'CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_IF_MORE_THAN_ONE_SPECIAL_NEED_APPLIES_PLEASE_LIST_HERE',
            'CF_SPECIAL_NEEDS_GROUPS_THIS_INFORMATION_IS_REQUESTED_BY_THE_DEPT_OF_HEALTH_DOES_THE_RECIPIENT_IDENTIFY_AS_BEING_FROM_A_SPECIAL_NEEDS_GROUP_',
            '_AB_SOURCE_FILE_URL', '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_better_impact', 'VOLUNTEER_INFORMATION') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATABASEUSERID ORDER BY _AIRBYTE_GENERATION_ID DESC) = 1

{% endsnapshot %}