{% snapshot HIST_BETTER_IMPACT_PROFILE_EXPORT %}

{{
    config(
        target_database='DEV_02_HIST_DB',
        target_schema='BETTER_IMPACT',
        unique_key='_AIRBYTE_RAW_ID',
        strategy='check',
        check_cols=[
            'AGE',
            'SUFFIX',
            'BIRTHDAY',
            'LASTNAME',
            'USERNAME',
            'FIRSTNAME',
            'MIDDLENAME',
            'POSTALCODE',
            'SALUTATION',
            'CLIENTSTATUS',
            'EMAILADDRESS',
            'DATABASEUSERID',
            'LEGALFIRSTNAME',
            'CLIENTDATEJOINED',
            'YEARSSINCECLIENTDATEJOINED',
            'DATEOFLASTCLIENTSTATUSCHANGE',
            '"CF - ABOUT YOUR CLIENT - GENDER"',
            '"CF - MATCH DETAILS - DATE OF MATCH"',
            '"CF - MATCH DETAILS - NAME OF VISITOR"',
            '"CF - ABOUT YOUR CLIENT - WORK BACKGROUND"',
            '"CF - MATCH DETAILS - POTENTIAL VOLUNTEER"',
            '"CF - ABOUT YOUR CLIENT - COUNTRY OF ORIGIN"',
            '"CF - ABOUT YOUR CLIENT - PREFERRED LANGUAGE"',
            '"CF - AGED CARE FACILITY MATCH INFORMATION  - AGED CARE FACILITY (LIST)"',
            '"CF - SPECIAL NEEDS GROUPS (THIS INFORMATION IS REQUESTED BY THE DEPT. OF HEALTH) - IF MORE THAN ONE SPECIAL NEED APPLIES PLEASE LIST HERE"',
            '"CF - AGED CARE FUNDING DETAILS - IF RELEVANT SELECT NAME OF HOME CARE PACKAGE PROVIDER OR RESIDENTIAL AGED CARE FACILITY WHERE THE CLIENT RESIDES"',
            '"CF - SPECIAL NEEDS GROUPS (THIS INFORMATION IS REQUESTED BY THE DEPT. OF HEALTH) - DOES THE RECIPIENT IDENTIFY AS BEING FROM A SPECIAL NEEDS GROUP?"',
            '_AB_SOURCE_FILE_URL',
            '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META,
    _AIRBYTE_GENERATION_ID,
    AGE,
    SUFFIX,
    BIRTHDAY,
    LASTNAME,
    USERNAME,
    FIRSTNAME,
    MIDDLENAME,
    POSTALCODE,
    SALUTATION,
    CLIENTSTATUS,
    EMAILADDRESS,
    DATABASEUSERID,
    LEGALFIRSTNAME,
    CLIENTDATEJOINED,
    _AB_SOURCE_FILE_URL,
    YEARSSINCECLIENTDATEJOINED,
    DATEOFLASTCLIENTSTATUSCHANGE,
    _AB_SOURCE_FILE_LAST_MODIFIED,
    "CF - ABOUT YOUR CLIENT - GENDER",
    "CF - MATCH DETAILS - DATE OF MATCH",
    "CF - MATCH DETAILS - NAME OF VISITOR",
    "CF - ABOUT YOUR CLIENT - WORK BACKGROUND",
    "CF - MATCH DETAILS - POTENTIAL VOLUNTEER",
    "CF - ABOUT YOUR CLIENT - COUNTRY OF ORIGIN",
    "CF - ABOUT YOUR CLIENT - PREFERRED LANGUAGE",
    "CF - AGED CARE FACILITY MATCH INFORMATION  - AGED CARE FACILITY (LIST)",
    "CF - SPECIAL NEEDS GROUPS (THIS INFORMATION IS REQUESTED BY THE DEPT. OF HEALTH) - IF MORE THAN ONE SPECIAL NEED APPLIES PLEASE LIST HERE",
    "CF - AGED CARE FUNDING DETAILS - IF RELEVANT SELECT NAME OF HOME CARE PACKAGE PROVIDER OR RESIDENTIAL AGED CARE FACILITY WHERE THE CLIENT RESIDES",
    "CF - SPECIAL NEEDS GROUPS (THIS INFORMATION IS REQUESTED BY THE DEPT. OF HEALTH) - DOES THE RECIPIENT IDENTIFY AS BEING FROM A SPECIAL NEEDS GROUP?",
    CURRENT_TIMESTAMP() AS _stg_loaded_at

FROM {{ source('raw_better_impact', 'PROFILE_EXPORT') }}

{% endsnapshot %}