{% snapshot HIST_BETTER_IMPACT_PIVOTED_FEEDBACK_REPORT %}

{{
    config(
        unique_key="DATABASEUSERID||'-'||DATEVOLUNTEERED||'-'||FF_NAME_OF_RESIDENT",
        strategy='check',
        check_cols=[
            'LASTNAME', 'USERNAME', 'FIRSTNAME', 'HOURSWORKED',
            'ACTIVITYNAME', 'DATABASEUSERID', 'DATEVOLUNTEERED',
            'FF_NO_OF_VISITS', 'FF_TYPE_OF_VISIT', 'ACTIVITYCATEGORYNAME',
            'FF_CLIENT_CONCERNS', 'FF_MATCH_END_REASON',
            'FF_NAME_OF_RESIDENT', 'FF_GOOD_NEWS_STORIES',
            'ACTIVITYREPORTGROUPNAME', 'FF_CLIENT_CONCERNS_1',
            'FF_GOOD_NEWS_STORIES_1',
            'FF_IF_NO_VISITS_WERE_MADE_PLEASE_INDICATE_REASON', 'FF_HMS',
            '_AB_SOURCE_FILE_URL', '_AB_SOURCE_FILE_LAST_MODIFIED'
        ],
        invalidate_hard_deletes=True,
        dbt_valid_to_current="to_date('9999-12-31')"
    )
}}

SELECT
    *

FROM {{ source('raw_better_impact', 'PIVOTED_FEEDBACK_REPORT') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATABASEUSERID, DATEVOLUNTEERED, FF_NAME_OF_RESIDENT ORDER BY _AIRBYTE_GENERATION_ID DESC) = 1

{% endsnapshot %}